import Solidity.Corpus.Calculus.TestSuite.Part01
import Solidity.Corpus.Calculus.TestSuite.Part02
import Solidity.Corpus.Calculus.TestSuite.Part03
import Solidity.Corpus.Calculus.TestSuite.Part04
import Solidity.Corpus.Calculus.TestSuite.Part05
import Solidity.Corpus.Calculus.TestSuite.Part06
import Solidity.Corpus.Calculus.TestSuite.Part07
import Solidity.Corpus.Calculus.TestSuite.Part08
import Solidity.Corpus.Calculus.TestSuite.Part09
import Solidity.Corpus.Calculus.TestSuite.Part10
import Solidity.Corpus.Calculus.TestSuite.Part11
