import Solidity.Examples.Solkey.TestSuite
import Solidity.Examples.Solkey.SolcExpressions
import Solidity.Examples.Solkey.SolcStructs
import Solidity.Examples.Solkey.SolcArrays
import Solidity.Examples.Solkey.SolcMemory
import Solidity.Examples.Solkey.SolcMappings
import Solidity.Examples.Solkey.SolcControlFlow
import Solidity.Examples.Solkey.Net
import Solidity.Examples.Solkey.Rules
