import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcMemory.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcMemory

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcMemory.memoryStructDefaultsToZero` (solc/SolcMemory.sol).

solc: structs/memory_structs_read_write.sol (`testInit`) — a fresh memory struct reads
as all zeros. -/
theorem solkey_solc_Memory_memoryStructDefaultsToZero :
    (sol!{ < Inner memory mv;
             assert((mv@Inner.a == 0));
             assert((mv@Inner.b == 0));
             assert((mv@Inner.c == 0)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.memoryStructWriteRead` (solc/SolcMemory.sol).

solc: structs/memory_structs_read_write.sol (`testAssign`) — member writes on a memory
struct read back. -/
theorem solkey_solc_Memory_memoryStructWriteRead :
    (sol!{ < Inner memory mv;
             mv@Inner.a = 1;
             mv@Inner.b = 2;
             mv@Inner.c = 3;
             assert((mv@Inner.a == 1));
             assert((mv@Inner.b == 2));
             assert((mv@Inner.c == 3)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.storageArrayElementCopiedIntoMemory` (solc/SolcMemory.sol).

solc: structs/memory_structs_read_write.sol (`testCopyRead`) — the upstream
`S memory s = data[2];` copy out of a storage array element.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Memory_storageArrayElementCopiedIntoMemory :
    (sol!{ < (inners@@InnerArray).push();
             (inners@@InnerArray).push();
             (inners@@InnerArray).push();
             inners@@InnerArray[2].a = 1;
             inners@@InnerArray[2].b = 2;
             inners@@InnerArray[2].c = 3;
             Inner memory mv = inners@@InnerArray[2];
             assert((mv@Inner.a == 1));
             assert((mv@Inner.b == 2));
             assert((mv@Inner.c == 3)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.nestedStorageStructToMemory` (solc/SolcMemory.sol).

solc: structs/struct_storage_to_memory.sol — the upstream `X memory m = x;` over a
struct that nests another struct. -/
theorem solkey_solc_Memory_nestedStorageStructToMemory :
    (sol!{ < outerX@@Outer.a = 12;
             outerX@@Outer.s.a = 42;
             outerX@@Outer.s.b = 23;
             outerX@@Outer.s.c = 34;
             Outer memory mv = outerX@@Outer;
             assert((mv@Outer.a == 12));
             assert((mv@Outer.s.a == 42));
             assert((mv@Outer.s.b == 23));
             assert((mv@Outer.s.c == 34)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.memoryStructToStorage` (solc/SolcMemory.sol).

solc: structs/struct_memory_to_storage.sol — a memory struct assigned into storage. -/
theorem solkey_solc_Memory_memoryStructToStorage :
    (sol!{ < Inner memory mv;
             mv@Inner.a = 1;
             mv@Inner.b = 2;
             mv@Inner.c = 3;
             innerS@@Inner = mv@Inner;
             assert((innerS@@Inner.a == 1));
             assert((innerS@@Inner.b == 2));
             assert((innerS@@Inner.c == 3)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.storageToMemoryCopyIsDeep` (solc/SolcMemory.sol).

solc: structs/copy_from_storage.sol — the storage-to-memory copy is deep: a later write
to the storage source does not reach the memory copy. -/
theorem solkey_solc_Memory_storageToMemoryCopyIsDeep :
    (sol!{ < outerX@@Outer.s.a = 17;
             Inner memory mv = outerX@@Outer.s;
             outerX@@Outer.s.a = 18;
             assert((mv@Inner.a == 17)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.memoryToStorageCopyIsDeep` (solc/SolcMemory.sol).

solc: structs/copy_to_mapping.sol — the memory-to-storage copy is deep in the other
direction too. -/
theorem solkey_solc_Memory_memoryToStorageCopyIsDeep :
    (sol!{ < Inner memory mv;
             mv@Inner.a = 50;
             innerS@@Inner = mv@Inner;
             mv@Inner.a = 51;
             assert((innerS@@Inner.a == 50)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.memoryAliasIsNotACopy` (solc/SolcMemory.sol).

solc: structs/memory_structs_nested.sol — a memory struct member is a reference, so two
locals bound to it alias each other. -/
theorem solkey_solc_Memory_memoryAliasIsNotACopy :
    (sol!{ < Outer memory mv;
             Inner memory mv2 = mv@Outer.s;
             mv2@Inner.a = 100;
             assert((mv@Outer.s.a == 100)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

/-- solkey `SolcMemory.storageArrayCopiedIntoMemory` (solc/SolcMemory.sol).

solc: array/copying/array_copy_storage_to_memory.sol — a whole storage array copied
into memory.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Memory_storageArrayCopiedIntoMemory :
    (sol!{ < (prims@@UintArray).push();
             (prims@@UintArray).push();
             prims@@UintArray[0] = 3;
             prims@@UintArray[1] = 4;
             UintArray memory mv = prims@@UintArray;
             assert((mv@UintArray[0] == 3));
             assert((mv@UintArray[1] == 4)) > (true) }).Holds
      State.solcMemoryStore := by
  sol_wp

end SolcMemory
end Solkey
end Solidity
