import Solidity.Wp.Verifier

/-!
# solkey `TestSuite.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace TestSuite

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.additionStorageWrite` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5, y = 7.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_additionStorageWrite :
    (sol!{ < uint x = 5;
             uint y = 7;
             alice.age = x + y;
             uint r = alice.age;
             assert((r == 12)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootReadWrite` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootReadWrite :
    (sol!{ < age = 34;
             uint r = age;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteRead` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldWriteRead :
    (sol!{ < alice.age = 34;
             uint r = alice.age;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepAddAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepAddAssign :
    (sol!{ < alice.account.balance = 30;
             alice.account.balance += 4;
             uint r = alice.account.balance;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldGlobalAge` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldGlobalAge :
    (sol!{ < alice.age = 34;
             assert((alice.age == 34));
             uint r = alice.age;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageAliasWrite` (TestSuite.sol). -/
theorem solkey_TestSuite_storageAliasWrite :
    (sol!{ < Person storage p = alice;
             Account storage acc = p@Person.account;
             acc@Account.balance = 100;
             p@Person.account.token.value = 3;
             assert((alice.account.balance == 100));
             assert((alice.account.token.value == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexRootMapping` (TestSuite.sol). -/
theorem solkey_TestSuite_storageIndexRootMapping :
    (sol!{ < balances[1] = 42;
             uint r = balances[1];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexAddAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexAddAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             values[1] += 2;
             uint r = values[1];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexMappingAddAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageIndexMappingAddAssign :
    (sol!{ < balances[1] = 40;
             balances[1] += 2;
             uint r = balances[1];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexReadComplexReceiverBindLocalRoot` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexReadComplexReceiverBindLocalRoot :
    (sol!{ < (bucket@@TokenBucket.tokens).push();
             bucket@@TokenBucket.tokens[0].value = 9;
             Token storage t = bucket@@TokenBucket.tokens[0];
             uint r = t@Token.value;
             assert((r == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteComplexReceiverCopySource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexWriteComplexReceiverCopySource :
    (sol!{ < (bucket@@TokenBucket.tokens).push();
             alice.account.token.value = 7;
             Token storage tokRef = alice.account.token;
             bucket@@TokenBucket.tokens[0] = tokRef@Token;
             uint r = bucket@@TokenBucket.tokens[0].value;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteRootRhsComplexReceiver` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldWriteRootRhsComplexReceiver :
    (sol!{ < tok@@Token.value = 7;
             alice.account.token = tok@@Token;
             uint r = alice.account.token.value;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteRootRhsComplexReceiver` (TestSuite.sol). -/
theorem solkey_TestSuite_storageIndexWriteRootRhsComplexReceiver :
    (sol!{ < total = 9;
             ledger@@Ledger.balances[3] = total;
             uint r = ledger@@Ledger.balances[3];
             assert((r == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushValue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushValue :
    (sol!{ < values.push();
             values.push();
             values.push(42);
             assert((values[2] == 42));
             assert((values.length == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushComplexReceiverNonsimpleArg` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 40, y = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushComplexReceiverNonsimpleArg :
    (sol!{ < matrix.push();
             uint x = 40;
             uint y = 2;
             matrix[0].push(x + y);
             uint r = matrix[0][0];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushValueCopySource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushValueCopySource :
    (sol!{ < tok@@Token.value = 7;
             (tokens@@TokenArray).push(tok@@Token);
             assert((tokens@@TokenArray[0].value == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.requireTrueLiteral` (TestSuite.sol). -/
theorem solkey_TestSuite_requireTrueLiteral :
    (sol!{ < require(true);
             assert(true) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolRootReadWrite` (TestSuite.sol). -/
theorem solkey_TestSuite_storageBoolRootReadWrite :
    (sol!{ < flag@@bool = true;
             bool r = flag@@bool;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolRootCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_storageBoolRootCopy :
    (sol!{ < flag@@bool = true;
             flag2@@bool = flag@@bool;
             bool r = flag2@@bool;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolFieldRead` (TestSuite.sol). -/
theorem solkey_TestSuite_storageBoolFieldRead :
    (sol!{ < toggle@@Toggle.on = true;
             bool r = toggle@@Toggle.on;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolMappingRead` (TestSuite.sol). -/
theorem solkey_TestSuite_storageBoolMappingRead :
    (sol!{ < flags[2] = true;
             bool r = flags[2];
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolArrayRead` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageBoolArrayRead :
    (sol!{ < (boolFlags@@BoolArray).push();
             boolFlags@@BoolArray[0] = true;
             bool r = boolFlags@@BoolArray[0];
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageBoolFieldStoreRoot` (TestSuite.sol). -/
theorem solkey_TestSuite_storageBoolFieldStoreRoot :
    (sol!{ < toggle@@Toggle.on = true;
             flag@@bool = toggle@@Toggle.on;
             bool r = flag@@bool;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryDeclDefault` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryDeclDefault :
    (sol!{ < Person memory mv;
             uint r = mv@Person.age;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageComplexReceiverEmptyPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageComplexReceiverEmptyPush :
    (sol!{ < (bucket@@TokenBucket.tokens).push();
             TokenArray storage bt = bucket@@TokenBucket.tokens;
             assert((bt@TokenArray.length == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionBothStorage` (TestSuite.sol). -/
theorem solkey_TestSuite_additionBothStorage :
    (sol!{ < alice.age = 10;
             bob.age = 5;
             uint r = alice.age + bob.age;
             assert((r == 15)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_additionSimple :
    (sol!{ < uint r = 1 + 2;
             assert((r == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionStorageRead` (TestSuite.sol). -/
theorem solkey_TestSuite_additionStorageRead :
    (sol!{ < alice.age = 10;
             uint r = alice.age + 1;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.divisionSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_divisionSimple :
    (sol!{ < uint r = 8 / 2;
             assert((r == 4)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.greaterEqualSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_greaterEqualSimple :
    (sol!{ < bool r = (5 >= 6);
             assert(!r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.greaterThanSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_greaterThanSimple :
    (sol!{ < bool r = (5 > 3);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.lessEqualSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_lessEqualSimple :
    (sol!{ < bool r = (5 <= 5);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.lessThanSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_lessThanSimple :
    (sol!{ < bool r = (3 < 5);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.logicalAndSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_logicalAndSimple :
    (sol!{ < bool r = true && false;
             assert(!r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.logicalAndShortCircuitRhs` (TestSuite.sol). -/
theorem solkey_TestSuite_logicalAndShortCircuitRhs :
    (sol!{ < uint x = 5;
             bool r = (x == 5) && (x + 1 == 6);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.logicalNotSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_logicalNotSimple :
    (sol!{ < bool r = !false;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.logicalOrSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_logicalOrSimple :
    (sol!{ < bool r = true || false;
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.logicalOrShortCircuitRhs` (TestSuite.sol). -/
theorem solkey_TestSuite_logicalOrShortCircuitRhs :
    (sol!{ < uint x = 5;
             bool r = (x == 4) || (x + 1 == 6);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ternaryCaptureCond` (TestSuite.sol). -/
theorem solkey_TestSuite_ternaryCaptureCond :
    (sol!{ < uint x = 5;
             uint r = (x == 5) ? x + 1 : 0;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ternaryToIf` (TestSuite.sol). -/
theorem solkey_TestSuite_ternaryToIf :
    (sol!{ < bool b = true;
             uint r = b ? 1 : 2;
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifUnfold` (TestSuite.sol). -/
theorem solkey_TestSuite_ifUnfold :
    (sol!{ < uint x = 5;
             uint r = 0;
             if ((x == 4)) { r = 1 };
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifElseUnfold` (TestSuite.sol). -/
theorem solkey_TestSuite_ifElseUnfold :
    (sol!{ < uint x = 5;
             uint r = 0;
             if ((x == 5)) { r = 1 } else { r = 2 };
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifSplit` (TestSuite.sol). -/
theorem solkey_TestSuite_ifSplit :
    (sol!{ < bool b = true;
             uint r = 0;
             if (b) { r = 1 };
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifElseSplit` (TestSuite.sol). -/
theorem solkey_TestSuite_ifElseSplit :
    (sol!{ < bool b = false;
             uint r = 0;
             if (b) { r = 1 } else { r = 2 };
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifTrue` (TestSuite.sol). -/
theorem solkey_TestSuite_ifTrue :
    (sol!{ < uint r = 0;
             if (true) { r = 1 };
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifFalse` (TestSuite.sol). -/
theorem solkey_TestSuite_ifFalse :
    (sol!{ < uint r = 0;
             if (false) { r = 1 };
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifElseTrue` (TestSuite.sol). -/
theorem solkey_TestSuite_ifElseTrue :
    (sol!{ < uint r = 0;
             if (true) { r = 1 } else { r = 2 };
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifElseFalse` (TestSuite.sol). -/
theorem solkey_TestSuite_ifElseFalse :
    (sol!{ < uint r = 0;
             if (false) { r = 1 } else { r = 2 };
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.ifElseNegated` (TestSuite.sol). -/
theorem solkey_TestSuite_ifElseNegated :
    (sol!{ < bool b = false;
             uint r = 0;
             if (!b) { r = 1 } else { r = 2 };
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryDeclFresh` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryDeclFresh :
    (sol!{ < Person memory mv > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryDeepField` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryDeepField :
    (sol!{ < Person memory mv;
             mv@Person.account.balance = 10;
             uint r = mv@Person.account.balance;
             assert((r == 10)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldAddAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldAddAssign :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age += 4;
             uint r = mv@Person.age;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldSubAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldSubAssign :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age -= 4;
             uint r = mv@Person.age;
             assert((r == 26)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldMulAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldMulAssign :
    (sol!{ < Person memory mv;
             mv@Person.age = 7;
             mv@Person.age *= 4;
             uint r = mv@Person.age;
             assert((r == 28)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldDivAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldDivAssign :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age /= 5;
             uint r = mv@Person.age;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldModAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldModAssign :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age %= 7;
             uint r = mv@Person.age;
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldAddAssignUnfold` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldAddAssignUnfold :
    (sol!{ < Person memory mv;
             mv@Person.account.balance = 20;
             mv@Person.account.balance += 4;
             uint r = mv@Person.account.balance;
             assert((r == 24)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldAddAssignNse` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldAddAssignNse :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age += 2 * 3;
             uint r = mv@Person.age;
             assert((r == 36)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPreincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPreincrement :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             ++mv@Person.age;
             uint r = mv@Person.age;
             assert((r == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPostincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPostincrement :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             mv@Person.age++;
             uint r = mv@Person.age;
             assert((r == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPredecrement` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPredecrement :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             predec(mv@Person.age);
             uint r = mv@Person.age;
             assert((r == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPostdecrement` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPostdecrement :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             postdec(mv@Person.age);
             uint r = mv@Person.age;
             assert((r == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPreincrementAssignment` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPreincrementAssignment :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             uint r = ++mv@Person.age;
             assert((r == 31));
             assert((mv@Person.age == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPostincrementAssignment` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPostincrementAssignment :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             uint r = mv@Person.age++;
             assert((r == 30));
             assert((mv@Person.age == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPredecrementAssignment` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPredecrementAssignment :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             uint r = predec(mv@Person.age);
             assert((r == 29));
             assert((mv@Person.age == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPostdecrementAssignment` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPostdecrementAssignment :
    (sol!{ < Person memory mv;
             mv@Person.age = 30;
             uint r = postdec(mv@Person.age);
             assert((r == 30));
             assert((mv@Person.age == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldPreincrementUnfold` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldPreincrementUnfold :
    (sol!{ < Person memory mv;
             mv@Person.account.balance = 20;
             ++mv@Person.account.balance;
             uint r = mv@Person.account.balance;
             assert((r == 21)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldAlias` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldAlias :
    (sol!{ < Person memory mv;
             Account memory mv2 = mv@Person.account;
             mv2@Account.balance = 100;
             uint r = mv@Person.account.balance;
             assert((r == 100)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryFieldReferenceAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryFieldReferenceAssign :
    (sol!{ < Person memory mv;
             Person memory mv2;
             Account memory mv3 = mv2@Person.account;
             mv@Person.account = mv3@Account;
             mv@Person.account.balance = 60;
             uint r = mv2@Person.account.balance;
             assert((r == 60)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryRootAlias` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryRootAlias :
    (sol!{ < Person memory mv;
             Person memory mv2;
             mv2@Person.age = 40;
             mv@Person = mv2@Person;
             mv@Person.age = 41;
             uint r = mv2@Person.age;
             assert((r == 41)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryRootDeleteFresh` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryRootDeleteFresh :
    (sol!{ < Person memory mv;
             delete mv@Person > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryToStorage` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryToStorage :
    (sol!{ < Person memory mv;
             mv@Person.age = 44;
             alice = mv@Person;
             uint r = alice.age;
             assert((r == 44)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryToStorageIndexMappingCopyRootExample` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryToStorageIndexMappingCopyRootExample :
    (sol!{ < Person memory mv;
             mv@Person.age = 6;
             folks[1] = mv@Person;
             uint r = folks[1].age;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryToStorageIndexArrayCopyRootExample` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_memoryToStorageIndexArrayCopyRootExample :
    (sol!{ < persons.push();
             Person memory mv;
             mv@Person.age = 6;
             persons[0] = mv@Person;
             uint r = persons[0].age;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.moduloSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_moduloSimple :
    (sol!{ < uint r = 7 % 3;
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.multiplicationSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_multiplicationSimple :
    (sol!{ < uint r = 3 * 4;
             assert((r == 12)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.notEqualSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_notEqualSimple :
    (sol!{ < bool r = (3 != 4);
             assert(r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.powerSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_powerSimple :
    (sol!{ < uint r = 2 ** 3;
             assert((r == 8)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.requireGuardBox` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_requireGuardBox :
    (sol!{ < uint x = 1;
             age = 1;
             uint r = age;
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.requireHoldsDiamond` (TestSuite.sol). -/
theorem solkey_TestSuite_requireHoldsDiamond :
    (sol!{ < uint x = 5;
             require((x > 0));
             total = x;
             uint r = total;
             assert((r == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageAliasRebindAlias` (TestSuite.sol). -/
theorem solkey_TestSuite_storageAliasRebindAlias :
    (sol!{ < Person storage alicePath = alice;
             bob.age = 20;
             alicePath@Person = bob;
             uint r = alicePath@Person.age;
             assert((r == 20)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageDeepFieldPostincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageDeepFieldPostincrement :
    (sol!{ < alice.account.balance = 100;
             alice.account.balance++;
             uint r = alice.account.balance;
             assert((r == 101)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageDeepFieldPreincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageDeepFieldPreincrement :
    (sol!{ < alice.account.balance = 100;
             ++alice.account.balance;
             uint r = alice.account.balance;
             assert((r == 101)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldAddAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldAddAssign :
    (sol!{ < alice.age = 30;
             alice.age += 4;
             uint r = alice.age;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldCopyStruct` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldCopyStruct :
    (sol!{ < bob.account.balance = 11;
             Account storage acc = bob.account;
             alice.account = acc@Account;
             uint r = alice.account.balance;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldCopyValueField` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldCopyValueField :
    (sol!{ < bob.age = 30;
             alice.age = bob.age;
             uint r = alice.age;
             assert((r == 30)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepDivAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepDivAssign :
    (sol!{ < alice.account.balance = 36;
             alice.account.balance /= 4;
             uint r = alice.account.balance;
             assert((r == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepModAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepModAssign :
    (sol!{ < alice.account.balance = 37;
             alice.account.balance %= 4;
             uint r = alice.account.balance;
             assert((r == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepMulAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepMulAssign :
    (sol!{ < alice.account.balance = 8;
             alice.account.balance *= 3;
             uint r = alice.account.balance;
             assert((r == 24)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepSubAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepSubAssign :
    (sol!{ < alice.account.balance = 30;
             alice.account.balance -= 4;
             uint r = alice.account.balance;
             assert((r == 26)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepWriteRead` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepWriteRead :
    (sol!{ < alice.account.balance = 34;
             uint r = alice.account.balance;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDelete` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDelete :
    (sol!{ < alice.age = 30;
             delete alice.age;
             uint r = alice.age;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeleteThenCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeleteThenCopy :
    (sol!{ < bob.account.balance = 10;
             delete bob.account;
             alice.account = bob.account;
             uint r = alice.account.balance;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeleteThenCopyDeep` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeleteThenCopyDeep :
    (sol!{ < bob.account.token.value = 7;
             delete bob.account;
             alice.account = bob.account;
             uint r = alice.account.token.value;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDivAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDivAssign :
    (sol!{ < alice.age = 30;
             alice.age /= 5;
             uint r = alice.age;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldModAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldModAssign :
    (sol!{ < alice.age = 30;
             alice.age %= 7;
             uint r = alice.age;
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldMulAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldMulAssign :
    (sol!{ < alice.age = 7;
             alice.age *= 4;
             uint r = alice.age;
             assert((r == 28)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPostdecrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPostdecrementAssign :
    (sol!{ < alice.age = 30;
             uint r = postdec(alice.age);
             assert((r == 30)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPostdecrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPostdecrement :
    (sol!{ < alice.age = 30;
             postdec(alice.age);
             uint r = alice.age;
             assert((r == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPostincrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPostincrementAssign :
    (sol!{ < alice.age = 30;
             uint r = alice.age++;
             assert((r == 30)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPostincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPostincrement :
    (sol!{ < alice.age = 30;
             alice.age++;
             uint r = alice.age;
             assert((r == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPredecrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPredecrementAssign :
    (sol!{ < alice.age = 30;
             uint r = predec(alice.age);
             assert((r == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPredecrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPredecrement :
    (sol!{ < alice.age = 30;
             predec(alice.age);
             uint r = alice.age;
             assert((r == 29)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPreincrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPreincrementAssign :
    (sol!{ < alice.age = 30;
             uint r = ++alice.age;
             assert((r == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldPreincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldPreincrement :
    (sol!{ < alice.age = 30;
             ++alice.age;
             uint r = alice.age;
             assert((r == 31)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldReadBindLocal` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldReadBindLocal :
    (sol!{ < Account storage acc = alice.account;
             bob.account.balance = 42;
             acc@Account = bob.account;
             uint r = acc@Account.balance;
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldReadStoreRoot` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldReadStoreRoot :
    (sol!{ < alice.age = 17;
             total = alice.age;
             uint r = total;
             assert((r == 17)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldSubAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldSubAssign :
    (sol!{ < alice.age = 30;
             alice.age -= 5;
             uint r = alice.age;
             assert((r == 25)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteCaptureSrc` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldWriteCaptureSrc :
    (sol!{ < bob.account.balance = 11;
             alice.account = bob.account;
             uint r = alice.account.balance;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteRhsCapture` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageFieldWriteRhsCapture :
    (sol!{ < uint x = 1;
             uint y = 2;
             uint z = 3;
             alice.age = x + y*z;
             uint r = alice.age;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexCopyValue` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 5, j = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexCopyValue :
    (sol!{ < values.push();
             values.push();
             uint i = 5;
             uint j = 1;
             values[1] = 8;
             balances[i] = values[j];
             uint r = balances[5];
             assert((r == 8)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexCopysourceAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexCopysourceAfterPush :
    (sol!{ < uint[][] storage m = matrix;
             m@uint[][].push();
             m@uint[][][0] = values;
             assert((matrix.length == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDecomposeAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexDecomposeAfterPush :
    (sol!{ < matrix.push();
             matrix[0].push(100);
             matrix[0][0] = 7;
             uint r = matrix[0][0];
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDeleteMappingBool` (TestSuite.sol). -/
theorem solkey_TestSuite_storageIndexDeleteMappingBool :
    (sol!{ < flags[1] = true;
             delete flags[1];
             bool r = flags[1];
             assert(!r) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDeleteMappingStruct` (TestSuite.sol). -/
theorem solkey_TestSuite_storageIndexDeleteMappingStruct :
    (sol!{ < delete folks[1];
             assert((folks[1].age == 0));
             assert((folks[1].account.balance == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDeleteNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexDeleteNseIndex :
    (sol!{ < uint k = 2;
             balances[3] = 7;
             delete balances[k+1];
             uint r = balances[3];
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDelete` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexDelete :
    (sol!{ < values.push();
             values.push();
             values[1] = 7;
             delete values[1];
             uint r = values[1];
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDivAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexDivAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             values[1] /= 8;
             uint r = values[1];
             assert((r == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexModAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexModAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             values[1] %= 6;
             uint r = values[1];
             assert((r == 4)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexMulAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexMulAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 5;
             values[1] *= 6;
             uint r = values[1];
             assert((r == 30)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexMultipleWrites` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexMultipleWrites :
    (sol!{ < values.push();
             values.push();
             values.push();
             values.push();
             values[3] = 5;
             values[3] = 8;
             uint r = values[3];
             assert((r == 8)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPostdecrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPostdecrementAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             uint r = postdec(values[1]);
             assert((r == 40)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPostdecrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPostdecrement :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             postdec(values[1]);
             uint r = values[1];
             assert((r == 39)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPostincrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPostincrementAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             uint r = values[1]++;
             assert((r == 40)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPostincrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPostincrement :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             values[1]++;
             uint r = values[1];
             assert((r == 41)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPredecrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPredecrementAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             uint r = predec(values[1]);
             assert((r == 39)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPredecrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPredecrement :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             predec(values[1]);
             uint r = values[1];
             assert((r == 39)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPreincrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPreincrementAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             uint r = ++values[1];
             assert((r == 41)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexPreincrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexPreincrement :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             ++values[1];
             uint r = values[1];
             assert((r == 41)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexReadMappingStoreRoot` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexReadMappingStoreRoot :
    (sol!{ < uint k = 1;
             balances[1] = 42;
             total = balances[k];
             uint r = total;
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexReadNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexReadNseIndex :
    (sol!{ < values.push();
             values.push();
             values.push();
             uint i = 1;
             values[2] = 9;
             uint r = values[i+1];
             assert((r == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexSubAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexSubAssign :
    (sol!{ < values.push();
             values.push();
             values[1] = 40;
             values[1] -= 8;
             uint r = values[1];
             assert((r == 32)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteNseChain` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 2, x = 3, y = 4.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexWriteNseChain :
    (sol!{ < uint i = 2;
             uint x = 3;
             uint y = 4;
             balances[i+1] = x*y + 3;
             uint r = balances[3];
             assert((r == 15)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageLocalDeclSkip` (TestSuite.sol). -/
theorem solkey_TestSuite_storageLocalDeclSkip :
    (sol!{ < Person storage p = undefined;
             age = 7;
             uint r = age;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageMatrixNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 1, j = 2, x = 5, y = 6.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageMatrixNseIndex :
    (sol!{ < matrix.push();
             matrix.push();
             matrix.push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             uint i = 1;
             uint j = 2;
             uint x = 5;
             uint y = 6;
             matrix[i+1][j+1] = x + y;
             assert((matrix[2][3] == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageMatrixWriteRead` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageMatrixWriteRead :
    (sol!{ < matrix.push();
             matrix.push();
             matrix.push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2][3] = 99;
             uint r = matrix[2][3];
             assert((r == 99)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePopAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePopAfterPush :
    (sol!{ < values.push();
             values.pop();
             assert((values.length == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePopNonempty` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePopNonempty :
    (sol!{ < values.push();
             values.push();
             values.pop();
             assert((values.length == 1));
             values.push();
             assert((values[1] == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePopUnknownLength` (TestSuite.sol). -/
theorem solkey_TestSuite_storagePopUnknownLength :
    (sol!{ < values.push();
             values.pop() > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushEmpty` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushEmpty :
    (sol!{ < values.push();
             values.push();
             values.push();
             assert((values.length == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushLengthPositive` (TestSuite.sol). -/
theorem solkey_TestSuite_storagePushLengthPositive :
    (sol!{ < values.push();
             assert((values.length > 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushLocalBind` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushLocalBind :
    (sol!{ < persons.push();
             persons.push();
             Person storage p = undefined;
             p@Person = persons.push();
             assert((persons.length == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushNonsimpleArg` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 40, y = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushNonsimpleArg :
    (sol!{ < values.push();
             values.push();
             uint x = 40;
             uint y = 2;
             values.push(x + y);
             assert((values[2] == 42));
             assert((values.length == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushReadBack` (TestSuite.sol). -/
theorem solkey_TestSuite_storagePushReadBack :
    (sol!{ < values.push(42);
             uint r = values[values.length - 1];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storagePushReturnAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storagePushReturnAssign :
    (sol!{ < values.push();
             values.push();
             values.push() = 42;
             assert((values[2] == 42));
             assert((values.length == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootAddAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootAddAssign :
    (sol!{ < age = 10;
             age += 5;
             uint r = age;
             assert((r == 15)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootCopySource` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootCopySource :
    (sol!{ < age = 34;
             balance = age;
             uint r = balance;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootCopyStruct` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootCopyStruct :
    (sol!{ < bob.age = 7;
             alice = bob;
             uint r = alice.age;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootDeleteStruct` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootDeleteStruct :
    (sol!{ < alice.age = 30;
             delete alice;
             uint r = alice.age;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootDeleteThenCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootDeleteThenCopy :
    (sol!{ < bob.age = 30;
             delete bob;
             alice = bob;
             uint r = alice.age;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootDelete` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootDelete :
    (sol!{ < age = 10;
             delete age;
             uint r = age;
             assert((r == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootDisjoint` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootDisjoint :
    (sol!{ < age = 7;
             balance = 9;
             uint r = age;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootDivAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootDivAssign :
    (sol!{ < age = 20;
             age /= 4;
             uint r = age;
             assert((r == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootModAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootModAssign :
    (sol!{ < age = 17;
             age %= 5;
             uint r = age;
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootMulAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootMulAssign :
    (sol!{ < age = 6;
             age *= 3;
             uint r = age;
             assert((r == 18)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootMultipleWrites` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootMultipleWrites :
    (sol!{ < age = 1;
             age = 2;
             uint r = age;
             assert((r == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPostdecrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPostdecrementAssign :
    (sol!{ < age = 10;
             uint r = postdec(age);
             assert((r == 10)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPostincrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPostincrementAssign :
    (sol!{ < age = 10;
             uint r = age++;
             assert((r == 10)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPostincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPostincrement :
    (sol!{ < age = 10;
             age++;
             uint r = age;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPredecrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPredecrement :
    (sol!{ < age = 10;
             predec(age);
             uint r = age;
             assert((r == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPreincrementAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPreincrementAssign :
    (sol!{ < age = 10;
             uint r = ++age;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootPreincrement` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootPreincrement :
    (sol!{ < age = 10;
             ++age;
             uint r = age;
             assert((r == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootSubAssign` (TestSuite.sol). -/
theorem solkey_TestSuite_storageRootSubAssign :
    (sol!{ < age = 10;
             age -= 4;
             uint r = age;
             assert((r == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageRootWriteRhsCapture` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageRootWriteRhsCapture :
    (sol!{ < uint x = 1;
             uint y = 2;
             uint z = 3;
             total = x + y*z;
             uint r = total;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageToMemory` (TestSuite.sol). -/
theorem solkey_TestSuite_storageToMemory :
    (sol!{ < alice.age = 27;
             Person memory mv = alice;
             alice.age = 30;
             uint r = mv@Person.age;
             assert((r == 27)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.subtractionSimple` (TestSuite.sol). -/
theorem solkey_TestSuite_subtractionSimple :
    (sol!{ < uint r = 7 - 2;
             assert((r == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.subtractionStorageRead` (TestSuite.sol). -/
theorem solkey_TestSuite_subtractionStorageRead :
    (sol!{ < alice.age = 10;
             uint r = alice.age - 3;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.unaryMinusSimple` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_unaryMinusSimple :
    (sol!{ < int x = 5;
             int r = -x;
             int expected = -5;
             assert((r == expected)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testDeepPopDoesNotResetMappingMember` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testDeepPopDoesNotResetMappingMember :
    (sol!{ < (ledgerUses@@LedgerUseArray).push();
             ledgerUses@@LedgerUseArray[0].ledger.balances[1] = 10;
             (ledgerUses@@LedgerUseArray).pop();
             (ledgerUses@@LedgerUseArray).push();
             assert((ledgerUses@@LedgerUseArray[0].ledger.balances[1] == 10)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryAliasing` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryAliasing :
    (sol!{ < Person memory mv;
             Account memory mv2 = mv@Person.account;
             mv2@Account.balance = 100;
             assert((mv@Person.account.balance == 100)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryDeleteAlias` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryDeleteAlias :
    (sol!{ < Person memory mv;
             Account memory mv2 = mv@Person.account;
             mv2@Account.balance = 100;
             delete mv2@Account;
             uint b = mv2@Account.balance;
             assert((b == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryDeleteIdentityFieldFreshensSlot` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryDeleteIdentityFieldFreshensSlot :
    (sol!{ < Person memory mv;
             Account memory mv2 = mv@Person.account;
             mv2@Account.balance = 100;
             delete mv@Person.account;
             assert((mv@Person.account.balance == 0));
             assert((mv2@Account.balance == 100)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryDeletePrimitiveField` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryDeletePrimitiveField :
    (sol!{ < Person memory mv;
             mv@Person.age = 20;
             delete mv@Person.age;
             assert((mv@Person.age == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryFieldShallowCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryFieldShallowCopy :
    (sol!{ < Person memory mv;
             Person memory mv2;
             mv2@Person.account.balance = 50;
             mv@Person.account = mv2@Person.account;
             mv@Person.account.balance = 60;
             assert((mv2@Person.account.balance == 60));
             assert((mv@Person.account.balance == 60)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryRootAlias` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryRootAlias :
    (sol!{ < Person memory mv;
             Person memory mv2;
             mv2@Person.age = 40;
             mv@Person = mv2@Person;
             mv@Person.age = 41;
             assert((mv2@Person.age == 41));
             assert((mv@Person.age == 41)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryRootDeleteRebindsOnlyLocal` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryRootDeleteRebindsOnlyLocal :
    (sol!{ < Person memory mv;
             Person memory mv2 = mv@Person;
             mv@Person.age = 33;
             delete mv@Person;
             assert((mv@Person.age == 0));
             assert((mv2@Person.age == 33)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryToStorageCopyComplexSource` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryToStorageCopyComplexSource :
    (sol!{ < Person memory mv;
             mv@Person.account.balance = 50;
             alice.account = mv@Person.account;
             mv@Person.account.balance = 51;
             assert((alice.account.balance == 50)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryToStorageCopyComplexTarget` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryToStorageCopyComplexTarget :
    (sol!{ < Token memory mv;
             mv@Token.value = 99;
             alice.account.token = mv@Token;
             mv@Token.value = 100;
             assert((alice.account.token.value == 99)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryToStorageCopyField` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryToStorageCopyField :
    (sol!{ < Account memory mv;
             mv@Account.balance = 50;
             alice.account = mv@Account;
             mv@Account.balance = 51;
             assert((alice.account.balance == 50)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryToStorageCopyRoot` (TestSuite.sol). -/
theorem solkey_TestSuite_testMemoryToStorageCopyRoot :
    (sol!{ < Person memory mv;
             mv@Person.age = 42;
             alice = mv@Person;
             mv@Person.age = 43;
             assert((alice.age == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testMemoryToStorageIndexCopyImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testMemoryToStorageIndexCopyImpureIndex :
    (sol!{ < persons.push();
             persons.push();
             Person memory mv;
             mv@Person.age = 7;
             uint i = 0;
             persons[i++] = mv@Person;
             assert((i == 1));
             assert((persons[0].age == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testNestedIndexWriteImpureIndexPrimitiveRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testNestedIndexWriteImpureIndexPrimitiveRhs :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[1].push(100);
             uint i = 1;
             matrix[i++][0] = i;
             assert((i == 2));
             assert((matrix[1][0] == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testNestedIndexReadImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testNestedIndexReadImpureIndex :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[1].push(100);
             uint i = 1;
             uint v = matrix[i++][0];
             assert((i == 2));
             assert((v == 100)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testNestedIndexWriteImpureReceiverAndIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testNestedIndexWriteImpureReceiverAndIndex :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[0].push(0);
             matrix[0].push(0);
             matrix[1].push(0);
             matrix[1].push(0);
             uint i = 0;
             matrix[i++][i++] = 77;
             assert((i == 2));
             assert((matrix[0][1] == 77));
             assert((matrix[1][0] == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testNestedIndexReadImpureReceiverAndIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testNestedIndexReadImpureReceiverAndIndex :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[0].push(0);
             matrix[0].push(11);
             matrix[1].push(22);
             uint i = 0;
             uint v = matrix[i++][i++];
             assert((i == 2));
             assert((v == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageDeleteImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageDeleteImpureReceiver :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[0].push(9);
             uint i = 0;
             delete matrix[i++][0];
             assert((i == 1));
             assert((matrix[0][0] == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStoragePushImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStoragePushImpureReceiver :
    (sol!{ < matrix.push();
             matrix.push();
             uint i = 0;
             matrix[i++].push(i);
             assert((i == 1));
             assert((matrix[0][0] == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCompoundAssignImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testCompoundAssignImpureReceiver :
    (sol!{ < persons.push();
             persons.push();
             persons[0].age = 5;
             uint i = 0;
             persons[i++].age += i;
             assert((i == 1));
             assert((persons[0].age == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testIndexWriteReceiverReadsMutatedVar` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testIndexWriteReceiverReadsMutatedVar :
    (sol!{ < matrix.push();
             matrix.push();
             matrix[0].push(0);
             matrix[1].push(0);
             uint k = 0;
             matrix[k][k++] = 77;
             assert((k == 1));
             assert((matrix[0][0] == 77));
             assert((matrix[1][0] == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testNestedStorageWrites` (TestSuite.sol). -/
theorem solkey_TestSuite_testNestedStorageWrites :
    (sol!{ < alice.account.balance = 10;
             alice.account.token.value = 5;
             uint b = alice.account.balance;
             uint v = alice.account.token.value;
             assert((b == 10));
             assert((v == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageAliases` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageAliases :
    (sol!{ < Person storage p = alice;
             Account storage acc = p@Person.account;
             acc@Account.balance = 100;
             p@Person.account.token.value = 3;
             assert((alice.account.balance == 100));
             assert((alice.account.token.value == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageArrayReadWrite` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageArrayReadWrite :
    (sol!{ < (tokens@@TokenArray).push();
             tokens@@TokenArray[0].value = 100;
             uint v = tokens@@TokenArray[0].value;
             assert((v == 100)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageComplexReceiverPushFieldLvalue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageComplexReceiverPushFieldLvalue :
    (sol!{ < (bucket@@TokenBucket.tokens).push().value = 5;
             TokenArray storage bt = bucket@@TokenBucket.tokens;
             assert((bt@TokenArray.length == 1));
             assert((bt@TokenArray[0].value == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageComplexReceiverPushLvalueCopy` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageComplexReceiverPushLvalueCopy :
    (sol!{ < alice.account.token.value = 7;
             Token storage tokRef = alice.account.token;
             (bucket@@TokenBucket.tokens).push() = tokRef@Token;
             TokenArray storage bt = bucket@@TokenBucket.tokens;
             assert((bt@TokenArray.length == 1));
             assert((bt@TokenArray[0].value == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageDeletePaperCase` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageDeletePaperCase :
    (sol!{ < alice.account.balance = 100;
             alice.account.token.value = 7;
             delete alice.account;
             uint b = alice.account.balance;
             uint v = alice.account.token.value;
             assert((b == 0));
             assert((v == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageIndexWriteImpureIndexPrimitiveRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageIndexWriteImpureIndexPrimitiveRhs :
    (sol!{ < uint i = 0;
             (aux@@UintArray).push(100);
             (aux@@UintArray).push(100);
             aux@@UintArray[i++] = i;
             assert((i == 1));
             assert((aux@@UintArray[0] == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageIndexWriteImpureIndexRefRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageIndexWriteImpureIndexRefRhs :
    (sol!{ < persons.push();
             persons.push();
             bob.age = 0;
             persons[bob.age++] = bob;
             assert((bob.age == 1));
             assert((persons[0].age == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageEvaluationOrder` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageEvaluationOrder :
    (sol!{ < uint i = 0;
             (aux@@UintArray).push(100);
             (aux@@UintArray).push(100);
             (aux@@UintArray).push(100);
             aux@@UintArray[++i] = ++i;
             assert((aux@@UintArray[2] == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageFieldDeepCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageFieldDeepCopy :
    (sol!{ < bob.account.balance = 10;
             bob.account.token.value = 7;
             Account storage bobAcc = bob.account;
             alice.account = bobAcc@Account;
             bob.account.balance = 20;
             bob.account.token.value = 9;
             assert((alice.account.balance == 10));
             assert((alice.account.token.value == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageMapReadWriteAndDelete` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageMapReadWriteAndDelete :
    (sol!{ < valuesMap@@UintMap[1] = 10;
             valuesMap@@UintMap[2] = 20;
             uint v = valuesMap@@UintMap[1];
             uint kept = valuesMap@@UintMap[2];
             delete valuesMap@@UintMap[1];
             assert((v == 10));
             assert((kept == 20));
             assert((valuesMap@@UintMap[1] == 0));
             assert((valuesMap@@UintMap[2] == 20)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageMapStructCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageMapStructCopy :
    (sol!{ < accountMap@@AccountMap[1].balance = 10;
             accountMap@@AccountMap[1].token.value = 7;
             accountMap@@AccountMap[2] = accountMap@@AccountMap[1];
             accountMap@@AccountMap[1].balance = 20;
             accountMap@@AccountMap[1].token.value = 9;
             assert((accountMap@@AccountMap[2].balance == 10));
             assert((accountMap@@AccountMap[2].token.value == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageNestedPushReturnAlias` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStorageNestedPushReturnAlias :
    (sol!{ < Account storage acc = persons.push().account;
             acc@Account.balance = 50;
             assert((persons.length == 1));
             assert((acc@Account.balance == 50)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStoragePushFieldLvalue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStoragePushFieldLvalue :
    (sol!{ < (tokens@@TokenArray).push().value = 11;
             assert((tokens@@TokenArray.length == 1));
             assert((tokens@@TokenArray[0].value == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStoragePushLvalueCopiesStorageSource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStoragePushLvalueCopiesStorageSource :
    (sol!{ < alice.account.token.value = 9;
             Token storage storageRef = alice.account.token;
             (tokens@@TokenArray).push() = storageRef@Token;
             assert((tokens@@TokenArray.length == 1));
             assert((tokens@@TokenArray[0].value == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStoragePushLvaluePrimitive` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStoragePushLvaluePrimitive :
    (sol!{ < values.push() = 77;
             assert((values.length == 1));
             assert((values[0] == 77)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStoragePushReturnAlias` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testStoragePushReturnAlias :
    (sol!{ < Token storage t = (tokens@@TokenArray).push();
             t@Token.value = 99;
             assert((tokens@@TokenArray.length == 1));
             assert((tokens@@TokenArray[0].value == 99)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageRootDeepCopy` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageRootDeepCopy :
    (sol!{ < bob.age = 21;
             bob.account.balance = 11;
             alice = bob;
             bob.age = 30;
             bob.account.balance = 12;
             assert((alice.age == 21));
             assert((alice.account.balance == 11)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageStructDeleteSkipsMappingMember` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageStructDeleteSkipsMappingMember :
    (sol!{ < ledger@@Ledger.nonce = 5;
             ledger@@Ledger.balances[1] = 10;
             ledger@@Ledger.balances[2] = 20;
             delete ledger@@Ledger;
             assert((ledger@@Ledger.nonce == 0));
             assert((ledger@@Ledger.balances[1] == 10));
             assert((ledger@@Ledger.balances[2] == 20));
             delete ledger@@Ledger.balances[1];
             assert((ledger@@Ledger.balances[1] == 0));
             assert((ledger@@Ledger.balances[2] == 20)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageToMemoryCopyComplexPath` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageToMemoryCopyComplexPath :
    (sol!{ < alice.account.token.value = 17;
             Token memory mv = alice.account.token;
             alice.account.token.value = 18;
             assert((mv@Token.value == 17)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageToMemoryCopyField` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageToMemoryCopyField :
    (sol!{ < alice.account.balance = 10;
             Account memory mv = alice.account;
             alice.account.balance = 20;
             uint v = mv@Account.balance;
             assert((v == 10)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageToMemoryCopyRoot` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageToMemoryCopyRoot :
    (sol!{ < alice.age = 25;
             Person memory mv = alice;
             alice.age = 30;
             uint v = mv@Person.age;
             assert((v == 25)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testStorageWriteAndRead` (TestSuite.sol). -/
theorem solkey_TestSuite_testStorageWriteAndRead :
    (sol!{ < uint x = 20;
             uint y = 1;
             alice.age = x + y;
             uint v = alice.age;
             assert((v == 21)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDecomposition` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDecomposition :
    (sol!{ < alice.account.balance = 34;
             assert((alice.account.balance == 34));
             uint r = alice.account.balance;
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDeepValue` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDeepValue :
    (sol!{ < alice.account.token.value = 7;
             assert((alice.account.token.value == 7));
             uint r = alice.account.token.value;
             assert((r == 7)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexDecomposition` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexDecomposition :
    (sol!{ < matrix.push();
             matrix.push();
             matrix.push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2][3] = 34;
             assert((matrix[2][3] == 34));
             uint r = matrix[2][3];
             assert((r == 34)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexRootArray` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexRootArray :
    (sol!{ < values.push();
             values.push();
             values[1] = 42;
             assert((values[1] == 42));
             uint r = values[1];
             assert((r == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDisjointFields` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDisjointFields :
    (sol!{ < alice.account.balance = 1;
             alice.account.token.value = 2;
             assert((alice.account.balance == 1));
             assert((alice.account.token.value == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldDisjointRoots` (TestSuite.sol). -/
theorem solkey_TestSuite_storageFieldDisjointRoots :
    (sol!{ < alice.age = 1;
             bob.age = 2;
             assert((alice.age == 1));
             assert((bob.age == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryDelete` (TestSuite.sol). -/
theorem solkey_TestSuite_memoryDelete :
    (sol!{ < Person memory mv;
             Account memory mv2 = mv@Person.account;
             mv@Person.age = 20;
             mv2@Account.balance = 100;
             delete mv@Person.age;
             delete mv@Person.account;
             uint result = mv@Person.age;
             uint aliasBalance = mv2@Account.balance;
             uint newBalance = mv@Person.account.balance;
             assert((result == 0));
             assert((aliasBalance == 100));
             assert((newBalance == 0)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageAliasRebindOriginal` (TestSuite.sol). -/
theorem solkey_TestSuite_storageAliasRebindOriginal :
    (sol!{ < uint before = alice.age;
             Person storage alicePath = alice;
             bob.age = 20;
             alicePath@Person = bob;
             assert((alice.age == before)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testSimpleAssert` (TestSuite.sol). -/
theorem solkey_TestSuite_testSimpleAssert :
    (sol!{ < age = 42;
             uint v = age;
             assert((v == 42)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.signedUnaryMinusInRange` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_signedUnaryMinusInRange :
    (sol!{ < int8 x = 5;
             int8 r;
             int8 expected;
             r = -x;
             expected = -5;
             assert((r == expected)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteRefSourceImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexWriteRefSourceImpureIndex :
    (sol!{ < persons.push();
             Person memory mv;
             persons[mv@Person.age++] = mv@Person;
             assert((persons[0].age == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteRefSourceImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageFieldWriteRefSourceImpureReceiver :
    (sol!{ < persons.push();
             Account memory mv;
             persons[mv@Account.balance++].account = mv@Account;
             assert((persons[0].account.balance == 1)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteStorageRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageFieldWriteStorageRefImpureReceiver :
    (sol!{ < persons.push();
             persons.push();
             alice.account.balance = 9;
             Account storage src = alice.account;
             uint i = 0;
             persons[i++].account = src@Account;
             assert((i == 1));
             assert((persons[0].account.balance == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageFieldWriteRootRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageFieldWriteRootRefImpureReceiver :
    (sol!{ < persons.push();
             persons.push();
             tok@@Token.value = 4;
             uint i = 0;
             persons[i++].account.token = tok@@Token;
             assert((i == 1));
             assert((persons[0].account.token.value == 4)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteRootRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexWriteRootRefImpureReceiver :
    (sol!{ < (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             tok@@Token.value = 3;
             uint i = 1;
             buckets@@TokenBucketArray[i++].tokens[0] = tok@@Token;
             assert((i == 2));
             assert((buckets@@TokenBucketArray[1].tokens[0].value == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.storageIndexWriteStorageRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_storageIndexWriteStorageRefImpureReceiver :
    (sol!{ < (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             tok@@Token.value = 8;
             Token storage src = tok@@Token;
             uint i = 1;
             buckets@@TokenBucketArray[i++].tokens[0] = src@Token;
             assert((i == 2));
             assert((buckets@@TokenBucketArray[1].tokens[0].value == 8)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.memoryToStorageIndexImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_memoryToStorageIndexImpureReceiver :
    (sol!{ < (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             Token memory mv;
             mv@Token.value = 5;
             uint i = 1;
             buckets@@TokenBucketArray[i++].tokens[0] = mv@Token;
             assert((i == 2));
             assert((buckets@@TokenBucketArray[1].tokens[0].value == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionLeftImpureRightReadFirst` (TestSuite.sol). -/
theorem solkey_TestSuite_additionLeftImpureRightReadFirst :
    (sol!{ < uint i = 1;
             uint x = i++ + i;
             assert((x == 2));
             assert((i == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionRightImpure` (TestSuite.sol). -/
theorem solkey_TestSuite_additionRightImpure :
    (sol!{ < uint i = 1;
             uint x = i + i++;
             assert((x == 3));
             assert((i == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.additionBothOperandsImpure` (TestSuite.sol). -/
theorem solkey_TestSuite_additionBothOperandsImpure :
    (sol!{ < uint i = 1;
             uint x = i++ + i++;
             assert((x == 3));
             assert((i == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.subtractionLeftImpureRightReadFirst` (TestSuite.sol). -/
theorem solkey_TestSuite_subtractionLeftImpureRightReadFirst :
    (sol!{ < uint i = 5;
             uint x = i++ - i;
             assert((x == 0));
             assert((i == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.lessThanLeftImpureRightReadFirst` (TestSuite.sol). -/
theorem solkey_TestSuite_lessThanLeftImpureRightReadFirst :
    (sol!{ < uint i = 1;
             bool b = (i++ < i);
             assert(!b);
             assert((i == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyRootKeepsValueMembers` (TestSuite.sol). -/
theorem solkey_TestSuite_testCopyRootKeepsValueMembers :
    (sol!{ < bob.age = 7;
             bob.account.balance = 3;
             alice = bob;
             bob.age = 8;
             assert((alice.age == 7));
             assert((alice.account.balance == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyFieldNested` (TestSuite.sol). -/
theorem solkey_TestSuite_testCopyFieldNested :
    (sol!{ < Account storage acc = bob.account;
             acc@Account.token.value = 5;
             alice.account = acc@Account;
             acc@Account.token.value = 6;
             assert((alice.account.token.value == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyOfCopy` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testCopyOfCopy :
    (sol!{ < bob.age = 4;
             alice = bob;
             persons.push();
             persons[0] = alice;
             assert((persons[0].age == 4)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyIntoMappingEntry` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testCopyIntoMappingEntry :
    (sol!{ < uint k = 3;
             alice.age = 6;
             folks[k] = alice;
             alice.age = 7;
             assert((folks[k].age == 6)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyArrayMemberElements` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testCopyArrayMemberElements :
    (sol!{ < (basketA@@Basket.items).push(9);
             basketB@@Basket = basketA@@Basket;
             basketA@@Basket.items[0] = 1;
             assert((basketB@@Basket.items.length == 1));
             assert((basketB@@Basket.items[0] == 9)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyPrimitiveRoot` (TestSuite.sol). -/
theorem solkey_TestSuite_testCopyPrimitiveRoot :
    (sol!{ < age = 3;
             balance = age;
             age = 4;
             assert((balance == 3)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyStoreRootFromField` (TestSuite.sol). -/
theorem solkey_TestSuite_testCopyStoreRootFromField :
    (sol!{ < alice.account.token.value = 2;
             tok@@Token = alice.account.token;
             alice.account.token.value = 1;
             assert((tok@@Token.value == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testCopyStoreRootFromIndex` (TestSuite.sol). -/
theorem solkey_TestSuite_testCopyStoreRootFromIndex :
    (sol!{ < folks[1].age = 2;
             alice = folks[1];
             folks[1].age = 3;
             assert((alice.age == 2)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.testPushCopyThenDeleteTarget` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_testPushCopyThenDeleteTarget :
    (sol!{ < tok@@Token.value = 4;
             Token storage src = tok@@Token;
             (tokens@@TokenArray).push() = src@Token;
             delete tokens@@TokenArray[0];
             assert((tokens@@TokenArray[0].value == 0));
             assert((tok@@Token.value == 4)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.indexWriteBothImpureStorageRef` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_indexWriteBothImpureStorageRef :
    (sol!{ < (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             tok@@Token.value = 8;
             Token storage src = tok@@Token;
             uint i = 1;
             uint j = 0;
             buckets@@TokenBucketArray[i++].tokens[j++] = src@Token;
             assert((i == 2));
             assert((j == 1));
             assert((buckets@@TokenBucketArray[1].tokens[0].value == 8)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

/-- solkey `TestSuite.indexWriteBothImpureMemToStorage` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_TestSuite_indexWriteBothImpureMemToStorage :
    (sol!{ < (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             (buckets@@TokenBucketArray[1].tokens).push();
             Token memory mv;
             mv@Token.value = 5;
             uint i = 1;
             uint j = 0;
             buckets@@TokenBucketArray[i++].tokens[j++] = mv@Token;
             assert((i == 2));
             assert((j == 1));
             assert((buckets@@TokenBucketArray[1].tokens[0].value == 5)) > (true) }).Holds
      State.testSuiteStore := by
  sol_wp

end TestSuite
end Solkey
end Solidity
