import Solidity.Tactics.Derivation
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part11

Obligations 241-245 of 245.

The same obligations as `Solidity/Corpus/Wp/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.testCopyStoreRootFromField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testCopyStoreRootFromField from State.testSuiteStore
  { alice.account.token.value = 2;
    tok@@Token = alice.account.token;
    alice.account.token.value = 1;
    assert((tok@@Token.value == 2)) }

/-- solkey `TestSuite.testCopyStoreRootFromIndex` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testCopyStoreRootFromIndex from State.testSuiteStore
  { folks[1].age = 2;
    alice = folks[1];
    folks[1].age = 3;
    assert((alice.age == 2)) }

/-- solkey `TestSuite.testPushCopyThenDeleteTarget` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testPushCopyThenDeleteTarget from State.testSuiteStore
  { tok@@Token.value = 4;
    Token storage src = tok@@Token;
    (tokens@@TokenArray).push() = src@Token;
    delete tokens@@TokenArray[0];
    assert((tokens@@TokenArray[0].value == 0));
    assert((tok@@Token.value == 4)) }

/-- solkey `TestSuite.indexWriteBothImpureStorageRef` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_indexWriteBothImpureStorageRef from State.testSuiteStore
  { (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    tok@@Token.value = 8;
    Token storage src = tok@@Token;
    uint i = 1;
    uint j = 0;
    buckets@@TokenBucketArray[i++].tokens[j++] = src@Token;
    assert((i == 2));
    assert((j == 1));
    assert((buckets@@TokenBucketArray[1].tokens[0].value == 8)) }

/-- solkey `TestSuite.indexWriteBothImpureMemToStorage` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_indexWriteBothImpureMemToStorage from State.testSuiteStore
  { (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    Token memory mv;
    mv@Token.value = 5;
    uint i = 1;
    uint j = 0;
    buckets@@TokenBucketArray[i++].tokens[j++] = mv@Token;
    assert((i == 2));
    assert((j == 1));
    assert((buckets@@TokenBucketArray[1].tokens[0].value == 5)) }

end TestSuite
end Calculus
end Solidity
