import Solidity.Tactics.Derivation
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part06

Obligations 121-144 of 245.

The same obligations as `Solidity/Corpus/Wp/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.storageIndexMultipleWrites` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexMultipleWrites from State.testSuiteStore
  { values.push();
    values.push();
    values.push();
    values.push();
    values[3] = 5;
    values[3] = 8;
    uint r = values[3];
    assert((r == 8)) }

/-- solkey `TestSuite.storageIndexPostdecrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPostdecrementAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    uint r = postdec(values[1]);
    assert((r == 40)) }

/-- solkey `TestSuite.storageIndexPostdecrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPostdecrement from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    postdec(values[1]);
    uint r = values[1];
    assert((r == 39)) }

/-- solkey `TestSuite.storageIndexPostincrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPostincrementAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    uint r = values[1]++;
    assert((r == 40)) }

/-- solkey `TestSuite.storageIndexPostincrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPostincrement from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    values[1]++;
    uint r = values[1];
    assert((r == 41)) }

/-- solkey `TestSuite.storageIndexPredecrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPredecrementAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    uint r = predec(values[1]);
    assert((r == 39)) }

/-- solkey `TestSuite.storageIndexPredecrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPredecrement from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    predec(values[1]);
    uint r = values[1];
    assert((r == 39)) }

/-- solkey `TestSuite.storageIndexPreincrementAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPreincrementAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    uint r = ++values[1];
    assert((r == 41)) }

/-- solkey `TestSuite.storageIndexPreincrement` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexPreincrement from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    ++values[1];
    uint r = values[1];
    assert((r == 41)) }

/-- solkey `TestSuite.storageIndexReadMappingStoreRoot` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexReadMappingStoreRoot from State.testSuiteStore
  { uint k = 1;
    balances[1] = 42;
    total = balances[k];
    uint r = total;
    assert((r == 42)) }

/-- solkey `TestSuite.storageIndexReadNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexReadNseIndex from State.testSuiteStore
  { values.push();
    values.push();
    values.push();
    uint i = 1;
    values[2] = 9;
    uint r = values[i+1];
    assert((r == 9)) }

/-- solkey `TestSuite.storageIndexSubAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexSubAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    values[1] -= 8;
    uint r = values[1];
    assert((r == 32)) }

/-- solkey `TestSuite.storageIndexWriteNseChain` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 2, x = 3, y = 4.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexWriteNseChain from State.testSuiteStore
  { uint i = 2;
    uint x = 3;
    uint y = 4;
    balances[i+1] = x*y + 3;
    uint r = balances[3];
    assert((r == 15)) }

/-- solkey `TestSuite.storageLocalDeclSkip` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageLocalDeclSkip from State.testSuiteStore
  { Person storage p = undefined;
    age = 7;
    uint r = age;
    assert((r == 7)) }

/-- solkey `TestSuite.storageMatrixNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 1, j = 2, x = 5, y = 6.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageMatrixNseIndex from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    uint i = 1;
    uint j = 2;
    uint x = 5;
    uint y = 6;
    matrix[i+1][j+1] = x + y;
    assert((matrix[2][3] == 11)) }

/-- solkey `TestSuite.storageMatrixWriteRead` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageMatrixWriteRead from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    matrix[2][3] = 99;
    uint r = matrix[2][3];
    assert((r == 99)) }

/-- solkey `TestSuite.storagePopAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePopAfterPush from State.testSuiteStore
  { values.push();
    values.pop();
    assert((values.length == 0)) }

/-- solkey `TestSuite.storagePopNonempty` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePopNonempty from State.testSuiteStore
  { values.push();
    values.push();
    values.pop();
    assert((values.length == 1));
    values.push();
    assert((values[1] == 0)) }

/-- solkey `TestSuite.storagePopUnknownLength` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storagePopUnknownLength from State.testSuiteStore
  { values.push();
    values.pop() }

/-- solkey `TestSuite.storagePushEmpty` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushEmpty from State.testSuiteStore
  { values.push();
    values.push();
    values.push();
    assert((values.length == 3)) }

/-- solkey `TestSuite.storagePushLengthPositive` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storagePushLengthPositive from State.testSuiteStore
  { values.push();
    assert((values.length > 0)) }

/-- solkey `TestSuite.storagePushLocalBind` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushLocalBind from State.testSuiteStore
  { persons.push();
    persons.push();
    Person storage p = undefined;
    p@Person = persons.push();
    assert((persons.length == 3)) }

/-- solkey `TestSuite.storagePushNonsimpleArg` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 40, y = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushNonsimpleArg from State.testSuiteStore
  { values.push();
    values.push();
    uint x = 40;
    uint y = 2;
    values.push(x + y);
    assert((values[2] == 42));
    assert((values.length == 3)) }

/-- solkey `TestSuite.storagePushReadBack` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storagePushReadBack from State.testSuiteStore
  { values.push(42);
    uint r = values[values.length - 1];
    assert((r == 42)) }

end TestSuite
end Calculus
end Solidity
