import Solidity.Tactics.Derivation
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part09

Obligations 193-216 of 245.

The same obligations as `Solidity/Corpus/Wp/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.testStorageComplexReceiverPushFieldLvalue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageComplexReceiverPushFieldLvalue from State.testSuiteStore
  { (bucket@@TokenBucket.tokens).push().value = 5;
    TokenArray storage bt = bucket@@TokenBucket.tokens;
    assert((bt@TokenArray.length == 1));
    assert((bt@TokenArray[0].value == 5)) }

/-- solkey `TestSuite.testStorageComplexReceiverPushLvalueCopy` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageComplexReceiverPushLvalueCopy from State.testSuiteStore
  { alice.account.token.value = 7;
    Token storage tokRef = alice.account.token;
    (bucket@@TokenBucket.tokens).push() = tokRef@Token;
    TokenArray storage bt = bucket@@TokenBucket.tokens;
    assert((bt@TokenArray.length == 1));
    assert((bt@TokenArray[0].value == 7)) }

/-- solkey `TestSuite.testStorageDeletePaperCase` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageDeletePaperCase from State.testSuiteStore
  { alice.account.balance = 100;
    alice.account.token.value = 7;
    delete alice.account;
    uint b = alice.account.balance;
    uint v = alice.account.token.value;
    assert((b == 0));
    assert((v == 0)) }

/-- solkey `TestSuite.testStorageIndexWriteImpureIndexPrimitiveRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageIndexWriteImpureIndexPrimitiveRhs from State.testSuiteStore
  { uint i = 0;
    (aux@@UintArray).push(100);
    (aux@@UintArray).push(100);
    aux@@UintArray[i++] = i;
    assert((i == 1));
    assert((aux@@UintArray[0] == 0)) }

/-- solkey `TestSuite.testStorageIndexWriteImpureIndexRefRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageIndexWriteImpureIndexRefRhs from State.testSuiteStore
  { persons.push();
    persons.push();
    bob.age = 0;
    persons[bob.age++] = bob;
    assert((bob.age == 1));
    assert((persons[0].age == 1)) }

/-- solkey `TestSuite.testStorageEvaluationOrder` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageEvaluationOrder from State.testSuiteStore
  { uint i = 0;
    (aux@@UintArray).push(100);
    (aux@@UintArray).push(100);
    (aux@@UintArray).push(100);
    aux@@UintArray[++i] = ++i;
    assert((aux@@UintArray[2] == 1)) }

/-- solkey `TestSuite.testStorageFieldDeepCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageFieldDeepCopy from State.testSuiteStore
  { bob.account.balance = 10;
    bob.account.token.value = 7;
    Account storage bobAcc = bob.account;
    alice.account = bobAcc@Account;
    bob.account.balance = 20;
    bob.account.token.value = 9;
    assert((alice.account.balance == 10));
    assert((alice.account.token.value == 7)) }

/-- solkey `TestSuite.testStorageMapReadWriteAndDelete` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageMapReadWriteAndDelete from State.testSuiteStore
  { valuesMap@@UintMap[1] = 10;
    valuesMap@@UintMap[2] = 20;
    uint v = valuesMap@@UintMap[1];
    uint kept = valuesMap@@UintMap[2];
    delete valuesMap@@UintMap[1];
    assert((v == 10));
    assert((kept == 20));
    assert((valuesMap@@UintMap[1] == 0));
    assert((valuesMap@@UintMap[2] == 20)) }

/-- solkey `TestSuite.testStorageMapStructCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageMapStructCopy from State.testSuiteStore
  { accountMap@@AccountMap[1].balance = 10;
    accountMap@@AccountMap[1].token.value = 7;
    accountMap@@AccountMap[2] = accountMap@@AccountMap[1];
    accountMap@@AccountMap[1].balance = 20;
    accountMap@@AccountMap[1].token.value = 9;
    assert((accountMap@@AccountMap[2].balance == 10));
    assert((accountMap@@AccountMap[2].token.value == 7)) }

/-- solkey `TestSuite.testStorageNestedPushReturnAlias` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageNestedPushReturnAlias from State.testSuiteStore
  { Account storage acc = persons.push().account;
    acc@Account.balance = 50;
    assert((persons.length == 1));
    assert((acc@Account.balance == 50)) }

/-- solkey `TestSuite.testStoragePushFieldLvalue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStoragePushFieldLvalue from State.testSuiteStore
  { (tokens@@TokenArray).push().value = 11;
    assert((tokens@@TokenArray.length == 1));
    assert((tokens@@TokenArray[0].value == 11)) }

/-- solkey `TestSuite.testStoragePushLvalueCopiesStorageSource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStoragePushLvalueCopiesStorageSource from State.testSuiteStore
  { alice.account.token.value = 9;
    Token storage storageRef = alice.account.token;
    (tokens@@TokenArray).push() = storageRef@Token;
    assert((tokens@@TokenArray.length == 1));
    assert((tokens@@TokenArray[0].value == 9)) }

/-- solkey `TestSuite.testStoragePushLvaluePrimitive` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStoragePushLvaluePrimitive from State.testSuiteStore
  { values.push() = 77;
    assert((values.length == 1));
    assert((values[0] == 77)) }

/-- solkey `TestSuite.testStoragePushReturnAlias` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStoragePushReturnAlias from State.testSuiteStore
  { Token storage t = (tokens@@TokenArray).push();
    t@Token.value = 99;
    assert((tokens@@TokenArray.length == 1));
    assert((tokens@@TokenArray[0].value == 99)) }

/-- solkey `TestSuite.testStorageRootDeepCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageRootDeepCopy from State.testSuiteStore
  { bob.age = 21;
    bob.account.balance = 11;
    alice = bob;
    bob.age = 30;
    bob.account.balance = 12;
    assert((alice.age == 21));
    assert((alice.account.balance == 11)) }

/-- solkey `TestSuite.testStorageStructDeleteSkipsMappingMember` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageStructDeleteSkipsMappingMember from State.testSuiteStore
  { ledger@@Ledger.nonce = 5;
    ledger@@Ledger.balances[1] = 10;
    ledger@@Ledger.balances[2] = 20;
    delete ledger@@Ledger;
    assert((ledger@@Ledger.nonce == 0));
    assert((ledger@@Ledger.balances[1] == 10));
    assert((ledger@@Ledger.balances[2] == 20));
    delete ledger@@Ledger.balances[1];
    assert((ledger@@Ledger.balances[1] == 0));
    assert((ledger@@Ledger.balances[2] == 20)) }

/-- solkey `TestSuite.testStorageToMemoryCopyComplexPath` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageToMemoryCopyComplexPath from State.testSuiteStore
  { alice.account.token.value = 17;
    Token memory mv = alice.account.token;
    alice.account.token.value = 18;
    assert((mv@Token.value == 17)) }

/-- solkey `TestSuite.testStorageToMemoryCopyField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageToMemoryCopyField from State.testSuiteStore
  { alice.account.balance = 10;
    Account memory mv = alice.account;
    alice.account.balance = 20;
    uint v = mv@Account.balance;
    assert((v == 10)) }

/-- solkey `TestSuite.testStorageToMemoryCopyRoot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageToMemoryCopyRoot from State.testSuiteStore
  { alice.age = 25;
    Person memory mv = alice;
    alice.age = 30;
    uint v = mv@Person.age;
    assert((v == 25)) }

/-- solkey `TestSuite.testStorageWriteAndRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageWriteAndRead from State.testSuiteStore
  { uint x = 20;
    uint y = 1;
    alice.age = x + y;
    uint v = alice.age;
    assert((v == 21)) }

/-- solkey `TestSuite.storageFieldDecomposition` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDecomposition from State.testSuiteStore
  { alice.account.balance = 34;
    assert((alice.account.balance == 34));
    uint r = alice.account.balance;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldDeepValue` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepValue from State.testSuiteStore
  { alice.account.token.value = 7;
    assert((alice.account.token.value == 7));
    uint r = alice.account.token.value;
    assert((r == 7)) }

/-- solkey `TestSuite.storageIndexDecomposition` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexDecomposition from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    matrix[2].push();
    matrix[2][3] = 34;
    assert((matrix[2][3] == 34));
    uint r = matrix[2][3];
    assert((r == 34)) }

/-- solkey `TestSuite.storageIndexRootArray` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexRootArray from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 42;
    assert((values[1] == 42));
    uint r = values[1];
    assert((r == 42)) }

end TestSuite
end Calculus
end Solidity
