import Solidity.TestSuite.Derived1
import Solidity.TestSuite.Derived2
import Solidity.TestSuite.Derived3
import Solidity.TestSuite.Derived4
import Solidity.TestSuite.Derived5
import Solidity.TestSuite.Derived6
import Solidity.TestSuite.Derived7
import Solidity.TestSuite.Derived8

/-!
# What is derived of solkey's `TestSuite`

Every function, by what `#solkey_obligations` (`Frontend/Problems.lean`)
finds: derived when its theorem `N.f.proved` exists, states
`⊢ N.f.problem` and uses no axiom but Lean's three (so no `sorry` and no
`native_decide`: one that does is listed "unsound"), pending when only its
statement does, and the import's verdict for the three with no statement.
A pending obligation is no theorem and no `sorry`: most wait for the closer
to reduce memory; the others are listed with their reasons in
`docs/testsuite-proofs.md`.
-/

/--
info: 420 functions: 300 derived, 117 pending, 3 other
excluded recursiveStructMapping
skipped tryCalleeGet
skipped tryCalleePing
pending:
memoryDeclDefault memoryArrayIndex memoryNewIntoStructField memoryNewIntoNestedField memoryNewIntoIndex storageNewIntoField
memoryDeepField memoryFieldAddAssign memoryFieldSubAssign memoryFieldMulAssign memoryFieldDivAssign memoryFieldModAssign
memoryFieldAddAssignUnfold memoryFieldAddAssignNse memoryFieldPreincrement memoryFieldPostincrement memoryFieldPredecrement memoryFieldPostdecrement
memoryFieldPreincrementAssignment memoryFieldPostincrementAssignment memoryFieldPredecrementAssignment memoryFieldPostdecrementAssignment memoryFieldPreincrementUnfold memoryFieldAlias
memoryFieldReferenceAssign memoryIndexArrayAddAssign memoryIndexArraySubAssign memoryIndexArrayMulAssign memoryIndexArrayDivAssign memoryIndexArrayModAssign
memoryIndexArrayAddAssignUnfold memoryIndexArrayPreincrementUnfold memoryIndexArrayPreincrement memoryIndexArrayPostdecrement memoryIndexArrayPostincrementAssignment memoryIndexArrayPredecrementAssignment
memoryIndexWriteNse memoryRootAlias memoryRootDeleteFresh memoryStructArrayIndex memoryToStorage memoryToStorageIndexMappingCopyRootExample
memoryToStorageIndexArrayCopyRootExample memoryToStorageIndexArrayCopyRootOutOfBoundsReverts storagePushReadBack storageToMemory testMemoryAliasing testMemoryDeleteAlias
testMemoryDeleteIdentityFieldFreshensSlot testMemoryDeletePrimitiveField testMemoryEvaluationOrder testMemoryFieldShallowCopy testMemoryIndexWriteImpureIndexPrimitiveRhs testMemoryIndexWriteImpureIndexRefRhs
testMemoryRootAlias testMemoryRootDeleteRebindsOnlyLocal testMemoryToStorageCopyComplexSource testMemoryToStorageCopyComplexTarget testMemoryToStorageCopyField testMemoryToStorageCopyRoot
testMemoryToStorageIndexCopyImpureIndex testMemoryTokenArrayAuxiliaryCases testMemoryUintArrayAuxiliaryCases testMemoryUintArrayPostdecrement testMemoryUintArrayPostincrement testMemoryUintArrayPredecrement
testMemoryFieldWriteImpureReceiver testDanglingReferenceSurvivesPush testArrayCopyClearsOldElements testArrayCopyKeepsDestinationTail testMemoryStructFixedMemberLength testMemoryFixedArrayLength
testMemoryNestedFixedArrayLength testNewArrayOfFixedElementLength testMemoryDynamicArrayDefaultLength testDeleteArrayLeavesDataPastLength testDanglingInnerArrayReappearsAfterPush testStorageToMemoryCopyComplexPath
testStorageToMemoryCopyField testStorageToMemoryCopyRoot memoryAssignForms memoryDelete storageIndexWriteRefSourceImpureIndex storageFieldWriteRefSourceImpureReceiver
memoryFieldWriteMemRefImpureReceiver memoryToStorageIndexImpureReceiver memoryIndexWriteMemRefImpureReceiver indexWriteBothImpureMemToStorage indexWriteBothImpureMemoryValue indexWriteBothImpureMemRef
memoryFieldAsMappingKey mappingEntryThroughMemoryToMappingEntry indexWriteValueRhsCapture memoryIndexWriteMemRefRhsCapture memoryIndexDeleteNonSimpleIndexCapture memoryFieldSubAssignUnfold
memoryFieldMulAssignUnfold memoryFieldDivAssignUnfold memoryFieldModAssignUnfold memoryFieldPostincrementUnfold memoryFieldPredecrementUnfold memoryFieldPostdecrementUnfold
memoryFieldDeleteUnfold memoryFieldReadUnfoldResult memoryIndexReadUnfoldResult memoryIndexArraySubAssignUnfold memoryIndexArrayMulAssignUnfold memoryIndexArrayDivAssignUnfold
memoryIndexArrayModAssignUnfold memoryIndexArrayPostincrementUnfold memoryIndexArrayPredecrementUnfold memoryIndexArrayPostdecrementUnfold memoryIndexArrayDeleteUnfold memoryIndexArrayPostincrement
memoryIndexArrayPredecrement memoryIndexArrayPreincrementAssignment memoryIndexArrayPostdecrementAssignment
-/
#guard_msgs in
#solkey_obligations Solkey.TestSuite
