import Solidity.TestSuite.Derived1
import Solidity.TestSuite.Derived2
import Solidity.TestSuite.Derived3

/-!
# What is derived of solkey's `TestSuite`

Every function, by what `#solkey_obligations` (`Frontend/Problems.lean`)
finds: derived when its theorem `N.f.proved` exists, pending when only its
statement does, and the import's verdict for the three with no statement.
A pending obligation is no theorem and no `sorry`: it waits for the closer
to read what `wt(storage)` gives and the storage operations it does not
reduce yet (`docs/testsuite-proofs.md`).
-/

/--
info: 420 functions: 111 derived, 306 pending, 3 without an obligation
excluded recursiveStructMapping
skipped tryCalleeGet
skipped tryCalleePing
pending:
storageRootReadWrite storageFieldWriteRead storageFieldDeepAddAssign storageFieldGlobalAge storageAliasWrite storageIndexRootMapping
storageIndexMappingAddAssign storageIndexWriteComplexReceiverCopySource storageFieldWriteRootRhsComplexReceiver storageIndexWriteRootRhsComplexReceiver storagePushValue storagePushComplexReceiverNonsimpleArg
storagePushValueCopySource storageBoolRootReadWrite storageBoolRootCopy storageBoolFieldRead storageBoolMappingRead storageBoolFieldStoreRoot
memoryDeclDefault memoryArrayIndex memoryNewIntoStructField memoryNewIntoNestedField memoryNewIntoIndex storageNewIntoField
testStorageComplexReceiverEmptyPush additionBothStorage additionStorageRead memoryDeepField memoryFieldAddAssign memoryFieldSubAssign
memoryFieldMulAssign memoryFieldDivAssign memoryFieldModAssign memoryFieldAddAssignUnfold memoryFieldAddAssignNse memoryFieldPreincrement
memoryFieldPostincrement memoryFieldPredecrement memoryFieldPostdecrement memoryFieldPreincrementAssignment memoryFieldPostincrementAssignment memoryFieldPredecrementAssignment
memoryFieldPostdecrementAssignment memoryFieldPreincrementUnfold memoryFieldAlias memoryFieldReferenceAssign memoryIndexArrayAddAssign memoryIndexArraySubAssign
memoryIndexArrayMulAssign memoryIndexArrayDivAssign memoryIndexArrayModAssign memoryIndexArrayAddAssignUnfold memoryIndexArrayPreincrementUnfold memoryIndexArrayPreincrement
memoryIndexArrayPostdecrement memoryIndexArrayPostincrementAssignment memoryIndexArrayPredecrementAssignment memoryIndexWriteNse memoryRootAlias memoryRootDeleteFresh
memoryStructArrayIndex memoryToStorage memoryToStorageIndexMappingCopyRootExample memoryToStorageIndexArrayCopyRootExample memoryToStorageIndexArrayCopyRootOutOfBoundsReverts requireHoldsDiamond
storageAliasRebindAlias storageDeepFieldPostincrement storageDeepFieldPreincrement storageFieldAddAssign storageFieldCopyStruct storageFieldCopyValueField
storageFieldDeepDivAssign storageFieldDeepModAssign storageFieldDeepMulAssign storageFieldDeepSubAssign storageFieldDeepWriteRead storageFieldDelete
storageFieldDeleteThenCopy storageFieldDeleteThenCopyDeep storageFieldDivAssign storageFieldModAssign storageFieldMulAssign storageFieldPostdecrementAssign
storageFieldPostdecrement storageFieldPostincrementAssign storageFieldPostincrement storageFieldPredecrementAssign storageFieldPredecrement storageFieldPreincrementAssign
storageFieldPreincrement storageFieldReadBindLocal storageFieldReadStoreRoot storageFieldSubAssign storageFieldWriteCaptureSrc storageFieldWriteRhsCapture
storageIndexCopyValue storageIndexCopysourceAfterPush storageIndexDecomposeAfterPush storageIndexDeleteMappingBool storageIndexDeleteMappingStruct storageIndexDeleteNseIndex
storageIndexPostdecrementAssign storageIndexPostincrementAssign storageIndexPredecrementAssign storageIndexPreincrementAssign storageIndexWriteNseChain storageLocalDeclSkip
storageMatrixNseIndex storagePopAfterPush storagePopNonempty storagePopUnknownLength storagePushEmpty storagePushLengthPositive
storagePushLocalBind storagePushNonsimpleArg storagePushReadBack storagePushReturnAssign storageRootAddAssign storageRootCopySource
storageRootCopyStruct storageRootDeleteStruct storageRootDeleteThenCopy storageRootDelete storageRootDisjoint storageRootDivAssign
storageRootModAssign storageRootMulAssign storageRootMultipleWrites storageRootPostdecrementAssign storageRootPostincrementAssign storageRootPostincrement
storageRootPredecrement storageRootPreincrementAssign storageRootPreincrement storageRootSubAssign storageRootWriteRhsCapture storageToMemory
subtractionStorageRead testDeepPopDoesNotResetMappingMember testDeleteArrayDoesNotResetElementMappingMember testMemoryAliasing testMemoryDeleteAlias testMemoryDeleteIdentityFieldFreshensSlot
testMemoryDeletePrimitiveField testMemoryEvaluationOrder testMemoryFieldShallowCopy testMemoryIndexWriteImpureIndexPrimitiveRhs testMemoryIndexWriteImpureIndexRefRhs testMemoryRootAlias
testMemoryRootDeleteRebindsOnlyLocal testMemoryToStorageCopyComplexSource testMemoryToStorageCopyComplexTarget testMemoryToStorageCopyField testMemoryToStorageCopyRoot testMemoryToStorageIndexCopyImpureIndex
testMemoryTokenArrayAuxiliaryCases testMemoryUintArrayAuxiliaryCases testMemoryUintArrayPostdecrement testMemoryUintArrayPostincrement testMemoryUintArrayPredecrement testNestedIndexWriteImpureIndexPrimitiveRhs
testNestedIndexReadImpureIndex testNestedIndexWriteImpureReceiverAndIndex testNestedIndexReadImpureReceiverAndIndex testStorageDeleteImpureReceiver testStoragePushImpureReceiver testCompoundAssignImpureReceiver
testMemoryFieldWriteImpureReceiver testIndexWriteReceiverReadsMutatedVar testNestedStorageWrites testStorageAliases testStorageComplexReceiverPushFieldLvalue testStorageComplexReceiverPushLvalueCopy
testStorageDeletePaperCase testStorageIndexWriteImpureIndexPrimitiveRhs testStorageIndexWriteImpureIndexRefRhs testStorageEvaluationOrder testStorageFieldDeepCopy testStorageMapReadWriteAndDelete
testStorageMapStructCopy testStorageNestedPushReturnAlias testStoragePushFieldLvalue testStoragePushLvalueCopiesStorageSource testStoragePushLvaluePrimitive testStoragePushReturnAlias
testDanglingReferenceSurvivesPush testArrayCopyClearsOldElements testArrayCopyKeepsDestinationTail testStorageIndexDeleteOutOfBoundsReverts testFixedArrayDeleteKeepsLength testFixedArrayIndexInBounds
testMemoryStructFixedMemberLength testMemoryFixedArrayLength testMemoryNestedFixedArrayLength testNewArrayOfFixedElementLength testMappingOfFixedArrayLength testMemoryDynamicArrayDefaultLength
testFixedStructArrayDeleteResetsElements testStructWithFixedArrayDeleteKeepsLength testStructWithFixedArrayCopy testFixedMappingArrayDeleteKeepsEntries testDeleteArrayLeavesDataPastLength testPopKeepsMappingElementEntries
testDeleteKeepsMappingElementEntries testPushBindMappingElement testDanglingInnerArrayReappearsAfterPush testStorageRootDeepCopy testStorageStructDeleteSkipsMappingMember testStorageToMemoryCopyComplexPath
testStorageToMemoryCopyField testStorageToMemoryCopyRoot testStorageWriteAndRead storageFieldDecomposition storageFieldDeepValue storageFieldDisjointFields
storageFieldDisjointRoots memoryAssignForms memoryDelete storageAliasRebindOriginal testSimpleAssert storageIndexWriteRefSourceImpureIndex
storageFieldWriteRefSourceImpureReceiver storageFieldWriteStorageRefImpureReceiver storageFieldWriteRootRefImpureReceiver memoryFieldWriteMemRefImpureReceiver storageIndexWriteRootRefImpureReceiver storageIndexWriteStorageRefImpureReceiver
memoryToStorageIndexImpureReceiver memoryIndexWriteMemRefImpureReceiver testCopyRootKeepsValueMembers testCopyFieldNested testCopyOfCopy testCopyIntoMappingEntry
testCopyArrayMemberElements testCopyPrimitiveRoot testCopyStoreRootFromField testCopyStoreRootFromIndex testPushCopyThenDeleteTarget indexWriteBothImpureStorageRef
indexWriteBothImpureMemToStorage indexWriteBothImpureMemoryValue indexWriteBothImpureMemRef nestedMappingWriteRead nestedMappingRowAlias arrayOfMappingsIndex
mappingOfLedgerMember mappingPointerTernary mappingReadAsKey memoryFieldAsMappingKey mappingEntryThroughMemoryToMappingEntry boolKeyMapping
boolKeyMappingSymbolicKey indexWriteValueRhsCapture memoryIndexWriteMemRefRhsCapture memoryIndexDeleteNonSimpleIndexCapture storageSignedDivModAssign memoryFieldSubAssignUnfold
memoryFieldMulAssignUnfold memoryFieldDivAssignUnfold memoryFieldModAssignUnfold memoryFieldPostincrementUnfold memoryFieldPredecrementUnfold memoryFieldPostdecrementUnfold
memoryFieldDeleteUnfold memoryFieldReadUnfoldResult memoryIndexReadUnfoldResult memoryIndexArraySubAssignUnfold memoryIndexArrayMulAssignUnfold memoryIndexArrayDivAssignUnfold
memoryIndexArrayModAssignUnfold memoryIndexArrayPostincrementUnfold memoryIndexArrayPredecrementUnfold memoryIndexArrayPostdecrementUnfold memoryIndexArrayDeleteUnfold memoryIndexArrayPostincrement
memoryIndexArrayPredecrement memoryIndexArrayPreincrementAssignment memoryIndexArrayPostdecrementAssignment storageFieldDeleteUnfold storageFieldPredecrementUnfold storageFieldPostdecrementUnfold
storageIndexAddAssignUnfold storageIndexSubAssignUnfold storageIndexMulAssignUnfold storageIndexDivAssignUnfold storageIndexModAssignUnfold storageIndexPreincrementUnfold
storageIndexPostincrementUnfold storageIndexPredecrementUnfold storageIndexPostdecrementUnfold storageIndexMappingSubAssign storageIndexMappingMulAssign storageIndexMappingDivAssign
storageIndexMappingModAssign storageIndexMappingPreincrement storageIndexMappingPostincrement storageIndexMappingPredecrement storageIndexMappingPostdecrement storageIndexMappingPreincrementAssignment
storageIndexMappingPostincrementAssignment storageIndexMappingPredecrementAssignment storageIndexMappingPostdecrementAssignment storageRootPostdecrement storageRootPredecrementAssign ternaryToIfStorage
-/
#guard_msgs in
#solkey_obligations Solkey.TestSuite
