import Solidity.Frontend.Import
import Solidity.Calculus.Close
import Solidity.Tools.Show

/-!
# Loops from solc's AST

solkey's loops, as its `TestSuite.sol` writes them past `ed7849d5b6`, in a
contract of their own (`tests/solc/Loops.sol`; the TestSuite fixture stays at
the pinned checkout), with Lean's own `unwind` clauses and a few functions
of Lean's own (marked so there).  solc drops the `/// @custom:key` lines
above a loop; `scripts/solc-ast.mjs` reads them from the source by the
loop's `src` offset, as solkey's `SolJSONParser.loopSpec` does, a clause
over several `///` lines joined, and keeps them as the loop's `loopSpec`,
which the front end prints above the loop (`SolcJson.loopSpec`).  The
fixture is regenerated by

    node scripts/solc-ast.mjs --solkey <clone at the pin> --soljson <dir> \
      --source tests/solc/Loops.sol --out tests/solc/Loops.ast.json \
      --wrapper Solidity/Examples/Tactics/LoopsImport.lean

which rewrites the hash below.  A function's loops are lowered before its
`return`s, as solkey's `LoopLowering` runs after its `ReturnLowering`: a
`return` inside a loop is a flag (`loopNestedReturn`), and a body with one
is renamed fresh first, so that a sibling `for (uint i …)` declares a name
of its own (`returnBeforeSiblingLoop`).
-/

solc_import "../../../tests/solc/Loops.ast.json" hash 0x499c9a4ed86a4b11 as Solc.Loops

namespace Solidity.Examples.LoopsImport

/-- info: 9 functions (4 diamond, 3 box, 0 skip, 2 internal): 9 elaborated, 0 skipped, 0 excluded, 0 unsupported -/
#guard_msgs in
#eval IO.println (Solidity.Frontend.ImportRow.summary Solc.Loops.report)

/-- info: require(n >= 0);
uint i = 0;
/// @custom:key invariant i <= n while (i < n) { i = i + 1; }
assert(i == n); -/
#guard_msgs in
#eval IO.println (Prog.show Solc.Loops.invariantCountsToBound)

/-- solkey's `invariantCountsToBound`, its `box` obligation: the loop's
invariant proves the `assert` after it. -/
theorem invariantCountsToBound :
    Valid (Fml.modal .box Solc.Loops.invariantCountsToBound .tt) := by
  unfold Solc.Loops.invariantCountsToBound
  sol_symex
  sol_close

/-- `invariantBreak`: the invariant holds at the head the `break` leaves
from too. -/
theorem invariantBreak : Valid (Fml.modal .box Solc.Loops.invariantBreak .tt) := by
  unfold Solc.Loops.invariantBreak
  sol_symex
  sol_close

/-- `whileCountsUp`, under the diamond, unwound three times (`unwind 3`, a
clause only Lean reads). -/
theorem whileCountsUp : Valid (Fml.modal .diamond Solc.Loops.whileCountsUp .tt) := by
  unfold Solc.Loops.whileCountsUp
  sol_symex
  sol_close

/-- `doWhileRunsBodyFirst`, under the diamond: the body runs once, though the
condition is false from the start (`unwind 1`, the one iteration). -/
theorem doWhileRunsBodyFirst :
    Valid (Fml.modal .diamond Solc.Loops.doWhileRunsBodyFirst .tt) := by
  unfold Solc.Loops.doWhileRunsBodyFirst
  sol_symex
  sol_close

/-- `invariantTwoLines`: the invariant read over its two `///` lines, as
solkey's `KeyNatspec` joins them. -/
theorem invariantTwoLines : Valid (Fml.modal .box Solc.Loops.invariantTwoLines .tt) := by
  unfold Solc.Loops.invariantTwoLines
  sol_symex
  sol_close

/-! `loopNestedReturn` and `returnBeforeSiblingLoop` are `internal`: no
obligation, only their programs, the `return` lowered to a flag. -/

/-- info: uint r;
uint se1 = 0;
bool ret3 = false;
while (!ret3 && (se1 < 3)) { uint se2 = 0; while (!ret3 && (se2 < 3)) { if (((se1 * 3) + se2) == k) { r = (se1 * 10) + se2; ret3 = true; } else {  } if (!ret3) { se2++; } else {  } } if (!ret3) { se1++; } else {  } }
if (ret3) {  } else { r = 99; } -/
#guard_msgs in
#eval IO.println (Prog.show Solc.Loops.loopNestedReturn)

/-- info: uint r;
uint se1 = 0;
bool ret3 = false;
while (!ret3 && (se1 < 3)) { if (se1 == k) { r = se1; ret3 = true; } else {  } if (!ret3) { se1++; } else {  } }
if (ret3) {  } else { uint se2 = 0; while (se2 < 2) { r = r + se2; se2++; } } -/
#guard_msgs in
#eval IO.println (Prog.show Solc.Loops.returnBeforeSiblingLoop)

/-! Two of solkey's functions elaborate but are not proved here, both under
the diamond (`docs/loops.md`, L4):

* `forContinueStillUpdates`, unwound five times with a `continue` flag in
  each copy: `sol_symex` exceeds `simp`'s step bound, and `sol_prove`'s
  derivation passes `Derive.budget` (20000 steps);
* `invariantVariantSkipsBreakIteration`: the `break` flag is read through
  the cover, which the closer does not close within the default
  heartbeats. -/

end Solidity.Examples.LoopsImport
