import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcControlFlow.sol`, ported

solkey `1b4341a303`: 10 functions — 6 proved, 2 evaluated, 2 unsupported.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcControlFlow

open Semantics

/-- solkey `SolcControlFlow.doWhileFalseRunsBodyOnce` (`solc/SolcControlFlow.sol`).

solc: statements/do_while_loop_continue.sol — `do { … } while (false)` runs its body
exactly once. Unrolled: the guard `i > 0` is false on the only iteration, so the body
increments `i` and execution continues past the loop.

The increment is written `i = i + 1;` rather than `i++;` — a bare increment of a
*local* has no rule (see `SolcExpressions.bareIncrementOnLocal`). -/
theorem doWhileFalseRunsBodyOnce :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      uint i = 0;
      uint r = 0;
      if (i > 0) { r = 0; } else { i = i + 1; };
      r = 42;
      assert(i == 1);
      assert(r == 42);
    } := by
  corpus_decide solcControlFlowStore_eq

/-- solkey `SolcControlFlow.forLoopUnrolledOverArray` (`solc/SolcControlFlow.sol`).

solc: array/array_storage_index_zeroed_test.sol — the upstream
`for (uint i = 0; i < len; i++) storageArray[i] = i + 1;`, unrolled at length 3.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem forLoopUnrolledOverArray :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      values.push(0);
      values.push(0);
      values.push(0);
      uint i = 0;
      values[i] = i + 1;
      i = i + 1;
      values[i] = i + 1;
      i = i + 1;
      values[i] = i + 1;
      i = i + 1;
      assert(i == 3);
      assert(values[0] == 1);
      assert(values[1] == 2);
      assert(values[2] == 3);
    } := by
  corpus_decide solcControlFlowStore_eq

/-- solkey `SolcControlFlow.sequentialAssignmentDoesNotSwap` (`solc/SolcControlFlow.sol`).

solc: various/swap_in_storage_overwrite.sol — `(x, y) = (y, x)` does not swap. solc
assigns the tuple components with no temporary, so the pair runs as `y = x; x = y;`
and both structs end up holding x's original value. Tuple assignment does not parse
here, so the port is that desugaring. -/
theorem sequentialAssignmentDoesNotSwap :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      sx.a = 1;
      sx.b = 2;
      sy.a = 3;
      sy.b = 4;
      sy = sx;
      sx = sy;
      assert(sx.a == 1);
      assert(sx.b == 2);
      assert(sy.a == 1);
      assert(sy.b == 2);
    } := by
  corpus_decide solcControlFlowStore_eq

/-! solkey `SolcControlFlow.swapViaTemporary` (`solc/SolcControlFlow.sol`).

solc: various/swap_in_storage_overwrite.sol — the corrected version, with the temporary
the upstream test shows is necessary.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcControlFlowStore
  sol[SolcControlFlow]{
    sx.a = 1;
    sx.b = 2;
    sy.a = 3;
    sy.b = 4;
    Pair memory tmp = sx;
    sx = sy;
    sy = tmp;
    assert(sx.a == 3);
    assert(sx.b == 4);
    assert(sy.a == 1);
    assert(sy.b == 2);
  }

/-! solkey `SolcControlFlow.ifElseSelectsMemorySource` (`solc/SolcControlFlow.sol`).

solc: expressions/conditional_expression_storage_memory_1.sol — the same selection into
a storage target, written as `if`/`else` instead of `?:`.

concretized: solkey proves this for all parameters; ported at cond = 0.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcControlFlowStore
  sol[SolcControlFlow]{
    uint cond = 0;
    bool c = cond == 1;
    Pair memory mx;
    mx.a = 11;
    Pair memory my;
    my.a = 22;
    if (c) { target = mx; } else { target = my; };
    assert(target.a == 22);
  }

/-- solkey `SolcControlFlow.ternarySelectsValueByFlag` (`solc/SolcControlFlow.sol`).

solc: expressions/conditional_expression_storage_memory_1.sol — the branch selection on
its own, over plain values rather than references.

concretized: solkey proves this for all parameters; ported at cond = 0.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem ternarySelectsValueByFlag :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      uint cond = 0;
      bool c = cond == 1;
      uint r = c ? 11 : 22;
      assert(r == 22);
    } := by
  corpus_decide solcControlFlowStore_eq

/-- solkey `SolcControlFlow.chainedIfsSelectLastMatch` (`solc/SolcControlFlow.sol`).

solc: expressions/conditional_expression_storage_memory_1.sol — the upstream result is
read back through a chain of independent `if`s, the last matching one winning. -/
theorem chainedIfsSelectLastMatch :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      target.a = 2;
      uint t = target.a;
      uint r = 0;
      if (t == 1) { r = 1; };
      if (t == 2) { r = 2; };
      assert(r == 2);
    } := by
  corpus_decide solcControlFlowStore_eq

/-- solkey `SolcControlFlow.nestedIfElseSelectsBranch` (`solc/SolcControlFlow.sol`).

solc: expressions/conditional_expression_multiple.sol — the same branch structure as a
nested `if`/`else` rather than a nested `?:`.

concretized: solkey proves this for all parameters; ported at x = 500.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem nestedIfElseSelectsBranch :
    Diamond State.solcControlFlowStore
    sol[SolcControlFlow]{
      uint x = 500;
      uint d = 0;
      if (x > 100) { if (x > 1000) { d = 1000; } else { d = 100; }; } else { if (x > 50) { d = 50; } else { d = 10; }; };
      assert(d == 100);
    } := by
  corpus_decide solcControlFlowStore_eq

end Solidity.Corpus.SolcControlFlow
