import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcMemory.sol`, ported

solkey `1b4341a303`: 11 functions — 6 evaluated, 3 proved, 2 unsupported.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcMemory

open Semantics

/-! solkey `SolcMemory.memoryStructDefaultsToZero` (`solc/SolcMemory.sol`).

solc: structs/memory_structs_read_write.sol (`testInit`) — a fresh memory struct reads
as all zeros.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    Inner memory d;
    assert(d.a == 0);
    assert(d.b == 0);
    assert(d.c == 0);
  }

/-! solkey `SolcMemory.memoryStructWriteRead` (`solc/SolcMemory.sol`).

solc: structs/memory_structs_read_write.sol (`testAssign`) — member writes on a memory
struct read back.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    Inner memory s;
    s.a = 1;
    s.b = 2;
    s.c = 3;
    assert(s.a == 1);
    assert(s.b == 2);
    assert(s.c == 3);
  }

/-! solkey `SolcMemory.storageArrayElementCopiedIntoMemory` (`solc/SolcMemory.sol`).

solc: structs/memory_structs_read_write.sol (`testCopyRead`) — the upstream
`S memory s = data[2];` copy out of a storage array element.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    inners.push();
    inners.push();
    inners.push();
    inners[2].a = 1;
    inners[2].b = 2;
    inners[2].c = 3;
    Inner memory s = inners[2];
    assert(s.a == 1);
    assert(s.b == 2);
    assert(s.c == 3);
  }

/-- solkey `SolcMemory.nestedStorageStructToMemory` (`solc/SolcMemory.sol`).

solc: structs/struct_storage_to_memory.sol — the upstream `X memory m = x;` over a
struct that nests another struct. -/
theorem nestedStorageStructToMemory :
    Diamond State.solcMemoryStore
    sol[SolcMemory]{
      outerX.a = 12;
      outerX.s.a = 42;
      outerX.s.b = 23;
      outerX.s.c = 34;
      Outer memory m = outerX;
      assert(m.a == 12);
      assert(m.s.a == 42);
      assert(m.s.b == 23);
      assert(m.s.c == 34);
    } := by
  corpus_decide solcMemoryStore_eq

/-! solkey `SolcMemory.memoryStructToStorage` (`solc/SolcMemory.sol`).

solc: structs/struct_memory_to_storage.sol — a memory struct assigned into storage.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    Inner memory m;
    m.a = 1;
    m.b = 2;
    m.c = 3;
    innerS = m;
    assert(innerS.a == 1);
    assert(innerS.b == 2);
    assert(innerS.c == 3);
  }

/-- solkey `SolcMemory.storageToMemoryCopyIsDeep` (`solc/SolcMemory.sol`).

solc: structs/copy_from_storage.sol — the storage-to-memory copy is deep: a later write
to the storage source does not reach the memory copy. -/
theorem storageToMemoryCopyIsDeep :
    Diamond State.solcMemoryStore
    sol[SolcMemory]{
      outerX.s.a = 17;
      Inner memory m = outerX.s;
      outerX.s.a = 18;
      assert(m.a == 17);
    } := by
  corpus_decide solcMemoryStore_eq

/-! solkey `SolcMemory.memoryToStorageCopyIsDeep` (`solc/SolcMemory.sol`).

solc: structs/copy_to_mapping.sol — the memory-to-storage copy is deep in the other
direction too.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    Inner memory m;
    m.a = 50;
    innerS = m;
    m.a = 51;
    assert(innerS.a == 50);
  }

/-! solkey `SolcMemory.memoryAliasIsNotACopy` (`solc/SolcMemory.sol`).

solc: structs/memory_structs_nested.sol — a memory struct member is a reference, so two
locals bound to it alias each other.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMemoryStore
  sol[SolcMemory]{
    Outer memory o;
    Inner memory ref = o.s;
    ref.a = 100;
    assert(o.s.a == 100);
  }

/-- solkey `SolcMemory.storageArrayCopiedIntoMemory` (`solc/SolcMemory.sol`).

solc: array/copying/array_copy_storage_to_memory.sol — a whole storage array copied
into memory.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageArrayCopiedIntoMemory :
    Diamond State.solcMemoryStore
    sol[SolcMemory]{
      prims.push(0);
      prims.push(0);
      prims[0] = 3;
      prims[1] = 4;
      uint[] memory m = prims;
      assert(m[0] == 3);
      assert(m[1] == 4);
    } := by
  corpus_decide solcMemoryStore_eq

end Solidity.Corpus.SolcMemory
