import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcArrays.sol`, ported

solkey `78f42fde33`: 12 functions — 7 unsupported, 4 evaluated, 1 proved.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcArrays

open Semantics

/-! solkey `SolcArrays.popThenPushSlotIsZeroed` (`solc/SolcArrays.sol`).

solc: array/array_storage_index_zeroed_test.sol — the upstream invariant that a slot
beyond the current length reads as zero: write a slot, pop it, push it back, and it is
cleared.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcArraysStore
  sol[SolcArrays]{
    storageArray.push();
    storageArray[0] = 7;
    assert(storageArray[0] == 7);
    storageArray.pop();
    storageArray.push();
    assert(storageArray[0] == 0);
  }

/-! solkey `SolcArrays.pushedSlotIsZeroed` (`solc/SolcArrays.sol`).

solc: array/array_storage_index_zeroed_test.sol — the direct form of the same
invariant: a freshly pushed slot reads as zero.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcArraysStore
  sol[SolcArrays]{
    storageArray.push();
    assert(storageArray[0] == 0);
  }

/-- solkey `SolcArrays.storageIndexReadWrite` (`solc/SolcArrays.sol`).

solc: array/array_storage_index_access.sol — element writes are independent of each
other.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexReadWrite :
    Diamond State.solcArraysStore
    sol[SolcArrays]{
      storageArray.push(0);
      storageArray.push(0);
      storageArray.push(0);
      storageArray[0] = 1;
      storageArray[1] = 2;
      storageArray[2] = 3;
      assert(storageArray[0] == 1);
      assert(storageArray[1] == 2);
      assert(storageArray[2] == 3);
    } := by
  corpus_decide solcArraysStore_eq

/-! solkey `SolcArrays.deleteArrayElementOfStructs` (`solc/SolcArrays.sol`).

solc: array/delete/delete_on_array_of_structs.sol — `delete arr[i]` resets that element
and leaves its neighbour alone.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcArraysStore
  sol[SolcArrays]{
    structs.push();
    structs.push();
    structs[0].a = 1;
    structs[0].b = 2;
    structs[1].a = 3;
    structs[1].b = 4;
    delete structs[0];
    assert(structs[0].a == 0);
    assert(structs[0].b == 0);
    assert(structs[1].a == 3);
    assert(structs[1].b == 4);
  }

/-! solkey `SolcArrays.matrixElementWriteRead` (`solc/SolcArrays.sol`).

solc: array/array_2d_assignment.sol — an element of a `uint[][]` is addressed by two
index steps.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcArraysStore
  sol[SolcArrays]{
    matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2][3] = 7;
    uint r = matrix[2][3];
    assert(r == 7);
  }

end Solidity.Corpus.SolcArrays
