import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcExpressions.sol`, ported

solkey `78f42fde33`: 20 functions — 13 proved, 7 unsupported.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcExpressions

open Semantics

/-- solkey `SolcExpressions.postIncrementYieldsOldValue` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — `a++` yields the old value and increments.

`T r = x++;` split into `T r; r = x++;`. -/
theorem postIncrementYieldsOldValue :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint a = 6;
      uint p;
      p = a++;
      assert(p == 6);
      assert(a == 7);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.preIncrementYieldsNewValue` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — `++a` yields the new value.

`T r = x++;` split into `T r; r = x++;`. -/
theorem preIncrementYieldsNewValue :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint a = 6;
      uint q;
      q = ++a;
      assert(q == 7);
      assert(a == 7);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.incDecChainOnLocal` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — the upstream accumulation
`r = a; r += a++ * 0x10; r += ++a * 0x100` on a local, with each step bound
(0x10 = 16, 0x100 = 256; the expected 6 + 6*16 + 8*256 = 2150).

`T r = x++;` split into `T r; r = x++;`. -/
theorem incDecChainOnLocal :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint a = 6;
      uint r = a;
      uint p;
      p = a++;
      r = r + p * 16;
      uint q;
      q = ++a;
      r = r + q * 256;
      assert(a == 8);
      assert(r == 2150);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.incDecChainOnStateVariable` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — same chain on a state variable
(`v = 3; r += v++ * 0x1000; r += ++v * 0x10000`), so the storage increment rules are
exercised instead of the local ones (0x1000 = 4096, 0x10000 = 65536; the expected
3*4096 + 5*65536 = 339968).

`T r = x++;` split into `T r; r = x++;`. -/
theorem incDecChainOnStateVariable :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      counter = 3;
      uint p;
      p = counter++;
      uint r = p * 4096;
      uint q;
      q = ++counter;
      r = r + q * 65536;
      assert(counter == 5);
      assert(r == 339968);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.compoundAssignOnLocal` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — the upstream chain verbatim, with the
compound assignment `r += a++ * 0x10` on a local instead of the bound-step rewrite
used by [incDecChainOnLocal]. -/
theorem compoundAssignOnLocal :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint a = 6;
      uint r = a;
      r += a * 16;
      assert(r == 102);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.bareIncrementOnLocal` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — a bare `a++;` statement, the increment form
the upstream loops use. -/
theorem bareIncrementOnLocal :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint a = 6;
      a++;
      assert(a == 7);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.bareIncrementOnStateVariable` (`solc/SolcExpressions.sol`).

solc: expressions/inc_dec_operators.sol — the same statement on a state variable. -/
theorem bareIncrementOnStateVariable :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      counter = 6;
      counter++;
      assert(counter == 7);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryTrueLiteral` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_true_literal.sol — `true ? 5 : 10` is 5. -/
theorem ternaryTrueLiteral :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint r = true ? 5 : 10;
      assert(r == 5);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryFalseLiteral` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_false_literal.sol — `false ? 5 : 10` is 10. -/
theorem ternaryFalseLiteral :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint r = false ? 5 : 10;
      assert(r == 10);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryNestedOuterHigh` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_multiple.sol — the nested
`x > 100 ? x > 1000 ? 1000 : 100 : x > 50 ? 50 : 10`, upstream case `f(1001) -> 1000`.

concretized: solkey proves this for all parameters; ported at x = 1001.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem ternaryNestedOuterHigh :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint x = 1001;
      uint d = x > 100 ? (x > 1000 ? 1000 : 100) : (x > 50 ? 50 : 10);
      assert(d == 1000);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryNestedOuterLow` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(500) -> 100`.

concretized: solkey proves this for all parameters; ported at x = 500.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem ternaryNestedOuterLow :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint x = 500;
      uint d = x > 100 ? (x > 1000 ? 1000 : 100) : (x > 50 ? 50 : 10);
      assert(d == 100);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryNestedInnerHigh` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(80) -> 50`.

concretized: solkey proves this for all parameters; ported at x = 80.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem ternaryNestedInnerHigh :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint x = 80;
      uint d = x > 100 ? (x > 1000 ? 1000 : 100) : (x > 50 ? 50 : 10);
      assert(d == 50);
    } := by
  corpus_decide solcExpressionsStore_eq

/-- solkey `SolcExpressions.ternaryNestedInnerLow` (`solc/SolcExpressions.sol`).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(40) -> 10`.

concretized: solkey proves this for all parameters; ported at x = 40.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem ternaryNestedInnerLow :
    Diamond State.solcExpressionsStore
    sol[SolcExpressions]{
      uint x = 40;
      uint d = x > 100 ? (x > 1000 ? 1000 : 100) : (x > 50 ? 50 : 10);
      assert(d == 10);
    } := by
  corpus_decide solcExpressionsStore_eq

end Solidity.Corpus.SolcExpressions
