import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcStructs.sol`, ported

solkey `1b4341a303`: 11 functions — 5 proved, 3 unsupported, 3 evaluated.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcStructs

open Semantics

/-- solkey `SolcStructs.deleteMemberThroughStorageAlias` (`solc/SolcStructs.sol`).

solc: structs/struct_delete_member.sol — `T storage x = data1;` does not copy: writing
and then deleting through `x` is observable on `data1`. -/
theorem deleteMemberThroughStorageAlias :
    Diamond State.solcStructsStore
    sol[SolcStructs]{
      data1.value = 2;
      Simple storage x = data1;
      x.value = 4;
      delete x.value;
      assert(data1.value == 0);
    } := by
  corpus_decide solcStructsStore_eq

/-- solkey `SolcStructs.deleteStructLeavesNeighbours` (`solc/SolcStructs.sol`).

solc: structs/struct_delete_storage.sol — `delete s` resets every member of the struct
and leaves the neighbouring state variables alone. -/
theorem deleteStructLeavesNeighbours :
    Diamond State.solcStructsStore
    sol[SolcStructs]{
      neighbourBefore = 23;
      neighbourAfter = 17;
      triple.x = 42;
      triple.y = 42;
      triple.z = 42;
      delete triple;
      assert(triple.x == 0);
      assert(triple.y == 0);
      assert(triple.z == 0);
      assert(neighbourBefore == 23);
      assert(neighbourAfter == 17);
    } := by
  corpus_decide solcStructsStore_eq

/-- solkey `SolcStructs.deleteStructInMapping` (`solc/SolcStructs.sol`).

solc: structs/struct_delete_struct_in_mapping.sol — `delete m[k]` resets the whole
entry. -/
theorem deleteStructInMapping :
    Diamond State.solcStructsStore
    sol[SolcStructs]{
      campaigns[0].value = 2;
      delete campaigns[0];
      assert(campaigns[0].value == 0);
    } := by
  corpus_decide solcStructsStore_eq

/-- solkey `SolcStructs.deleteEntryKeepsOtherKeys` (`solc/SolcStructs.sol`).

solc: structs/struct_delete_struct_in_mapping.sol — the entry next to the deleted one
is untouched. -/
theorem deleteEntryKeepsOtherKeys :
    Diamond State.solcStructsStore
    sol[SolcStructs]{
      campaigns[0].value = 2;
      campaigns[1].value = 3;
      delete campaigns[0];
      assert(campaigns[0].value == 0);
      assert(campaigns[1].value == 3);
    } := by
  corpus_decide solcStructsStore_eq

/-! solkey `SolcStructs.structCopyViaMemoryLocal` (`solc/SolcStructs.sol`).

solc: structs/struct_copy_via_local.sol — a storage struct copied out to memory and
back into another storage struct keeps every member.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcStructsStore
  sol[SolcStructs]{
    source.a = 1;
    source.b = 2;
    Pair memory x = source;
    target = x;
    assert(target.a == 1);
    assert(target.b == 2);
  }

/-- solkey `SolcStructs.structCopyFromStorageIsDeep` (`solc/SolcStructs.sol`).

solc: structs/copy_from_storage.sol — the storage source is copied, not aliased: a
later write to the source does not reach the copy. -/
theorem structCopyFromStorageIsDeep :
    Diamond State.solcStructsStore
    sol[SolcStructs]{
      source.a = 13;
      source.b = 14;
      target = source;
      source.a = 20;
      source.b = 21;
      assert(target.a == 13);
      assert(target.b == 14);
    } := by
  corpus_decide solcStructsStore_eq

/-! solkey `SolcStructs.structArrayElementCopy` (`solc/SolcStructs.sol`).

solc: array/copying/array_copy_storage_storage_struct.sol — the element-wise form of
the upstream whole-array copy `data2 = data1;` (which has no terminal rule yet).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcStructsStore
  sol[SolcStructs]{
    pairs1.push();
    pairs2.push();
    pairs1[0].a = 4;
    pairs1[0].b = 5;
    Pair storage src = pairs1[0];
    pairs2[0] = src;
    assert(pairs2[0].a == 4);
    assert(pairs2[0].b == 5);
  }

/-! solkey `SolcStructs.structArrayElementCopyMemberwise` (`solc/SolcStructs.sol`).

solc: array/copying/array_copy_storage_storage_struct.sol — the same copy performed
member by member through two element aliases.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcStructsStore
  sol[SolcStructs]{
    pairs1.push();
    pairs2.push();
    pairs1[0].a = 4;
    pairs1[0].b = 5;
    Pair storage src = pairs1[0];
    Pair storage dst = pairs2[0];
    dst.a = src.a;
    dst.b = src.b;
    assert(pairs2[0].a == 4);
    assert(pairs2[0].b == 5);
  }

end Solidity.Corpus.SolcStructs
