import Solidity.Corpus.Basic

/-!
# solkey `solc/SolcMappings.sol`, ported

solkey `f2eb3d98eb`: 9 functions — 7 proved, 1 evaluated, 1 unsupported.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.SolcMappings

open Semantics

set_option maxHeartbeats 8000000

/-- solkey `SolcMappings.structStorageToMappingEntry` (`solc/SolcMappings.sol`).

solc: structs/struct_storage_to_mapping.sol — `m[1] = s;` copies the storage struct into
the mapping entry. -/
theorem structStorageToMappingEntry :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      sBox.a = 12;
      sMap[1] = sBox;
      assert(sMap[1].a == 12);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.mappingEntryToStorageStruct` (`solc/SolcMappings.sol`).

solc: structs/copy_from_mapping.sol — the copy out of a mapping entry into a state
struct. -/
theorem mappingEntryToStorageStruct :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      sMap[1].a = 7;
      sBox = sMap[1];
      assert(sBox.a == 7);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.mappingEntryCopyIsDeep` (`solc/SolcMappings.sol`).

solc: structs/struct_storage_to_mapping.sol — the copy is deep: writing the source
afterwards does not reach the entry. -/
theorem mappingEntryCopyIsDeep :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      sBox.a = 12;
      sMap[1] = sBox;
      sBox.a = 13;
      assert(sMap[1].a == 12);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.copySubstructureIntoMapping` (`solc/SolcMappings.sol`).

solc: structs/copy_substructures_to_mapping.sol — a struct with a nested struct copied
into a mapping entry keeps both levels. -/
theorem copySubstructureIntoMapping :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      withSub.a = 1;
      withSub.sub.x = 2;
      withSub.sub.y = 3;
      withSubMap[5] = withSub;
      assert(withSubMap[5].a == 1);
      assert(withSubMap[5].sub.x == 2);
      assert(withSubMap[5].sub.y == 3);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.copySubstructureFromMapping` (`solc/SolcMappings.sol`).

solc: structs/copy_substructures_from_mapping.sol — and back out again. -/
theorem copySubstructureFromMapping :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      withSubMap[5].a = 1;
      withSubMap[5].sub.x = 2;
      withSub = withSubMap[5];
      assert(withSub.a == 1);
      assert(withSub.sub.x == 2);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.mappingKeysAreIndependent` (`solc/SolcMappings.sol`).

solc: structs/struct_delete_struct_in_mapping.sol — distinct keys are independent. -/
theorem mappingKeysAreIndependent :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      balances[1] = 10;
      balances[2] = 20;
      delete balances[1];
      assert(balances[1] == 0);
      assert(balances[2] == 20);
    } := by
  corpus_decide solcMappingsStore_eq

/-- solkey `SolcMappings.deleteStructKeepsMappingMember` (`solc/SolcMappings.sol`).

No upstream twin — the Solidity language rule that `delete` on a struct resets its
value members but leaves its mapping members alone (solc has no semantic test for it
because the result is not observable through its return-value harness). This is what
SolKey's lazy `delNode` marker implements. -/
theorem deleteStructKeepsMappingMember :
    Diamond State.solcMappingsStore
    sol[SolcMappings]{
      ledger.nonce = 5;
      ledger.balances[1] = 10;
      delete ledger;
      assert(ledger.nonce == 0);
      assert(ledger.balances[1] == 10);
    } := by
  corpus_decide solcMappingsStore_eq

/-! solkey `SolcMappings.arrayElementsToMapping` (`solc/SolcMappings.sol`).

solc: array/copying/array_elements_to_mapping.sol — the upstream `m[0] = s[0];` copies a
whole array into a mapping entry.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.solcMappingsStore
  sol[SolcMappings]{
    rows.push();
    rows[0].push(0);
    rows[0].push(0);
    rows[0][0] = 10;
    rows[0][1] = 11;
    uint[] storage row = rows[0];
    arrayMap[0] = row;
    assert(arrayMap[0][0] == 10);
    assert(arrayMap[0][1] == 11);
  }

end Solidity.Corpus.SolcMappings
