import Solidity.Corpus.Basic

/-!
# solkey `TestSuite.sol`, ported

solkey `f2eb3d98eb`: 413 functions — 186 proved, 176 unsupported, 51 evaluated.

Generated by `scripts/solkey-port.mjs`; do not edit by hand. Each
function is `Diamond σ sol[C]{ body }`, solkey's `⟨ f() ⟩ true` at the
contract's initial store (`Corpus/Basic.lean` says why this form):
a theorem where the kernel decides it, an `#eval` pin where it stops
at a well-founded definition or the run does not end normally.  The
functions with no obligation, and why, are the `unsupported` rows of
`tests/solkey/expected.tsv`; `docs/corpus-parity.md` is the scoreboard.
-/

namespace Solidity.Corpus.TestSuite

open Semantics

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.additionStorageWrite` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 5, y = 7.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem additionStorageWrite :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      uint y = 7;
      alice.age = x + y;
      uint r = alice.age;
      assert(r == 12);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootReadWrite` (`TestSuite.sol`). -/
theorem storageRootReadWrite :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 34;
      uint r = age;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldWriteRead` (`TestSuite.sol`). -/
theorem storageFieldWriteRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 34;
      uint r = alice.age;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepAddAssign` (`TestSuite.sol`). -/
theorem storageFieldDeepAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 30;
      alice.account.balance += 4;
      uint r = alice.account.balance;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldGlobalAge` (`TestSuite.sol`). -/
theorem storageFieldGlobalAge :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 34;
      assert(alice.age == 34);
      uint r = alice.age;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageAliasWrite` (`TestSuite.sol`). -/
theorem storageAliasWrite :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Person storage p = alice;
      Account storage acc = p.account;
      acc.balance = 100;
      p.account.token.value = 3;
      assert(alice.account.balance == 100);
      assert(alice.account.token.value == 3);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexRootMapping` (`TestSuite.sol`). -/
theorem storageIndexRootMapping :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 42;
      uint r = balances[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexAddAssign` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      values[1] += 2;
      uint r = values[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingAddAssign` (`TestSuite.sol`). -/
theorem storageIndexMappingAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      balances[1] += 2;
      uint r = balances[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.storageIndexReadComplexReceiverBindLocalRoot` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    bucket.tokens.push();
    bucket.tokens[0].value = 9;
    Token storage t = bucket.tokens[0];
    uint r = t.value;
    assert(r == 9);
  }

/-! solkey `TestSuite.storageIndexWriteComplexReceiverCopySource` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    bucket.tokens.push();
    alice.account.token.value = 7;
    Token storage tokRef = alice.account.token;
    bucket.tokens[0] = tokRef;
    uint r = bucket.tokens[0].value;
    assert(r == 7);
  }

/-- solkey `TestSuite.storageFieldWriteRootRhsComplexReceiver` (`TestSuite.sol`). -/
theorem storageFieldWriteRootRhsComplexReceiver :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      tok.value = 7;
      alice.account.token = tok;
      uint r = alice.account.token.value;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexWriteRootRhsComplexReceiver` (`TestSuite.sol`). -/
theorem storageIndexWriteRootRhsComplexReceiver :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      total = 9;
      ledger.balances[3] = total;
      uint r = ledger.balances[3];
      assert(r == 9);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.storagePushComplexReceiverNonsimpleArg` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 40, y = 2.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    matrix.push();
    uint x = 40;
    uint y = 2;
    matrix[0].push(x + y);
    uint r = matrix[0][0];
    assert(r == 42);
  }

/-- solkey `TestSuite.storagePushValueCopySource` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storagePushValueCopySource :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      tok.value = 7;
      tokens.push(tok);
      assert(tokens[0].value == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.requireTrueLiteral` (`TestSuite.sol`). -/
theorem requireTrueLiteral :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      require(true);
      assert(true);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolRootReadWrite` (`TestSuite.sol`). -/
theorem storageBoolRootReadWrite :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      flag = true;
      bool r = flag;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolRootCopy` (`TestSuite.sol`). -/
theorem storageBoolRootCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      flag = true;
      flag2 = flag;
      bool r = flag2;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolFieldRead` (`TestSuite.sol`). -/
theorem storageBoolFieldRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      toggle.on = true;
      bool r = toggle.on;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolMappingRead` (`TestSuite.sol`). -/
theorem storageBoolMappingRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      flags[2] = true;
      bool r = flags[2];
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolArrayRead` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageBoolArrayRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      boolFlags.push(false);
      boolFlags[0] = true;
      bool r = boolFlags[0];
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageBoolFieldStoreRoot` (`TestSuite.sol`). -/
theorem storageBoolFieldStoreRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      toggle.on = true;
      flag = toggle.on;
      bool r = flag;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.memoryDeclDefault` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    uint r = carol.age;
    assert(r == 0);
  }

/-- solkey `TestSuite.additionBothStorage` (`TestSuite.sol`). -/
theorem additionBothStorage :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 10;
      bob.age = 5;
      uint r = alice.age + bob.age;
      assert(r == 15);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.additionSimple` (`TestSuite.sol`). -/
theorem additionSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 1 + 2;
      assert(r == 3);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.additionStorageRead` (`TestSuite.sol`). -/
theorem additionStorageRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 10;
      uint r = alice.age + 1;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.divisionSimple` (`TestSuite.sol`). -/
theorem divisionSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 8 / 2;
      assert(r == 4);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.greaterEqualSimple` (`TestSuite.sol`). -/
theorem greaterEqualSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = 5 >= 6;
      assert(!r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.greaterThanSimple` (`TestSuite.sol`). -/
theorem greaterThanSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = 5 > 3;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.lessEqualSimple` (`TestSuite.sol`). -/
theorem lessEqualSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = 5 <= 5;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.lessThanSimple` (`TestSuite.sol`). -/
theorem lessThanSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = 3 < 5;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalAndSimple` (`TestSuite.sol`). -/
theorem logicalAndSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = true && false;
      assert(!r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalAndShortCircuitRhs` (`TestSuite.sol`). -/
theorem logicalAndShortCircuitRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      bool r = x == 5 && x + 1 == 6;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalNotSimple` (`TestSuite.sol`). -/
theorem logicalNotSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = !false;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalOrSimple` (`TestSuite.sol`). -/
theorem logicalOrSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = true || false;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalOrShortCircuitRhs` (`TestSuite.sol`). -/
theorem logicalOrShortCircuitRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      bool r = x == 4 || x + 1 == 6;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ternaryCaptureCond` (`TestSuite.sol`). -/
theorem ternaryCaptureCond :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      uint r = x == 5 ? x + 1 : 0;
      assert(r == 6);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ternaryToIf` (`TestSuite.sol`). -/
theorem ternaryToIf :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = true;
      uint r = b ? 1 : 2;
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifUnfold` (`TestSuite.sol`). -/
theorem ifUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      uint r = 0;
      if (x == 4) { r = 1; };
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifElseUnfold` (`TestSuite.sol`). -/
theorem ifElseUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      uint r = 0;
      if (x == 5) { r = 1; } else { r = 2; };
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifSplit` (`TestSuite.sol`). -/
theorem ifSplit :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = true;
      uint r = 0;
      if (b) { r = 1; };
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifElseSplit` (`TestSuite.sol`). -/
theorem ifElseSplit :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = false;
      uint r = 0;
      if (b) { r = 1; } else { r = 2; };
      assert(r == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifTrue` (`TestSuite.sol`). -/
theorem ifTrue :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 0;
      if (true) { r = 1; };
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifFalse` (`TestSuite.sol`). -/
theorem ifFalse :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 0;
      if (false) { r = 1; };
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifElseTrue` (`TestSuite.sol`). -/
theorem ifElseTrue :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 0;
      if (true) { r = 1; } else { r = 2; };
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifElseFalse` (`TestSuite.sol`). -/
theorem ifElseFalse :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 0;
      if (false) { r = 1; } else { r = 2; };
      assert(r == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ifElseNegated` (`TestSuite.sol`). -/
theorem ifElseNegated :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = false;
      uint r = 0;
      if (!b) { r = 1; } else { r = 2; };
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.memoryDeclFresh` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
  }

/-! solkey `TestSuite.memoryDeepField` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 10;
    uint r = carol.account.balance;
    assert(r == 10);
  }

/-! solkey `TestSuite.memoryFieldAddAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age += 4;
    uint r = carol.age;
    assert(r == 34);
  }

/-! solkey `TestSuite.memoryFieldSubAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age -= 4;
    uint r = carol.age;
    assert(r == 26);
  }

/-! solkey `TestSuite.memoryFieldMulAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 7;
    carol.age *= 4;
    uint r = carol.age;
    assert(r == 28);
  }

/-! solkey `TestSuite.memoryFieldDivAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age /= 5;
    uint r = carol.age;
    assert(r == 6);
  }

/-! solkey `TestSuite.memoryFieldModAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age %= 7;
    uint r = carol.age;
    assert(r == 2);
  }

/-! solkey `TestSuite.memoryFieldAddAssignUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 20;
    carol.account.balance += 4;
    uint r = carol.account.balance;
    assert(r == 24);
  }

/-! solkey `TestSuite.memoryFieldAddAssignNse` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age += 2 * 3;
    uint r = carol.age;
    assert(r == 36);
  }

/-! solkey `TestSuite.memoryFieldPreincrement` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    ++carol.age;
    uint r = carol.age;
    assert(r == 31);
  }

/-! solkey `TestSuite.memoryFieldPostincrement` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    carol.age++;
    uint r = carol.age;
    assert(r == 31);
  }

/-! solkey `TestSuite.memoryFieldPreincrementAssignment` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    uint r;
    r = ++carol.age;
    assert(r == 31);
    assert(carol.age == 31);
  }

/-! solkey `TestSuite.memoryFieldPostincrementAssignment` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 30;
    uint r;
    r = carol.age++;
    assert(r == 30);
    assert(carol.age == 31);
  }

/-! solkey `TestSuite.memoryFieldPreincrementUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 20;
    ++carol.account.balance;
    uint r = carol.account.balance;
    assert(r == 21);
  }

/-! solkey `TestSuite.memoryFieldAlias` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Account memory acc = carol.account;
    acc.balance = 100;
    uint r = carol.account.balance;
    assert(r == 100);
  }

/-! solkey `TestSuite.memoryFieldReferenceAssign` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Person memory david;
    Account memory pv = david.account;
    carol.account = pv;
    carol.account.balance = 60;
    uint r = david.account.balance;
    assert(r == 60);
  }

/-! solkey `TestSuite.memoryRootAlias` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Person memory david;
    david.age = 40;
    carol = david;
    carol.age = 41;
    uint r = david.age;
    assert(r == 41);
  }

/-! solkey `TestSuite.memoryToStorage` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 44;
    alice = carol;
    uint r = alice.age;
    assert(r == 44);
  }

/-! solkey `TestSuite.memoryToStorageIndexMappingCopyRootExample` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 6;
    folks[1] = carol;
    uint r = folks[1].age;
    assert(r == 6);
  }

/-! solkey `TestSuite.memoryToStorageIndexArrayCopyRootExample` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    persons.push();
    Person memory carol;
    carol.age = 6;
    persons[0] = carol;
    uint r = persons[0].age;
    assert(r == 6);
  }

/-- solkey `TestSuite.moduloSimple` (`TestSuite.sol`). -/
theorem moduloSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 7 % 3;
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.multiplicationSimple` (`TestSuite.sol`). -/
theorem multiplicationSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 3 * 4;
      assert(r == 12);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.notEqualSimple` (`TestSuite.sol`). -/
theorem notEqualSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool r = 3 != 4;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.requireGuardBox` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 1.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem requireGuardBox :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 1;
      age = 1;
      uint r = age;
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.requireHoldsDiamond` (`TestSuite.sol`). -/
theorem requireHoldsDiamond :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      require(x > 0);
      total = x;
      uint r = total;
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageAliasRebindAlias` (`TestSuite.sol`). -/
theorem storageAliasRebindAlias :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Person storage alicePath = alice;
      bob.age = 20;
      alicePath = bob;
      uint r = alicePath.age;
      assert(r == 20);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageDeepFieldPostincrement` (`TestSuite.sol`). -/
theorem storageDeepFieldPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 100;
      alice.account.balance++;
      uint r = alice.account.balance;
      assert(r == 101);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageDeepFieldPreincrement` (`TestSuite.sol`). -/
theorem storageDeepFieldPreincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 100;
      ++alice.account.balance;
      uint r = alice.account.balance;
      assert(r == 101);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldAddAssign` (`TestSuite.sol`). -/
theorem storageFieldAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      alice.age += 4;
      uint r = alice.age;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldCopyStruct` (`TestSuite.sol`). -/
theorem storageFieldCopyStruct :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.account.balance = 11;
      Account storage acc = bob.account;
      alice.account = acc;
      uint r = alice.account.balance;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldCopyValueField` (`TestSuite.sol`). -/
theorem storageFieldCopyValueField :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.age = 30;
      alice.age = bob.age;
      uint r = alice.age;
      assert(r == 30);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepDivAssign` (`TestSuite.sol`). -/
theorem storageFieldDeepDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 36;
      alice.account.balance /= 4;
      uint r = alice.account.balance;
      assert(r == 9);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepModAssign` (`TestSuite.sol`). -/
theorem storageFieldDeepModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 37;
      alice.account.balance %= 4;
      uint r = alice.account.balance;
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepMulAssign` (`TestSuite.sol`). -/
theorem storageFieldDeepMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 8;
      alice.account.balance *= 3;
      uint r = alice.account.balance;
      assert(r == 24);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepSubAssign` (`TestSuite.sol`). -/
theorem storageFieldDeepSubAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 30;
      alice.account.balance -= 4;
      uint r = alice.account.balance;
      assert(r == 26);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepWriteRead` (`TestSuite.sol`). -/
theorem storageFieldDeepWriteRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 34;
      uint r = alice.account.balance;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDelete` (`TestSuite.sol`). -/
theorem storageFieldDelete :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      delete alice.age;
      uint r = alice.age;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeleteThenCopy` (`TestSuite.sol`). -/
theorem storageFieldDeleteThenCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.account.balance = 10;
      delete bob.account;
      alice.account = bob.account;
      uint r = alice.account.balance;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeleteThenCopyDeep` (`TestSuite.sol`). -/
theorem storageFieldDeleteThenCopyDeep :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.account.token.value = 7;
      delete bob.account;
      alice.account = bob.account;
      uint r = alice.account.token.value;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDivAssign` (`TestSuite.sol`). -/
theorem storageFieldDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      alice.age /= 5;
      uint r = alice.age;
      assert(r == 6);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldModAssign` (`TestSuite.sol`). -/
theorem storageFieldModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      alice.age %= 7;
      uint r = alice.age;
      assert(r == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldMulAssign` (`TestSuite.sol`). -/
theorem storageFieldMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 7;
      alice.age *= 4;
      uint r = alice.age;
      assert(r == 28);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldPostincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageFieldPostincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      uint r;
      r = alice.age++;
      assert(r == 30);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldPostincrement` (`TestSuite.sol`). -/
theorem storageFieldPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      alice.age++;
      uint r = alice.age;
      assert(r == 31);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldPreincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageFieldPreincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      uint r;
      r = ++alice.age;
      assert(r == 31);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldPreincrement` (`TestSuite.sol`). -/
theorem storageFieldPreincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      ++alice.age;
      uint r = alice.age;
      assert(r == 31);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldReadBindLocal` (`TestSuite.sol`). -/
theorem storageFieldReadBindLocal :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Account storage acc = alice.account;
      bob.account.balance = 42;
      acc = bob.account;
      uint r = acc.balance;
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldReadStoreRoot` (`TestSuite.sol`). -/
theorem storageFieldReadStoreRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 17;
      total = alice.age;
      uint r = total;
      assert(r == 17);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldSubAssign` (`TestSuite.sol`). -/
theorem storageFieldSubAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      alice.age -= 5;
      uint r = alice.age;
      assert(r == 25);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldWriteCaptureSrc` (`TestSuite.sol`). -/
theorem storageFieldWriteCaptureSrc :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.account.balance = 11;
      alice.account = bob.account;
      uint r = alice.account.balance;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldWriteRhsCapture` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageFieldWriteRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 1;
      uint y = 2;
      uint z = 3;
      alice.age = x + y*z;
      uint r = alice.age;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexCopyValue` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at i = 5, j = 1.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexCopyValue :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      uint i = 5;
      uint j = 1;
      values[1] = 8;
      balances[i] = values[j];
      uint r = balances[5];
      assert(r == 8);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.storageIndexDecomposeAfterPush` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    matrix.push();
    matrix[0].push(100);
    matrix[0][0] = 7;
    uint r = matrix[0][0];
    assert(r == 7);
  }

/-- solkey `TestSuite.storageIndexDeleteMappingBool` (`TestSuite.sol`). -/
theorem storageIndexDeleteMappingBool :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      flags[1] = true;
      delete flags[1];
      bool r = flags[1];
      assert(!r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexDeleteMappingStruct` (`TestSuite.sol`). -/
theorem storageIndexDeleteMappingStruct :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      delete folks[1];
      assert(folks[1].age == 0);
      assert(folks[1].account.balance == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexDeleteNseIndex` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at k = 2.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexDeleteNseIndex :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint k = 2;
      balances[3] = 7;
      delete balances[k+1];
      uint r = balances[3];
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexDelete` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexDelete :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 7;
      delete values[1];
      uint r = values[1];
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexDivAssign` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      values[1] /= 8;
      uint r = values[1];
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexModAssign` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      values[1] %= 6;
      uint r = values[1];
      assert(r == 4);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMulAssign` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 5;
      values[1] *= 6;
      uint r = values[1];
      assert(r == 30);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMultipleWrites` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexMultipleWrites :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values.push(0);
      values.push(0);
      values[3] = 5;
      values[3] = 8;
      uint r = values[3];
      assert(r == 8);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPostincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexPostincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      uint r;
      r = values[1]++;
      assert(r == 40);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPostincrement` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      values[1]++;
      uint r = values[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPreincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexPreincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      uint r;
      r = ++values[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPreincrement` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexPreincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      ++values[1];
      uint r = values[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexReadMappingStoreRoot` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at k = 1.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexReadMappingStoreRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint k = 1;
      balances[1] = 42;
      total = balances[k];
      uint r = total;
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexReadNseIndex` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at i = 1.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexReadNseIndex :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values.push(0);
      uint i = 1;
      values[2] = 9;
      uint r = values[i+1];
      assert(r == 9);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexSubAssign` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexSubAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      values[1] -= 8;
      uint r = values[1];
      assert(r == 32);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexWriteNseChain` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at i = 2, x = 3, y = 4.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexWriteNseChain :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint i = 2;
      uint x = 3;
      uint y = 4;
      balances[i+1] = x*y + 3;
      uint r = balances[3];
      assert(r == 15);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageLocalDeclSkip` (`TestSuite.sol`). -/
theorem storageLocalDeclSkip :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Person storage p;
      age = 7;
      uint r = age;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.storageMatrixNseIndex` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at i = 1, j = 2, x = 5, y = 6.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    uint i = 1;
    uint j = 2;
    uint x = 5;
    uint y = 6;
    matrix[i+1][j+1] = x + y;
    assert(matrix[2][3] == 11);
  }

/-! solkey `TestSuite.storageMatrixWriteRead` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2][3] = 99;
    uint r = matrix[2][3];
    assert(r == 99);
  }

/-- solkey `TestSuite.storagePopUnknownLength` (`TestSuite.sol`). -/
theorem storagePopUnknownLength :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push();
      values.pop();
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootAddAssign` (`TestSuite.sol`). -/
theorem storageRootAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      age += 5;
      uint r = age;
      assert(r == 15);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootCopySource` (`TestSuite.sol`). -/
theorem storageRootCopySource :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 34;
      balance = age;
      uint r = balance;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootCopyStruct` (`TestSuite.sol`). -/
theorem storageRootCopyStruct :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.age = 7;
      alice = bob;
      uint r = alice.age;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootDeleteStruct` (`TestSuite.sol`). -/
theorem storageRootDeleteStruct :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 30;
      delete alice;
      uint r = alice.age;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootDeleteThenCopy` (`TestSuite.sol`). -/
theorem storageRootDeleteThenCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.age = 30;
      delete bob;
      alice = bob;
      uint r = alice.age;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootDelete` (`TestSuite.sol`). -/
theorem storageRootDelete :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      delete age;
      uint r = age;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootDisjoint` (`TestSuite.sol`). -/
theorem storageRootDisjoint :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 7;
      balance = 9;
      uint r = age;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootDivAssign` (`TestSuite.sol`). -/
theorem storageRootDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 20;
      age /= 4;
      uint r = age;
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootModAssign` (`TestSuite.sol`). -/
theorem storageRootModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 17;
      age %= 5;
      uint r = age;
      assert(r == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootMulAssign` (`TestSuite.sol`). -/
theorem storageRootMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 6;
      age *= 3;
      uint r = age;
      assert(r == 18);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootMultipleWrites` (`TestSuite.sol`). -/
theorem storageRootMultipleWrites :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 1;
      age = 2;
      uint r = age;
      assert(r == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootPostincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageRootPostincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      uint r;
      r = age++;
      assert(r == 10);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootPostincrement` (`TestSuite.sol`). -/
theorem storageRootPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      age++;
      uint r = age;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootPreincrementAssign` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageRootPreincrementAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      uint r;
      r = ++age;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootPreincrement` (`TestSuite.sol`). -/
theorem storageRootPreincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      ++age;
      uint r = age;
      assert(r == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootSubAssign` (`TestSuite.sol`). -/
theorem storageRootSubAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 10;
      age -= 4;
      uint r = age;
      assert(r == 6);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageRootWriteRhsCapture` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageRootWriteRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 1;
      uint y = 2;
      uint z = 3;
      total = x + y*z;
      uint r = total;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageToMemory` (`TestSuite.sol`). -/
theorem storageToMemory :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 27;
      Person memory carol = alice;
      alice.age = 30;
      uint r = carol.age;
      assert(r == 27);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.subtractionSimple` (`TestSuite.sol`). -/
theorem subtractionSimple :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint r = 7 - 2;
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.subtractionStorageRead` (`TestSuite.sol`). -/
theorem subtractionStorageRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 10;
      uint r = alice.age - 3;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.testDeepPopDoesNotResetMappingMember` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    ledgerUses.push();
    ledgerUses[0].ledger.balances[1] = 10;
    ledgerUses.pop();
    ledgerUses.push();
    assert(ledgerUses[0].ledger.balances[1] == 10);
  }

/-! solkey `TestSuite.testDeleteArrayDoesNotResetElementMappingMember` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    ledgerUses.push();
    ledgerUses[0].ledger.nonce = 3;
    ledgerUses[0].ledger.balances[1] = 10;
    delete ledgerUses;
    ledgerUses.push();
    assert(ledgerUses[0].ledger.nonce == 0);
    assert(ledgerUses[0].ledger.balances[1] == 10);
  }

/-! solkey `TestSuite.testMemoryAliasing` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Account memory carolAcc = carol.account;
    carolAcc.balance = 100;
    assert(carol.account.balance == 100);
  }

/-! solkey `TestSuite.testMemoryFieldShallowCopy` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Person memory david;
    david.account.balance = 50;
    carol.account = david.account;
    carol.account.balance = 60;
    assert(david.account.balance == 60);
    assert(carol.account.balance == 60);
  }

/-! solkey `TestSuite.testMemoryRootAlias` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Person memory david;
    david.age = 40;
    carol = david;
    carol.age = 41;
    assert(david.age == 41);
    assert(carol.age == 41);
  }

/-! solkey `TestSuite.testMemoryToStorageCopyComplexSource` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 50;
    alice.account = carol.account;
    carol.account.balance = 51;
    assert(alice.account.balance == 50);
  }

/-! solkey `TestSuite.testMemoryToStorageCopyComplexTarget` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Token memory carolToken;
    carolToken.value = 99;
    alice.account.token = carolToken;
    carolToken.value = 100;
    assert(alice.account.token.value == 99);
  }

/-! solkey `TestSuite.testMemoryToStorageCopyField` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Account memory carolAcc;
    carolAcc.balance = 50;
    alice.account = carolAcc;
    carolAcc.balance = 51;
    assert(alice.account.balance == 50);
  }

/-! solkey `TestSuite.testMemoryToStorageCopyRoot` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 42;
    alice = carol;
    carol.age = 43;
    assert(alice.age == 42);
  }

/-- solkey `TestSuite.testNestedStorageWrites` (`TestSuite.sol`). -/
theorem testNestedStorageWrites :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 10;
      alice.account.token.value = 5;
      uint b = alice.account.balance;
      uint v = alice.account.token.value;
      assert(b == 10);
      assert(v == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageAliases` (`TestSuite.sol`). -/
theorem testStorageAliases :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Person storage p = alice;
      Account storage acc = p.account;
      acc.balance = 100;
      p.account.token.value = 3;
      assert(alice.account.balance == 100);
      assert(alice.account.token.value == 3);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.testStorageArrayReadWrite` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    tokens.push();
    tokens[0].value = 100;
    uint v = tokens[0].value;
    assert(v == 100);
  }

/-- solkey `TestSuite.testStorageDeleteCase` (`TestSuite.sol`). -/
theorem testStorageDeleteCase :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 100;
      alice.account.token.value = 7;
      delete alice.account;
      uint b = alice.account.balance;
      uint v = alice.account.token.value;
      assert(b == 0);
      assert(v == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageFieldDeepCopy` (`TestSuite.sol`). -/
theorem testStorageFieldDeepCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.account.balance = 10;
      bob.account.token.value = 7;
      Account storage bobAcc = bob.account;
      alice.account = bobAcc;
      bob.account.balance = 20;
      bob.account.token.value = 9;
      assert(alice.account.balance == 10);
      assert(alice.account.token.value == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageMapReadWriteAndDelete` (`TestSuite.sol`). -/
theorem testStorageMapReadWriteAndDelete :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      valuesMap[1] = 10;
      valuesMap[2] = 20;
      uint v = valuesMap[1];
      uint kept = valuesMap[2];
      delete valuesMap[1];
      assert(v == 10);
      assert(kept == 20);
      assert(valuesMap[1] == 0);
      assert(valuesMap[2] == 20);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageMapStructCopy` (`TestSuite.sol`). -/
theorem testStorageMapStructCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      accountMap[1].balance = 10;
      accountMap[1].token.value = 7;
      accountMap[2] = accountMap[1];
      accountMap[1].balance = 20;
      accountMap[1].token.value = 9;
      assert(accountMap[2].balance == 10);
      assert(accountMap[2].token.value == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.testDanglingReferenceSurvivesPush` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    delete tokens;
    tokens.push();
    Token storage r = tokens[0];
    tokens.pop();
    r.value = 5;
    tokens.push();
    assert(tokens[0].value == 5);
  }

/-! solkey `TestSuite.testArrayCopyClearsOldElements` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    delete tokens;
    tokens.push();
    Token storage r = tokens[0];
    tokens.pop();
    r.value = 5;
    delete bucket.tokens;
    bucket.tokens.push();
    bucket.tokens[0].value = 7;
    bucket.tokens = tokens;
    bucket.tokens.push();
    assert(bucket.tokens[0].value == 0);
  }

/-! solkey `TestSuite.testArrayCopyKeepsDestinationTail` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    delete bucket.tokens;
    delete tokens;
    tokens.push();
    Token storage r = tokens[0];
    tokens.pop();
    r.value = 5;
    tokens = bucket.tokens;
    tokens.push();
    assert(tokens[0].value == 5);
  }

/-! solkey `TestSuite.testDeleteArrayLeavesDataPastLength` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    delete tokens;
    tokens.push();
    Token storage r = tokens[0];
    tokens.pop();
    r.value = 5;
    delete tokens;
    tokens.push();
    assert(tokens[0].value == 5);
  }

/-- solkey `TestSuite.testStorageRootDeepCopy` (`TestSuite.sol`). -/
theorem testStorageRootDeepCopy :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.age = 21;
      bob.account.balance = 11;
      alice = bob;
      bob.age = 30;
      bob.account.balance = 12;
      assert(alice.age == 21);
      assert(alice.account.balance == 11);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageStructDeleteSkipsMappingMember` (`TestSuite.sol`). -/
theorem testStorageStructDeleteSkipsMappingMember :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.nonce = 5;
      ledger.balances[1] = 10;
      ledger.balances[2] = 20;
      delete ledger;
      assert(ledger.nonce == 0);
      assert(ledger.balances[1] == 10);
      assert(ledger.balances[2] == 20);
      delete ledger.balances[1];
      assert(ledger.balances[1] == 0);
      assert(ledger.balances[2] == 20);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageToMemoryCopyComplexPath` (`TestSuite.sol`). -/
theorem testStorageToMemoryCopyComplexPath :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.token.value = 17;
      Token memory t = alice.account.token;
      alice.account.token.value = 18;
      assert(t.value == 17);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageToMemoryCopyField` (`TestSuite.sol`). -/
theorem testStorageToMemoryCopyField :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 10;
      Account memory acc = alice.account;
      alice.account.balance = 20;
      uint v = acc.balance;
      assert(v == 10);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageToMemoryCopyRoot` (`TestSuite.sol`). -/
theorem testStorageToMemoryCopyRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 25;
      Person memory carol = alice;
      alice.age = 30;
      uint v = carol.age;
      assert(v == 25);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testStorageWriteAndRead` (`TestSuite.sol`). -/
theorem testStorageWriteAndRead :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 20;
      uint y = 1;
      alice.age = x + y;
      uint v = alice.age;
      assert(v == 21);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDecomposition` (`TestSuite.sol`). -/
theorem storageFieldDecomposition :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 34;
      assert(alice.account.balance == 34);
      uint r = alice.account.balance;
      assert(r == 34);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDeepValue` (`TestSuite.sol`). -/
theorem storageFieldDeepValue :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.token.value = 7;
      assert(alice.account.token.value == 7);
      uint r = alice.account.token.value;
      assert(r == 7);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.storageIndexDecomposition` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    matrix.push();
    matrix.push();
    matrix.push();
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2].push(0);
    matrix[2][3] = 34;
    assert(matrix[2][3] == 34);
    uint r = matrix[2][3];
    assert(r == 34);
  }

/-- solkey `TestSuite.storageIndexRootArray` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexRootArray :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 42;
      assert(values[1] == 42);
      uint r = values[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDisjointFields` (`TestSuite.sol`). -/
theorem storageFieldDisjointFields :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 1;
      alice.account.token.value = 2;
      assert(alice.account.balance == 1);
      assert(alice.account.token.value == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageFieldDisjointRoots` (`TestSuite.sol`). -/
theorem storageFieldDisjointRoots :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.age = 1;
      bob.age = 2;
      assert(alice.age == 1);
      assert(bob.age == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageAliasRebindOriginal` (`TestSuite.sol`). -/
theorem storageAliasRebindOriginal :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint before = alice.age;
      Person storage alicePath = alice;
      bob.age = 20;
      alicePath = bob;
      assert(alice.age == before);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testSimpleAssert` (`TestSuite.sol`). -/
theorem testSimpleAssert :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 42;
      uint v = age;
      assert(v == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.localArithmeticInRange` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at x = 1.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem localArithmeticInRange :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 1;
      require(x <= 100);
      uint r;
      r = x + 1;
      r -= 1;
      ++r;
      assert(r == x + 1);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testCopyRootKeepsValueMembers` (`TestSuite.sol`). -/
theorem testCopyRootKeepsValueMembers :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bob.age = 7;
      bob.account.balance = 3;
      alice = bob;
      bob.age = 8;
      assert(alice.age == 7);
      assert(alice.account.balance == 3);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testCopyFieldNested` (`TestSuite.sol`). -/
theorem testCopyFieldNested :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      Account storage acc = bob.account;
      acc.token.value = 5;
      alice.account = acc;
      acc.token.value = 6;
      assert(alice.account.token.value == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.testCopyOfCopy` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert.

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    bob.age = 4;
    alice = bob;
    persons.push();
    persons[0] = alice;
    assert(persons[0].age == 4);
  }

/-- solkey `TestSuite.testCopyIntoMappingEntry` (`TestSuite.sol`).

concretized: solkey proves this for all parameters; ported at k = 3.

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem testCopyIntoMappingEntry :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint k = 3;
      alice.age = 6;
      folks[k] = alice;
      alice.age = 7;
      assert(folks[k].age == 6);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testCopyPrimitiveRoot` (`TestSuite.sol`). -/
theorem testCopyPrimitiveRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      age = 3;
      balance = age;
      age = 4;
      assert(balance == 3);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testCopyStoreRootFromField` (`TestSuite.sol`). -/
theorem testCopyStoreRootFromField :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.token.value = 2;
      tok = alice.account.token;
      alice.account.token.value = 1;
      assert(tok.value == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.testCopyStoreRootFromIndex` (`TestSuite.sol`). -/
theorem testCopyStoreRootFromIndex :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      folks[1].age = 2;
      alice = folks[1];
      folks[1].age = 3;
      assert(alice.age == 2);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.mappingReadAsKey` (`TestSuite.sol`). -/
theorem mappingReadAsKey :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 3;
      balances[3] = 9;
      uint r = balances[balances[1]];
      assert(r == 9);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.memoryFieldAsMappingKey` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.age = 3;
    balances[carol.age] = 7;
    uint r = balances[3];
    assert(r == 7);
  }

/-! solkey `TestSuite.mappingEntryThroughMemoryToMappingEntry` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    folks[1].age = 3;
    Person memory p = folks[1];
    folks[2] = p;
    folks[1].age = 4;
    uint r = folks[2].age;
    assert(r == 3);
  }

/-- solkey `TestSuite.localAddAssign` (`TestSuite.sol`). -/
theorem localAddAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      x += 2;
      assert(x == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.localMulAssign` (`TestSuite.sol`). -/
theorem localMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 7;
      x *= 6;
      assert(x == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.localDivAssign` (`TestSuite.sol`). -/
theorem localDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      x /= 8;
      assert(x == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.localModAssign` (`TestSuite.sol`). -/
theorem localModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      x %= 7;
      assert(x == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.localPostincrement` (`TestSuite.sol`). -/
theorem localPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      x++;
      assert(x == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.subAssignValueRhsCapture` (`TestSuite.sol`). -/
theorem subAssignValueRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 1;
      x -= y + 1;
      assert(x == 38);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.mulAssignValueRhsCapture` (`TestSuite.sol`). -/
theorem mulAssignValueRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 7;
      uint y = 5;
      x *= y + 1;
      assert(x == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.divAssignValueRhsCapture` (`TestSuite.sol`). -/
theorem divAssignValueRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 7;
      x /= y + 1;
      assert(x == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.modAssignValueRhsCapture` (`TestSuite.sol`). -/
theorem modAssignValueRhsCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 6;
      x %= y + 1;
      assert(x == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.boolInequalityCaptureLhs` (`TestSuite.sol`). -/
theorem boolInequalityCaptureLhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = true;
      bool r = !b != b;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.boolInequalityCaptureRhs` (`TestSuite.sol`). -/
theorem boolInequalityCaptureRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = true;
      bool r = b != !b;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.greaterThanCaptureRhs` (`TestSuite.sol`). -/
theorem greaterThanCaptureRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = x > x - 1;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.greaterEqualCaptureLhs` (`TestSuite.sol`). -/
theorem greaterEqualCaptureLhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = x + 1 >= x;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.greaterEqualCaptureRhs` (`TestSuite.sol`). -/
theorem greaterEqualCaptureRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = x >= x - 1;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.lessEqualCaptureLhs` (`TestSuite.sol`). -/
theorem lessEqualCaptureLhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = x - 1 <= x;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.lessEqualCaptureRhs` (`TestSuite.sol`). -/
theorem lessEqualCaptureRhs :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = x <= x + 1;
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.logicalNotCapture` (`TestSuite.sol`). -/
theorem logicalNotCapture :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 3;
      bool r = !(x == 4);
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.multiplicationUnfoldLeft` (`TestSuite.sol`). -/
theorem multiplicationUnfoldLeft :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 5;
      uint y = 7;
      uint r = (x + 1) * y;
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.multiplicationUnfoldRight` (`TestSuite.sol`). -/
theorem multiplicationUnfoldRight :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 7;
      uint y = 5;
      uint r = x * (y + 1);
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.divisionUnfoldLeft` (`TestSuite.sol`). -/
theorem divisionUnfoldLeft :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 39;
      uint y = 8;
      uint r = (x + 1) / y;
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.divisionUnfoldRight` (`TestSuite.sol`). -/
theorem divisionUnfoldRight :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 7;
      uint r = x / (y + 1);
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.moduloUnfoldLeft` (`TestSuite.sol`). -/
theorem moduloUnfoldLeft :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 39;
      uint y = 7;
      uint r = (x + 1) % y;
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.moduloUnfoldRight` (`TestSuite.sol`). -/
theorem moduloUnfoldRight :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 6;
      uint r = x % (y + 1);
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.subtractionUnfoldRight` (`TestSuite.sol`). -/
theorem subtractionUnfoldRight :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 40;
      uint y = 1;
      uint r = x - (y + 1);
      assert(r == 38);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.parenthesizedRightOperand` (`TestSuite.sol`). -/
theorem parenthesizedRightOperand :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 10;
      uint y = 5;
      uint z = 3;
      uint r = x - (y - z);
      assert(r == 8);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.parenthesizedLeftOperand` (`TestSuite.sol`). -/
theorem parenthesizedLeftOperand :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      uint x = 2;
      uint y = 3;
      uint z = 4;
      uint r = (x + y) * z;
      assert(r == 20);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.parenthesizedCondition` (`TestSuite.sol`). -/
theorem parenthesizedCondition :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool a = true;
      bool b = false;
      bool c = true;
      bool r = a && (b || c);
      assert(r);
    } := by
  corpus_decide testSuiteStore_eq

/-! solkey `TestSuite.memoryFieldSubAssignUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 20;
    carol.account.balance -= 4;
    uint r = carol.account.balance;
    assert(r == 16);
  }

/-! solkey `TestSuite.memoryFieldMulAssignUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 7;
    carol.account.balance *= 6;
    uint r = carol.account.balance;
    assert(r == 42);
  }

/-! solkey `TestSuite.memoryFieldDivAssignUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 40;
    carol.account.balance /= 8;
    uint r = carol.account.balance;
    assert(r == 5);
  }

/-! solkey `TestSuite.memoryFieldModAssignUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 40;
    carol.account.balance %= 7;
    uint r = carol.account.balance;
    assert(r == 5);
  }

/-! solkey `TestSuite.memoryFieldPostincrementUnfold` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    carol.account.balance = 20;
    carol.account.balance++;
    uint r = carol.account.balance;
    assert(r == 21);
  }

/-! solkey `TestSuite.memoryFieldReadUnfoldResult` (`TestSuite.sol`).

The kernel stops at a well-founded definition; the run is pinned instead. -/

/-- info: "ok" -/
#guard_msgs in
#eval outcome State.testSuiteStore
  sol[TestSuite]{
    Person memory carol;
    Person memory david;
    david.age = 40;
    carol.account.balance = david.age;
    uint r = carol.account.balance;
    assert(r == 40);
  }

/-- solkey `TestSuite.storageFieldDeleteUnfold` (`TestSuite.sol`). -/
theorem storageFieldDeleteUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      alice.account.balance = 20;
      delete alice.account.balance;
      uint r = alice.account.balance;
      assert(r == 0);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexAddAssignUnfold` (`TestSuite.sol`). -/
theorem storageIndexAddAssignUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ledger.balances[1] += 2;
      uint r = ledger.balances[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexSubAssignUnfold` (`TestSuite.sol`). -/
theorem storageIndexSubAssignUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ledger.balances[1] -= 2;
      uint r = ledger.balances[1];
      assert(r == 38);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMulAssignUnfold` (`TestSuite.sol`). -/
theorem storageIndexMulAssignUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 7;
      ledger.balances[1] *= 6;
      uint r = ledger.balances[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexDivAssignUnfold` (`TestSuite.sol`). -/
theorem storageIndexDivAssignUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ledger.balances[1] /= 8;
      uint r = ledger.balances[1];
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexModAssignUnfold` (`TestSuite.sol`). -/
theorem storageIndexModAssignUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ledger.balances[1] %= 7;
      uint r = ledger.balances[1];
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPreincrementUnfold` (`TestSuite.sol`). -/
theorem storageIndexPreincrementUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ++ledger.balances[1];
      uint r = ledger.balances[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexPostincrementUnfold` (`TestSuite.sol`). -/
theorem storageIndexPostincrementUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      ledger.balances[1] = 40;
      ledger.balances[1]++;
      uint r = ledger.balances[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingSubAssign` (`TestSuite.sol`). -/
theorem storageIndexMappingSubAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      balances[1] -= 2;
      uint r = balances[1];
      assert(r == 38);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingMulAssign` (`TestSuite.sol`). -/
theorem storageIndexMappingMulAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 7;
      balances[1] *= 6;
      uint r = balances[1];
      assert(r == 42);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingDivAssign` (`TestSuite.sol`). -/
theorem storageIndexMappingDivAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      balances[1] /= 8;
      uint r = balances[1];
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingModAssign` (`TestSuite.sol`). -/
theorem storageIndexMappingModAssign :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      balances[1] %= 7;
      uint r = balances[1];
      assert(r == 5);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingPreincrement` (`TestSuite.sol`). -/
theorem storageIndexMappingPreincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      ++balances[1];
      uint r = balances[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingPostincrement` (`TestSuite.sol`). -/
theorem storageIndexMappingPostincrement :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      balances[1]++;
      uint r = balances[1];
      assert(r == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingPreincrementAssignment` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageIndexMappingPreincrementAssignment :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      uint r;
      r = ++balances[1];
      assert(r == 41);
      assert(balances[1] == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexMappingPostincrementAssignment` (`TestSuite.sol`).

`T r = x++;` split into `T r; r = x++;`. -/
theorem storageIndexMappingPostincrementAssignment :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      balances[1] = 40;
      uint r;
      r = balances[1]++;
      assert(r == 40);
      assert(balances[1] == 41);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storageIndexReadArrayStoreRoot` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storageIndexReadArrayStoreRoot :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      values.push(0);
      values.push(0);
      values[1] = 40;
      age = values[1];
      uint r = age;
      assert(r == 40);
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.storagePopUnfold` (`TestSuite.sol`).

solkey tags this `@custom:key box`; the port makes its assumptions true
instead, so the diamond also proves that it does not revert. -/
theorem storagePopUnfold :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      basketA.items.push(0);
      basketA.items.pop();
    } := by
  corpus_decide testSuiteStore_eq

/-- solkey `TestSuite.ternaryToIfStorage` (`TestSuite.sol`). -/
theorem ternaryToIfStorage :
    Diamond State.testSuiteStore
    sol[TestSuite]{
      bool b = true;
      age = b ? 1 : 2;
      uint r = age;
      assert(r == 1);
    } := by
  corpus_decide testSuiteStore_eq

end Solidity.Corpus.TestSuite
