import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part05

Obligations 97-120 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.storageFieldMulAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldMulAssign from State.testSuiteStore
  { alice.age = 7;
    alice.age *= 4;
    uint r = alice.age;
    assert((r == 28)) }

/-- solkey `TestSuite.storageFieldPostdecrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPostdecrementAssign from State.testSuiteStore
  { alice.age = 30;
    uint r = postdec(alice.age);
    assert((r == 30)) }

/-- solkey `TestSuite.storageFieldPostdecrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPostdecrement from State.testSuiteStore
  { alice.age = 30;
    postdec(alice.age);
    uint r = alice.age;
    assert((r == 29)) }

/-- solkey `TestSuite.storageFieldPostincrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPostincrementAssign from State.testSuiteStore
  { alice.age = 30;
    uint r = alice.age++;
    assert((r == 30)) }

/-- solkey `TestSuite.storageFieldPostincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPostincrement from State.testSuiteStore
  { alice.age = 30;
    alice.age++;
    uint r = alice.age;
    assert((r == 31)) }

/-- solkey `TestSuite.storageFieldPredecrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPredecrementAssign from State.testSuiteStore
  { alice.age = 30;
    uint r = predec(alice.age);
    assert((r == 29)) }

/-- solkey `TestSuite.storageFieldPredecrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPredecrement from State.testSuiteStore
  { alice.age = 30;
    predec(alice.age);
    uint r = alice.age;
    assert((r == 29)) }

/-- solkey `TestSuite.storageFieldPreincrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPreincrementAssign from State.testSuiteStore
  { alice.age = 30;
    uint r = ++alice.age;
    assert((r == 31)) }

/-- solkey `TestSuite.storageFieldPreincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldPreincrement from State.testSuiteStore
  { alice.age = 30;
    ++alice.age;
    uint r = alice.age;
    assert((r == 31)) }

/-- solkey `TestSuite.storageFieldReadBindLocal` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldReadBindLocal from State.testSuiteStore
  { Account storage acc = alice.account;
    bob.account.balance = 42;
    acc@Account = bob.account;
    uint r = acc@Account.balance;
    assert((r == 42)) }

/-- solkey `TestSuite.storageFieldReadStoreRoot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldReadStoreRoot from State.testSuiteStore
  { alice.age = 17;
    total = alice.age;
    uint r = total;
    assert((r == 17)) }

/-- solkey `TestSuite.storageFieldSubAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldSubAssign from State.testSuiteStore
  { alice.age = 30;
    alice.age -= 5;
    uint r = alice.age;
    assert((r == 25)) }

/-- solkey `TestSuite.storageFieldWriteCaptureSrc` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldWriteCaptureSrc from State.testSuiteStore
  { bob.account.balance = 11;
    alice.account = bob.account;
    uint r = alice.account.balance;
    assert((r == 11)) }

/-- solkey `TestSuite.storageFieldWriteRhsCapture` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageFieldWriteRhsCapture from State.testSuiteStore
  { uint x = 1;
    uint y = 2;
    uint z = 3;
    alice.age = x + y*z;
    uint r = alice.age;
    assert((r == 7)) }

/-- solkey `TestSuite.storageIndexCopyValue` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at i = 5, j = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexCopyValue from State.testSuiteStore
  { values.push();
    values.push();
    uint i = 5;
    uint j = 1;
    values[1] = 8;
    balances[i] = values[j];
    uint r = balances[5];
    assert((r == 8)) }

/-- solkey `TestSuite.storageIndexCopysourceAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexCopysourceAfterPush from State.testSuiteStore
  { uint[][] storage m = matrix;
    m@uint[][].push();
    m@uint[][][0] = values;
    assert((matrix.length == 1)) }

/-- solkey `TestSuite.storageIndexDecomposeAfterPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexDecomposeAfterPush from State.testSuiteStore
  { matrix.push();
    matrix[0].push(100);
    matrix[0][0] = 7;
    uint r = matrix[0][0];
    assert((r == 7)) }

/-- solkey `TestSuite.storageIndexDeleteMappingBool` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageIndexDeleteMappingBool from State.testSuiteStore
  { flags[1] = true;
    delete flags[1];
    bool r = flags[1];
    assert(!r) }

/-- solkey `TestSuite.storageIndexDeleteMappingStruct` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageIndexDeleteMappingStruct from State.testSuiteStore
  { delete folks[1];
    assert((folks[1].age == 0));
    assert((folks[1].account.balance == 0)) }

/-- solkey `TestSuite.storageIndexDeleteNseIndex` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexDeleteNseIndex from State.testSuiteStore
  { uint k = 2;
    balances[3] = 7;
    delete balances[k+1];
    uint r = balances[3];
    assert((r == 0)) }

/-- solkey `TestSuite.storageIndexDelete` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexDelete from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 7;
    delete values[1];
    uint r = values[1];
    assert((r == 0)) }

/-- solkey `TestSuite.storageIndexDivAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexDivAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    values[1] /= 8;
    uint r = values[1];
    assert((r == 5)) }

/-- solkey `TestSuite.storageIndexModAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexModAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    values[1] %= 6;
    uint r = values[1];
    assert((r == 4)) }

/-- solkey `TestSuite.storageIndexMulAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexMulAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 5;
    values[1] *= 6;
    uint r = values[1];
    assert((r == 30)) }

end TestSuite
end Calculus
end Solidity
