import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part03

Obligations 49-72 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.ifElseNegated` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifElseNegated from State.testSuiteStore
  { bool b = false;
    uint r = 0;
    if (!b) { r = 1 } else { r = 2 };
    assert((r == 1)) }

/-- solkey `TestSuite.memoryDeclFresh` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryDeclFresh from State.testSuiteStore
  { Person memory mv }

/-- solkey `TestSuite.memoryDeepField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryDeepField from State.testSuiteStore
  { Person memory mv;
    mv@Person.account.balance = 10;
    uint r = mv@Person.account.balance;
    assert((r == 10)) }

/-- solkey `TestSuite.memoryFieldAddAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldAddAssign from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age += 4;
    uint r = mv@Person.age;
    assert((r == 34)) }

/-- solkey `TestSuite.memoryFieldSubAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldSubAssign from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age -= 4;
    uint r = mv@Person.age;
    assert((r == 26)) }

/-- solkey `TestSuite.memoryFieldMulAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldMulAssign from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 7;
    mv@Person.age *= 4;
    uint r = mv@Person.age;
    assert((r == 28)) }

/-- solkey `TestSuite.memoryFieldDivAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldDivAssign from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age /= 5;
    uint r = mv@Person.age;
    assert((r == 6)) }

/-- solkey `TestSuite.memoryFieldModAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldModAssign from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age %= 7;
    uint r = mv@Person.age;
    assert((r == 2)) }

/-- solkey `TestSuite.memoryFieldAddAssignUnfold` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldAddAssignUnfold from State.testSuiteStore
  { Person memory mv;
    mv@Person.account.balance = 20;
    mv@Person.account.balance += 4;
    uint r = mv@Person.account.balance;
    assert((r == 24)) }

/-- solkey `TestSuite.memoryFieldAddAssignNse` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldAddAssignNse from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age += 2 * 3;
    uint r = mv@Person.age;
    assert((r == 36)) }

/-- solkey `TestSuite.memoryFieldPreincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPreincrement from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    ++mv@Person.age;
    uint r = mv@Person.age;
    assert((r == 31)) }

/-- solkey `TestSuite.memoryFieldPostincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPostincrement from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    mv@Person.age++;
    uint r = mv@Person.age;
    assert((r == 31)) }

/-- solkey `TestSuite.memoryFieldPredecrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPredecrement from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    predec(mv@Person.age);
    uint r = mv@Person.age;
    assert((r == 29)) }

/-- solkey `TestSuite.memoryFieldPostdecrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPostdecrement from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    postdec(mv@Person.age);
    uint r = mv@Person.age;
    assert((r == 29)) }

/-- solkey `TestSuite.memoryFieldPreincrementAssignment` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPreincrementAssignment from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    uint r = ++mv@Person.age;
    assert((r == 31));
    assert((mv@Person.age == 31)) }

/-- solkey `TestSuite.memoryFieldPostincrementAssignment` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPostincrementAssignment from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    uint r = mv@Person.age++;
    assert((r == 30));
    assert((mv@Person.age == 31)) }

/-- solkey `TestSuite.memoryFieldPredecrementAssignment` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPredecrementAssignment from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    uint r = predec(mv@Person.age);
    assert((r == 29));
    assert((mv@Person.age == 29)) }

/-- solkey `TestSuite.memoryFieldPostdecrementAssignment` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPostdecrementAssignment from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 30;
    uint r = postdec(mv@Person.age);
    assert((r == 30));
    assert((mv@Person.age == 29)) }

/-- solkey `TestSuite.memoryFieldPreincrementUnfold` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldPreincrementUnfold from State.testSuiteStore
  { Person memory mv;
    mv@Person.account.balance = 20;
    ++mv@Person.account.balance;
    uint r = mv@Person.account.balance;
    assert((r == 21)) }

/-- solkey `TestSuite.memoryFieldAlias` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldAlias from State.testSuiteStore
  { Person memory mv;
    Account memory mv2 = mv@Person.account;
    mv2@Account.balance = 100;
    uint r = mv@Person.account.balance;
    assert((r == 100)) }

/-- solkey `TestSuite.memoryFieldReferenceAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryFieldReferenceAssign from State.testSuiteStore
  { Person memory mv;
    Person memory mv2;
    Account memory mv3 = mv2@Person.account;
    mv@Person.account = mv3@Account;
    mv@Person.account.balance = 60;
    uint r = mv2@Person.account.balance;
    assert((r == 60)) }

/-- solkey `TestSuite.memoryRootAlias` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryRootAlias from State.testSuiteStore
  { Person memory mv;
    Person memory mv2;
    mv2@Person.age = 40;
    mv@Person = mv2@Person;
    mv@Person.age = 41;
    uint r = mv2@Person.age;
    assert((r == 41)) }

/-- solkey `TestSuite.memoryRootDeleteFresh` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryRootDeleteFresh from State.testSuiteStore
  { Person memory mv;
    delete mv@Person }

/-- solkey `TestSuite.memoryToStorage` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryToStorage from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 44;
    alice = mv@Person;
    uint r = alice.age;
    assert((r == 44)) }

end TestSuite
end Calculus
end Solidity
