import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part02

Obligations 25-48 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.testStorageComplexReceiverEmptyPush` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageComplexReceiverEmptyPush from State.testSuiteStore
  { (bucket@@TokenBucket.tokens).push();
    TokenArray storage bt = bucket@@TokenBucket.tokens;
    assert((bt@TokenArray.length == 1)) }

/-- solkey `TestSuite.additionBothStorage` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionBothStorage from State.testSuiteStore
  { alice.age = 10;
    bob.age = 5;
    uint r = alice.age + bob.age;
    assert((r == 15)) }

/-- solkey `TestSuite.additionSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionSimple from State.testSuiteStore
  { uint r = 1 + 2;
    assert((r == 3)) }

/-- solkey `TestSuite.additionStorageRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionStorageRead from State.testSuiteStore
  { alice.age = 10;
    uint r = alice.age + 1;
    assert((r == 11)) }

/-- solkey `TestSuite.divisionSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_divisionSimple from State.testSuiteStore
  { uint r = 8 / 2;
    assert((r == 4)) }

/-- solkey `TestSuite.greaterEqualSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_greaterEqualSimple from State.testSuiteStore
  { bool r = (5 >= 6);
    assert(!r) }

/-- solkey `TestSuite.greaterThanSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_greaterThanSimple from State.testSuiteStore
  { bool r = (5 > 3);
    assert(r) }

/-- solkey `TestSuite.lessEqualSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_lessEqualSimple from State.testSuiteStore
  { bool r = (5 <= 5);
    assert(r) }

/-- solkey `TestSuite.lessThanSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_lessThanSimple from State.testSuiteStore
  { bool r = (3 < 5);
    assert(r) }

/-- solkey `TestSuite.logicalAndSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_logicalAndSimple from State.testSuiteStore
  { bool r = true && false;
    assert(!r) }

/-- solkey `TestSuite.logicalAndShortCircuitRhs` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_logicalAndShortCircuitRhs from State.testSuiteStore
  { uint x = 5;
    bool r = (x == 5) && (x + 1 == 6);
    assert(r) }

/-- solkey `TestSuite.logicalNotSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_logicalNotSimple from State.testSuiteStore
  { bool r = !false;
    assert(r) }

/-- solkey `TestSuite.logicalOrSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_logicalOrSimple from State.testSuiteStore
  { bool r = true || false;
    assert(r) }

/-- solkey `TestSuite.logicalOrShortCircuitRhs` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_logicalOrShortCircuitRhs from State.testSuiteStore
  { uint x = 5;
    bool r = (x == 4) || (x + 1 == 6);
    assert(r) }

/-- solkey `TestSuite.ternaryCaptureCond` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ternaryCaptureCond from State.testSuiteStore
  { uint x = 5;
    uint r = (x == 5) ? x + 1 : 0;
    assert((r == 6)) }

/-- solkey `TestSuite.ternaryToIf` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ternaryToIf from State.testSuiteStore
  { bool b = true;
    uint r = b ? 1 : 2;
    assert((r == 1)) }

/-- solkey `TestSuite.ifUnfold` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifUnfold from State.testSuiteStore
  { uint x = 5;
    uint r = 0;
    if ((x == 4)) { r = 1 };
    assert((r == 0)) }

/-- solkey `TestSuite.ifElseUnfold` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifElseUnfold from State.testSuiteStore
  { uint x = 5;
    uint r = 0;
    if ((x == 5)) { r = 1 } else { r = 2 };
    assert((r == 1)) }

/-- solkey `TestSuite.ifSplit` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifSplit from State.testSuiteStore
  { bool b = true;
    uint r = 0;
    if (b) { r = 1 };
    assert((r == 1)) }

/-- solkey `TestSuite.ifElseSplit` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifElseSplit from State.testSuiteStore
  { bool b = false;
    uint r = 0;
    if (b) { r = 1 } else { r = 2 };
    assert((r == 2)) }

/-- solkey `TestSuite.ifTrue` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifTrue from State.testSuiteStore
  { uint r = 0;
    if (true) { r = 1 };
    assert((r == 1)) }

/-- solkey `TestSuite.ifFalse` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifFalse from State.testSuiteStore
  { uint r = 0;
    if (false) { r = 1 };
    assert((r == 0)) }

/-- solkey `TestSuite.ifElseTrue` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifElseTrue from State.testSuiteStore
  { uint r = 0;
    if (true) { r = 1 } else { r = 2 };
    assert((r == 1)) }

/-- solkey `TestSuite.ifElseFalse` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_ifElseFalse from State.testSuiteStore
  { uint r = 0;
    if (false) { r = 1 } else { r = 2 };
    assert((r == 2)) }

end TestSuite
end Calculus
end Solidity
