import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part04

Obligations 73-96 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.memoryToStorageIndexMappingCopyRootExample` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryToStorageIndexMappingCopyRootExample from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 6;
    folks[1] = mv@Person;
    uint r = folks[1].age;
    assert((r == 6)) }

/-- solkey `TestSuite.memoryToStorageIndexArrayCopyRootExample` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_memoryToStorageIndexArrayCopyRootExample from State.testSuiteStore
  { persons.push();
    Person memory mv;
    mv@Person.age = 6;
    persons[0] = mv@Person;
    uint r = persons[0].age;
    assert((r == 6)) }

/-- solkey `TestSuite.moduloSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_moduloSimple from State.testSuiteStore
  { uint r = 7 % 3;
    assert((r == 1)) }

/-- solkey `TestSuite.multiplicationSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_multiplicationSimple from State.testSuiteStore
  { uint r = 3 * 4;
    assert((r == 12)) }

/-- solkey `TestSuite.notEqualSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_notEqualSimple from State.testSuiteStore
  { bool r = (3 != 4);
    assert(r) }

/-- solkey `TestSuite.powerSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_powerSimple from State.testSuiteStore
  { uint r = 2 ** 3;
    assert((r == 8)) }

/-- solkey `TestSuite.requireGuardBox` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_requireGuardBox from State.testSuiteStore
  { uint x = 1;
    age = 1;
    uint r = age;
    assert((r == 1)) }

/-- solkey `TestSuite.requireHoldsDiamond` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_requireHoldsDiamond from State.testSuiteStore
  { uint x = 5;
    require((x > 0));
    total = x;
    uint r = total;
    assert((r == 5)) }

/-- solkey `TestSuite.storageAliasRebindAlias` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageAliasRebindAlias from State.testSuiteStore
  { Person storage alicePath = alice;
    bob.age = 20;
    alicePath@Person = bob;
    uint r = alicePath@Person.age;
    assert((r == 20)) }

/-- solkey `TestSuite.storageDeepFieldPostincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageDeepFieldPostincrement from State.testSuiteStore
  { alice.account.balance = 100;
    alice.account.balance++;
    uint r = alice.account.balance;
    assert((r == 101)) }

/-- solkey `TestSuite.storageDeepFieldPreincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageDeepFieldPreincrement from State.testSuiteStore
  { alice.account.balance = 100;
    ++alice.account.balance;
    uint r = alice.account.balance;
    assert((r == 101)) }

/-- solkey `TestSuite.storageFieldAddAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldAddAssign from State.testSuiteStore
  { alice.age = 30;
    alice.age += 4;
    uint r = alice.age;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldCopyStruct` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldCopyStruct from State.testSuiteStore
  { bob.account.balance = 11;
    Account storage acc = bob.account;
    alice.account = acc@Account;
    uint r = alice.account.balance;
    assert((r == 11)) }

/-- solkey `TestSuite.storageFieldCopyValueField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldCopyValueField from State.testSuiteStore
  { bob.age = 30;
    alice.age = bob.age;
    uint r = alice.age;
    assert((r == 30)) }

/-- solkey `TestSuite.storageFieldDeepDivAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepDivAssign from State.testSuiteStore
  { alice.account.balance = 36;
    alice.account.balance /= 4;
    uint r = alice.account.balance;
    assert((r == 9)) }

/-- solkey `TestSuite.storageFieldDeepModAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepModAssign from State.testSuiteStore
  { alice.account.balance = 37;
    alice.account.balance %= 4;
    uint r = alice.account.balance;
    assert((r == 1)) }

/-- solkey `TestSuite.storageFieldDeepMulAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepMulAssign from State.testSuiteStore
  { alice.account.balance = 8;
    alice.account.balance *= 3;
    uint r = alice.account.balance;
    assert((r == 24)) }

/-- solkey `TestSuite.storageFieldDeepSubAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepSubAssign from State.testSuiteStore
  { alice.account.balance = 30;
    alice.account.balance -= 4;
    uint r = alice.account.balance;
    assert((r == 26)) }

/-- solkey `TestSuite.storageFieldDeepWriteRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepWriteRead from State.testSuiteStore
  { alice.account.balance = 34;
    uint r = alice.account.balance;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldDelete` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDelete from State.testSuiteStore
  { alice.age = 30;
    delete alice.age;
    uint r = alice.age;
    assert((r == 0)) }

/-- solkey `TestSuite.storageFieldDeleteThenCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeleteThenCopy from State.testSuiteStore
  { bob.account.balance = 10;
    delete bob.account;
    alice.account = bob.account;
    uint r = alice.account.balance;
    assert((r == 0)) }

/-- solkey `TestSuite.storageFieldDeleteThenCopyDeep` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeleteThenCopyDeep from State.testSuiteStore
  { bob.account.token.value = 7;
    delete bob.account;
    alice.account = bob.account;
    uint r = alice.account.token.value;
    assert((r == 0)) }

/-- solkey `TestSuite.storageFieldDivAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDivAssign from State.testSuiteStore
  { alice.age = 30;
    alice.age /= 5;
    uint r = alice.age;
    assert((r == 6)) }

/-- solkey `TestSuite.storageFieldModAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldModAssign from State.testSuiteStore
  { alice.age = 30;
    alice.age %= 7;
    uint r = alice.age;
    assert((r == 2)) }

end TestSuite
end Calculus
end Solidity
