import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part01

Obligations 1-24 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.additionStorageWrite` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5, y = 7.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_additionStorageWrite from State.testSuiteStore
  { uint x = 5;
    uint y = 7;
    alice.age = x + y;
    uint r = alice.age;
    assert((r == 12)) }

/-- solkey `TestSuite.storageRootReadWrite` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootReadWrite from State.testSuiteStore
  { age = 34;
    uint r = age;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldWriteRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldWriteRead from State.testSuiteStore
  { alice.age = 34;
    uint r = alice.age;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldDeepAddAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDeepAddAssign from State.testSuiteStore
  { alice.account.balance = 30;
    alice.account.balance += 4;
    uint r = alice.account.balance;
    assert((r == 34)) }

/-- solkey `TestSuite.storageFieldGlobalAge` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldGlobalAge from State.testSuiteStore
  { alice.age = 34;
    assert((alice.age == 34));
    uint r = alice.age;
    assert((r == 34)) }

/-- solkey `TestSuite.storageAliasWrite` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageAliasWrite from State.testSuiteStore
  { Person storage p = alice;
    Account storage acc = p@Person.account;
    acc@Account.balance = 100;
    p@Person.account.token.value = 3;
    assert((alice.account.balance == 100));
    assert((alice.account.token.value == 3)) }

/-- solkey `TestSuite.storageIndexRootMapping` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageIndexRootMapping from State.testSuiteStore
  { balances[1] = 42;
    uint r = balances[1];
    assert((r == 42)) }

/-- solkey `TestSuite.storageIndexAddAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexAddAssign from State.testSuiteStore
  { values.push();
    values.push();
    values[1] = 40;
    values[1] += 2;
    uint r = values[1];
    assert((r == 42)) }

/-- solkey `TestSuite.storageIndexMappingAddAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageIndexMappingAddAssign from State.testSuiteStore
  { balances[1] = 40;
    balances[1] += 2;
    uint r = balances[1];
    assert((r == 42)) }

/-- solkey `TestSuite.storageIndexReadComplexReceiverBindLocalRoot` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexReadComplexReceiverBindLocalRoot from State.testSuiteStore
  { (bucket@@TokenBucket.tokens).push();
    bucket@@TokenBucket.tokens[0].value = 9;
    Token storage t = bucket@@TokenBucket.tokens[0];
    uint r = t@Token.value;
    assert((r == 9)) }

/-- solkey `TestSuite.storageIndexWriteComplexReceiverCopySource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexWriteComplexReceiverCopySource from State.testSuiteStore
  { (bucket@@TokenBucket.tokens).push();
    alice.account.token.value = 7;
    Token storage tokRef = alice.account.token;
    bucket@@TokenBucket.tokens[0] = tokRef@Token;
    uint r = bucket@@TokenBucket.tokens[0].value;
    assert((r == 7)) }

/-- solkey `TestSuite.storageFieldWriteRootRhsComplexReceiver` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldWriteRootRhsComplexReceiver from State.testSuiteStore
  { tok@@Token.value = 7;
    alice.account.token = tok@@Token;
    uint r = alice.account.token.value;
    assert((r == 7)) }

/-- solkey `TestSuite.storageIndexWriteRootRhsComplexReceiver` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageIndexWriteRootRhsComplexReceiver from State.testSuiteStore
  { total = 9;
    ledger@@Ledger.balances[3] = total;
    uint r = ledger@@Ledger.balances[3];
    assert((r == 9)) }

/-- solkey `TestSuite.storagePushValue` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushValue from State.testSuiteStore
  { values.push();
    values.push();
    values.push(42);
    assert((values[2] == 42));
    assert((values.length == 3)) }

/-- solkey `TestSuite.storagePushComplexReceiverNonsimpleArg` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 40, y = 2.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushComplexReceiverNonsimpleArg from State.testSuiteStore
  { matrix.push();
    uint x = 40;
    uint y = 2;
    matrix[0].push(x + y);
    uint r = matrix[0][0];
    assert((r == 42)) }

/-- solkey `TestSuite.storagePushValueCopySource` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushValueCopySource from State.testSuiteStore
  { tok@@Token.value = 7;
    (tokens@@TokenArray).push(tok@@Token);
    assert((tokens@@TokenArray[0].value == 7)) }

/-- solkey `TestSuite.requireTrueLiteral` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_requireTrueLiteral from State.testSuiteStore
  { require(true);
    assert(true) }

/-- solkey `TestSuite.storageBoolRootReadWrite` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageBoolRootReadWrite from State.testSuiteStore
  { flag@@bool = true;
    bool r = flag@@bool;
    assert(r) }

/-- solkey `TestSuite.storageBoolRootCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageBoolRootCopy from State.testSuiteStore
  { flag@@bool = true;
    flag2@@bool = flag@@bool;
    bool r = flag2@@bool;
    assert(r) }

/-- solkey `TestSuite.storageBoolFieldRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageBoolFieldRead from State.testSuiteStore
  { toggle@@Toggle.on = true;
    bool r = toggle@@Toggle.on;
    assert(r) }

/-- solkey `TestSuite.storageBoolMappingRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageBoolMappingRead from State.testSuiteStore
  { flags[2] = true;
    bool r = flags[2];
    assert(r) }

/-- solkey `TestSuite.storageBoolArrayRead` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageBoolArrayRead from State.testSuiteStore
  { (boolFlags@@BoolArray).push();
    boolFlags@@BoolArray[0] = true;
    bool r = boolFlags@@BoolArray[0];
    assert(r) }

/-- solkey `TestSuite.storageBoolFieldStoreRoot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageBoolFieldStoreRoot from State.testSuiteStore
  { toggle@@Toggle.on = true;
    flag@@bool = toggle@@Toggle.on;
    bool r = flag@@bool;
    assert(r) }

/-- solkey `TestSuite.memoryDeclDefault` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryDeclDefault from State.testSuiteStore
  { Person memory mv;
    uint r = mv@Person.age;
    assert((r == 0)) }

end TestSuite
end Calculus
end Solidity
