import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part08

Obligations 169-192 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.testDeepPopDoesNotResetMappingMember` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testDeepPopDoesNotResetMappingMember from State.testSuiteStore
  { (ledgerUses@@LedgerUseArray).push();
    ledgerUses@@LedgerUseArray[0].ledger.balances[1] = 10;
    (ledgerUses@@LedgerUseArray).pop();
    (ledgerUses@@LedgerUseArray).push();
    assert((ledgerUses@@LedgerUseArray[0].ledger.balances[1] == 10)) }

/-- solkey `TestSuite.testMemoryAliasing` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryAliasing from State.testSuiteStore
  { Person memory mv;
    Account memory mv2 = mv@Person.account;
    mv2@Account.balance = 100;
    assert((mv@Person.account.balance == 100)) }

/-- solkey `TestSuite.testMemoryDeleteAlias` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryDeleteAlias from State.testSuiteStore
  { Person memory mv;
    Account memory mv2 = mv@Person.account;
    mv2@Account.balance = 100;
    delete mv2@Account;
    uint b = mv2@Account.balance;
    assert((b == 0)) }

/-- solkey `TestSuite.testMemoryDeleteIdentityFieldFreshensSlot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryDeleteIdentityFieldFreshensSlot from State.testSuiteStore
  { Person memory mv;
    Account memory mv2 = mv@Person.account;
    mv2@Account.balance = 100;
    delete mv@Person.account;
    assert((mv@Person.account.balance == 0));
    assert((mv2@Account.balance == 100)) }

/-- solkey `TestSuite.testMemoryDeletePrimitiveField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryDeletePrimitiveField from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 20;
    delete mv@Person.age;
    assert((mv@Person.age == 0)) }

/-- solkey `TestSuite.testMemoryFieldShallowCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryFieldShallowCopy from State.testSuiteStore
  { Person memory mv;
    Person memory mv2;
    mv2@Person.account.balance = 50;
    mv@Person.account = mv2@Person.account;
    mv@Person.account.balance = 60;
    assert((mv2@Person.account.balance == 60));
    assert((mv@Person.account.balance == 60)) }

/-- solkey `TestSuite.testMemoryRootAlias` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryRootAlias from State.testSuiteStore
  { Person memory mv;
    Person memory mv2;
    mv2@Person.age = 40;
    mv@Person = mv2@Person;
    mv@Person.age = 41;
    assert((mv2@Person.age == 41));
    assert((mv@Person.age == 41)) }

/-- solkey `TestSuite.testMemoryRootDeleteRebindsOnlyLocal` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryRootDeleteRebindsOnlyLocal from State.testSuiteStore
  { Person memory mv;
    Person memory mv2 = mv@Person;
    mv@Person.age = 33;
    delete mv@Person;
    assert((mv@Person.age == 0));
    assert((mv2@Person.age == 33)) }

/-- solkey `TestSuite.testMemoryToStorageCopyComplexSource` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryToStorageCopyComplexSource from State.testSuiteStore
  { Person memory mv;
    mv@Person.account.balance = 50;
    alice.account = mv@Person.account;
    mv@Person.account.balance = 51;
    assert((alice.account.balance == 50)) }

/-- solkey `TestSuite.testMemoryToStorageCopyComplexTarget` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryToStorageCopyComplexTarget from State.testSuiteStore
  { Token memory mv;
    mv@Token.value = 99;
    alice.account.token = mv@Token;
    mv@Token.value = 100;
    assert((alice.account.token.value == 99)) }

/-- solkey `TestSuite.testMemoryToStorageCopyField` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryToStorageCopyField from State.testSuiteStore
  { Account memory mv;
    mv@Account.balance = 50;
    alice.account = mv@Account;
    mv@Account.balance = 51;
    assert((alice.account.balance == 50)) }

/-- solkey `TestSuite.testMemoryToStorageCopyRoot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testMemoryToStorageCopyRoot from State.testSuiteStore
  { Person memory mv;
    mv@Person.age = 42;
    alice = mv@Person;
    mv@Person.age = 43;
    assert((alice.age == 42)) }

/-- solkey `TestSuite.testMemoryToStorageIndexCopyImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testMemoryToStorageIndexCopyImpureIndex from State.testSuiteStore
  { persons.push();
    persons.push();
    Person memory mv;
    mv@Person.age = 7;
    uint i = 0;
    persons[i++] = mv@Person;
    assert((i == 1));
    assert((persons[0].age == 7)) }

/-- solkey `TestSuite.testNestedIndexWriteImpureIndexPrimitiveRhs` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testNestedIndexWriteImpureIndexPrimitiveRhs from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[1].push(100);
    uint i = 1;
    matrix[i++][0] = i;
    assert((i == 2));
    assert((matrix[1][0] == 1)) }

/-- solkey `TestSuite.testNestedIndexReadImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testNestedIndexReadImpureIndex from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[1].push(100);
    uint i = 1;
    uint v = matrix[i++][0];
    assert((i == 2));
    assert((v == 100)) }

/-- solkey `TestSuite.testNestedIndexWriteImpureReceiverAndIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testNestedIndexWriteImpureReceiverAndIndex from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[0].push(0);
    matrix[0].push(0);
    matrix[1].push(0);
    matrix[1].push(0);
    uint i = 0;
    matrix[i++][i++] = 77;
    assert((i == 2));
    assert((matrix[0][1] == 77));
    assert((matrix[1][0] == 0)) }

/-- solkey `TestSuite.testNestedIndexReadImpureReceiverAndIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testNestedIndexReadImpureReceiverAndIndex from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[0].push(0);
    matrix[0].push(11);
    matrix[1].push(22);
    uint i = 0;
    uint v = matrix[i++][i++];
    assert((i == 2));
    assert((v == 11)) }

/-- solkey `TestSuite.testStorageDeleteImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageDeleteImpureReceiver from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[0].push(9);
    uint i = 0;
    delete matrix[i++][0];
    assert((i == 1));
    assert((matrix[0][0] == 0)) }

/-- solkey `TestSuite.testStoragePushImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStoragePushImpureReceiver from State.testSuiteStore
  { matrix.push();
    matrix.push();
    uint i = 0;
    matrix[i++].push(i);
    assert((i == 1));
    assert((matrix[0][0] == 1)) }

/-- solkey `TestSuite.testCompoundAssignImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testCompoundAssignImpureReceiver from State.testSuiteStore
  { persons.push();
    persons.push();
    persons[0].age = 5;
    uint i = 0;
    persons[i++].age += i;
    assert((i == 1));
    assert((persons[0].age == 5)) }

/-- solkey `TestSuite.testIndexWriteReceiverReadsMutatedVar` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testIndexWriteReceiverReadsMutatedVar from State.testSuiteStore
  { matrix.push();
    matrix.push();
    matrix[0].push(0);
    matrix[1].push(0);
    uint k = 0;
    matrix[k][k++] = 77;
    assert((k == 1));
    assert((matrix[0][0] == 77));
    assert((matrix[1][0] == 0)) }

/-- solkey `TestSuite.testNestedStorageWrites` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testNestedStorageWrites from State.testSuiteStore
  { alice.account.balance = 10;
    alice.account.token.value = 5;
    uint b = alice.account.balance;
    uint v = alice.account.token.value;
    assert((b == 10));
    assert((v == 5)) }

/-- solkey `TestSuite.testStorageAliases` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testStorageAliases from State.testSuiteStore
  { Person storage p = alice;
    Account storage acc = p@Person.account;
    acc@Account.balance = 100;
    p@Person.account.token.value = 3;
    assert((alice.account.balance == 100));
    assert((alice.account.token.value == 3)) }

/-- solkey `TestSuite.testStorageArrayReadWrite` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testStorageArrayReadWrite from State.testSuiteStore
  { (tokens@@TokenArray).push();
    tokens@@TokenArray[0].value = 100;
    uint v = tokens@@TokenArray[0].value;
    assert((v == 100)) }

end TestSuite
end Calculus
end Solidity
