import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part10

Obligations 217-240 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Calculus/Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.storageFieldDisjointFields` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDisjointFields from State.testSuiteStore
  { alice.account.balance = 1;
    alice.account.token.value = 2;
    assert((alice.account.balance == 1));
    assert((alice.account.token.value == 2)) }

/-- solkey `TestSuite.storageFieldDisjointRoots` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageFieldDisjointRoots from State.testSuiteStore
  { alice.age = 1;
    bob.age = 2;
    assert((alice.age == 1));
    assert((bob.age == 2)) }

/-- solkey `TestSuite.memoryDelete` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_memoryDelete from State.testSuiteStore
  { Person memory mv;
    Account memory mv2 = mv@Person.account;
    mv@Person.age = 20;
    mv2@Account.balance = 100;
    delete mv@Person.age;
    delete mv@Person.account;
    uint result = mv@Person.age;
    uint aliasBalance = mv2@Account.balance;
    uint newBalance = mv@Person.account.balance;
    assert((result == 0));
    assert((aliasBalance == 100));
    assert((newBalance == 0)) }

/-- solkey `TestSuite.storageAliasRebindOriginal` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageAliasRebindOriginal from State.testSuiteStore
  { uint before = alice.age;
    Person storage alicePath = alice;
    bob.age = 20;
    alicePath@Person = bob;
    assert((alice.age == before)) }

/-- solkey `TestSuite.testSimpleAssert` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testSimpleAssert from State.testSuiteStore
  { age = 42;
    uint v = age;
    assert((v == 42)) }

/-- solkey `TestSuite.signedUnaryMinusInRange` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_signedUnaryMinusInRange from State.testSuiteStore
  { int8 x = 5;
    int8 r;
    int8 expected;
    r = -x;
    expected = -5;
    assert((r == expected)) }

/-- solkey `TestSuite.storageIndexWriteRefSourceImpureIndex` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexWriteRefSourceImpureIndex from State.testSuiteStore
  { persons.push();
    Person memory mv;
    persons[mv@Person.age++] = mv@Person;
    assert((persons[0].age == 1)) }

/-- solkey `TestSuite.storageFieldWriteRefSourceImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageFieldWriteRefSourceImpureReceiver from State.testSuiteStore
  { persons.push();
    Account memory mv;
    persons[mv@Account.balance++].account = mv@Account;
    assert((persons[0].account.balance == 1)) }

/-- solkey `TestSuite.storageFieldWriteStorageRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageFieldWriteStorageRefImpureReceiver from State.testSuiteStore
  { persons.push();
    persons.push();
    alice.account.balance = 9;
    Account storage src = alice.account;
    uint i = 0;
    persons[i++].account = src@Account;
    assert((i == 1));
    assert((persons[0].account.balance == 9)) }

/-- solkey `TestSuite.storageFieldWriteRootRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageFieldWriteRootRefImpureReceiver from State.testSuiteStore
  { persons.push();
    persons.push();
    tok@@Token.value = 4;
    uint i = 0;
    persons[i++].account.token = tok@@Token;
    assert((i == 1));
    assert((persons[0].account.token.value == 4)) }

/-- solkey `TestSuite.storageIndexWriteRootRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexWriteRootRefImpureReceiver from State.testSuiteStore
  { (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    tok@@Token.value = 3;
    uint i = 1;
    buckets@@TokenBucketArray[i++].tokens[0] = tok@@Token;
    assert((i == 2));
    assert((buckets@@TokenBucketArray[1].tokens[0].value == 3)) }

/-- solkey `TestSuite.storageIndexWriteStorageRefImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageIndexWriteStorageRefImpureReceiver from State.testSuiteStore
  { (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    tok@@Token.value = 8;
    Token storage src = tok@@Token;
    uint i = 1;
    buckets@@TokenBucketArray[i++].tokens[0] = src@Token;
    assert((i == 2));
    assert((buckets@@TokenBucketArray[1].tokens[0].value == 8)) }

/-- solkey `TestSuite.memoryToStorageIndexImpureReceiver` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_memoryToStorageIndexImpureReceiver from State.testSuiteStore
  { (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray).push();
    (buckets@@TokenBucketArray[1].tokens).push();
    Token memory mv;
    mv@Token.value = 5;
    uint i = 1;
    buckets@@TokenBucketArray[i++].tokens[0] = mv@Token;
    assert((i == 2));
    assert((buckets@@TokenBucketArray[1].tokens[0].value == 5)) }

/-- solkey `TestSuite.additionLeftImpureRightReadFirst` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionLeftImpureRightReadFirst from State.testSuiteStore
  { uint i = 1;
    uint x = i++ + i;
    assert((x == 2));
    assert((i == 2)) }

/-- solkey `TestSuite.additionRightImpure` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionRightImpure from State.testSuiteStore
  { uint i = 1;
    uint x = i + i++;
    assert((x == 3));
    assert((i == 2)) }

/-- solkey `TestSuite.additionBothOperandsImpure` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_additionBothOperandsImpure from State.testSuiteStore
  { uint i = 1;
    uint x = i++ + i++;
    assert((x == 3));
    assert((i == 3)) }

/-- solkey `TestSuite.subtractionLeftImpureRightReadFirst` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_subtractionLeftImpureRightReadFirst from State.testSuiteStore
  { uint i = 5;
    uint x = i++ - i;
    assert((x == 0));
    assert((i == 6)) }

/-- solkey `TestSuite.lessThanLeftImpureRightReadFirst` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_lessThanLeftImpureRightReadFirst from State.testSuiteStore
  { uint i = 1;
    bool b = (i++ < i);
    assert(!b);
    assert((i == 2)) }

/-- solkey `TestSuite.testCopyRootKeepsValueMembers` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testCopyRootKeepsValueMembers from State.testSuiteStore
  { bob.age = 7;
    bob.account.balance = 3;
    alice = bob;
    bob.age = 8;
    assert((alice.age == 7));
    assert((alice.account.balance == 3)) }

/-- solkey `TestSuite.testCopyFieldNested` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testCopyFieldNested from State.testSuiteStore
  { Account storage acc = bob.account;
    acc@Account.token.value = 5;
    alice.account = acc@Account;
    acc@Account.token.value = 6;
    assert((alice.account.token.value == 5)) }

/-- solkey `TestSuite.testCopyOfCopy` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testCopyOfCopy from State.testSuiteStore
  { bob.age = 4;
    alice = bob;
    persons.push();
    persons[0] = alice;
    assert((persons[0].age == 4)) }

/-- solkey `TestSuite.testCopyIntoMappingEntry` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at k = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testCopyIntoMappingEntry from State.testSuiteStore
  { uint k = 3;
    alice.age = 6;
    folks[k] = alice;
    alice.age = 7;
    assert((folks[k].age == 6)) }

/-- solkey `TestSuite.testCopyArrayMemberElements` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_testCopyArrayMemberElements from State.testSuiteStore
  { (basketA@@Basket.items).push(9);
    basketB@@Basket = basketA@@Basket;
    basketA@@Basket.items[0] = 1;
    assert((basketB@@Basket.items.length == 1));
    assert((basketB@@Basket.items[0] == 9)) }

/-- solkey `TestSuite.testCopyPrimitiveRoot` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_testCopyPrimitiveRoot from State.testSuiteStore
  { age = 3;
    balance = age;
    age = 4;
    assert((balance == 3)) }

end TestSuite
end Calculus
end Solidity
