import Solidity.Examples.Common
import Solidity.Semantics

/-!
# solkey `TestSuite.sol`, by the rule table alone — Part07

Obligations 145-168 of 245.

The same obligations as `Solidity/Examples/Solkey/TestSuite.lean`,
proved without the interpreter doing the symbolic execution:
`sol_calculus` drives each program with the taclets of `Rules.lean`
until no line of the frontier has a statement left, and decides the
frontier reached.

That is the difference worth the second corpus. `sol_wp` never reads
the rule table, so the corpus beside this one says the *interpreter*
agrees with solkey; a chain here says the *calculus* does, which is
the artefact that corresponds to a KeY proof.

What is left at the end is first-order: the accumulated update
applied to the store, and one obligation line per `assert` — KeY's
own shape, since `Rules.assertGoals` leaves the violated branch as
an obligation rather than a revert.

The split into parts is an elaboration cost, nothing else: they
reopen one namespace and are independent files over the same cached
dependencies, so `scripts/check-calculus-parity.sh` runs them
concurrently.

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. Verdicts are pinned in
`tests/solkey/expected-calculus.tsv`, and `docs/calculus-parity.md`
is the scoreboard.
-/

namespace Solidity
namespace Calculus
namespace TestSuite

open Semantics SoliditySyntax StandardExample Rules

set_option maxHeartbeats 8000000

/-- solkey `TestSuite.storagePushReturnAssign` (TestSuite.sol).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storagePushReturnAssign from State.testSuiteStore
  { values.push();
    values.push();
    values.push() = 42;
    assert((values[2] == 42));
    assert((values.length == 3)) }

/-- solkey `TestSuite.storageRootAddAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootAddAssign from State.testSuiteStore
  { age = 10;
    age += 5;
    uint r = age;
    assert((r == 15)) }

/-- solkey `TestSuite.storageRootCopySource` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootCopySource from State.testSuiteStore
  { age = 34;
    balance = age;
    uint r = balance;
    assert((r == 34)) }

/-- solkey `TestSuite.storageRootCopyStruct` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootCopyStruct from State.testSuiteStore
  { bob.age = 7;
    alice = bob;
    uint r = alice.age;
    assert((r == 7)) }

/-- solkey `TestSuite.storageRootDeleteStruct` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootDeleteStruct from State.testSuiteStore
  { alice.age = 30;
    delete alice;
    uint r = alice.age;
    assert((r == 0)) }

/-- solkey `TestSuite.storageRootDeleteThenCopy` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootDeleteThenCopy from State.testSuiteStore
  { bob.age = 30;
    delete bob;
    alice = bob;
    uint r = alice.age;
    assert((r == 0)) }

/-- solkey `TestSuite.storageRootDelete` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootDelete from State.testSuiteStore
  { age = 10;
    delete age;
    uint r = age;
    assert((r == 0)) }

/-- solkey `TestSuite.storageRootDisjoint` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootDisjoint from State.testSuiteStore
  { age = 7;
    balance = 9;
    uint r = age;
    assert((r == 7)) }

/-- solkey `TestSuite.storageRootDivAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootDivAssign from State.testSuiteStore
  { age = 20;
    age /= 4;
    uint r = age;
    assert((r == 5)) }

/-- solkey `TestSuite.storageRootModAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootModAssign from State.testSuiteStore
  { age = 17;
    age %= 5;
    uint r = age;
    assert((r == 2)) }

/-- solkey `TestSuite.storageRootMulAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootMulAssign from State.testSuiteStore
  { age = 6;
    age *= 3;
    uint r = age;
    assert((r == 18)) }

/-- solkey `TestSuite.storageRootMultipleWrites` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootMultipleWrites from State.testSuiteStore
  { age = 1;
    age = 2;
    uint r = age;
    assert((r == 2)) }

/-- solkey `TestSuite.storageRootPostdecrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPostdecrementAssign from State.testSuiteStore
  { age = 10;
    uint r = postdec(age);
    assert((r == 10)) }

/-- solkey `TestSuite.storageRootPostincrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPostincrementAssign from State.testSuiteStore
  { age = 10;
    uint r = age++;
    assert((r == 10)) }

/-- solkey `TestSuite.storageRootPostincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPostincrement from State.testSuiteStore
  { age = 10;
    age++;
    uint r = age;
    assert((r == 11)) }

/-- solkey `TestSuite.storageRootPredecrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPredecrement from State.testSuiteStore
  { age = 10;
    predec(age);
    uint r = age;
    assert((r == 9)) }

/-- solkey `TestSuite.storageRootPreincrementAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPreincrementAssign from State.testSuiteStore
  { age = 10;
    uint r = ++age;
    assert((r == 11)) }

/-- solkey `TestSuite.storageRootPreincrement` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootPreincrement from State.testSuiteStore
  { age = 10;
    ++age;
    uint r = age;
    assert((r == 11)) }

/-- solkey `TestSuite.storageRootSubAssign` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageRootSubAssign from State.testSuiteStore
  { age = 10;
    age -= 4;
    uint r = age;
    assert((r == 6)) }

/-- solkey `TestSuite.storageRootWriteRhsCapture` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 1, y = 2, z = 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_storageRootWriteRhsCapture from State.testSuiteStore
  { uint x = 1;
    uint y = 2;
    uint z = 3;
    total = x + y*z;
    uint r = total;
    assert((r == 7)) }

/-- solkey `TestSuite.storageToMemory` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_storageToMemory from State.testSuiteStore
  { alice.age = 27;
    Person memory mv = alice;
    alice.age = 30;
    uint r = mv@Person.age;
    assert((r == 27)) }

/-- solkey `TestSuite.subtractionSimple` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_subtractionSimple from State.testSuiteStore
  { uint r = 7 - 2;
    assert((r == 5)) }

/-- solkey `TestSuite.subtractionStorageRead` (TestSuite.sol). -/
sol_calculus solkey_TestSuite_subtractionStorageRead from State.testSuiteStore
  { alice.age = 10;
    uint r = alice.age - 3;
    assert((r == 7)) }

/-- solkey `TestSuite.unaryMinusSimple` (TestSuite.sol).

concretized: solkey proves this for all parameters; ported at x = 5.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
sol_calculus solkey_TestSuite_unaryMinusSimple from State.testSuiteStore
  { int x = 5;
    int r = -x;
    int expected = -5;
    assert((r == expected)) }

end TestSuite
end Calculus
end Solidity
