import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcArrays.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcArrays

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcArrays.pushLvalueAssignsAndGrows` (solc/SolcArrays.sol).

solc: array/array_push_return_reference.sol — `arr.push() = v;` writes the new slot and
bumps the length; the upstream `fetch(0) -> 42`, `fetch(1) -> 23` sequence.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_pushLvalueAssignsAndGrows :
    (sol!{ < (storageArray@@UintArray).push() = 42;
             assert((storageArray@@UintArray.length == 1));
             assert((storageArray@@UintArray[0] == 42));
             (storageArray@@UintArray).push() = 23;
             assert((storageArray@@UintArray.length == 2));
             assert((storageArray@@UintArray[0] == 42));
             assert((storageArray@@UintArray[1] == 23)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.pushWithArgument` (solc/SolcArrays.sol).

solc: array/array_push_with_arg.sol — `arr.push(v)` appends `v`.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_pushWithArgument :
    (sol!{ < (storageArray@@UintArray).push(42);
             assert((storageArray@@UintArray.length == 1));
             assert((storageArray@@UintArray[0] == 42)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.pushThenPopRestoresLength` (solc/SolcArrays.sol).

solc: array/array_storage_push_pop.sol — the upstream `set_get_length` grows the array
with `push()` and drains it with `pop()`, ending at length 0. Unrolled to three.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_pushThenPopRestoresLength :
    (sol!{ < (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             assert((storageArray@@UintArray.length == 3));
             (storageArray@@UintArray).pop();
             assert((storageArray@@UintArray.length == 2));
             (storageArray@@UintArray).pop();
             (storageArray@@UintArray).pop();
             assert((storageArray@@UintArray.length == 0)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.pushEmptyGrowsLength` (solc/SolcArrays.sol).

solc: array/array_storage_push_empty.sol — a no-arg `push()` appends one slot.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_pushEmptyGrowsLength :
    (sol!{ < (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             assert((storageArray@@UintArray.length == 3)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.popThenPushSlotIsZeroed` (solc/SolcArrays.sol).

solc: array/array_storage_index_zeroed_test.sol — the upstream invariant that a slot
beyond the current length reads as zero: write a slot, pop it, push it back, and it is
cleared.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_popThenPushSlotIsZeroed :
    (sol!{ < (storageArray@@UintArray).push();
             storageArray@@UintArray[0] = 7;
             assert((storageArray@@UintArray[0] == 7));
             (storageArray@@UintArray).pop();
             (storageArray@@UintArray).push();
             assert((storageArray@@UintArray[0] == 0)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.pushedSlotIsZeroed` (solc/SolcArrays.sol).

solc: array/array_storage_index_zeroed_test.sol — the direct form of the same
invariant: a freshly pushed slot reads as zero.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_pushedSlotIsZeroed :
    (sol!{ < (storageArray@@UintArray).push();
             assert((storageArray@@UintArray[0] == 0)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.storageIndexReadWrite` (solc/SolcArrays.sol).

solc: array/array_storage_index_access.sol — element writes are independent of each
other.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_storageIndexReadWrite :
    (sol!{ < (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             storageArray@@UintArray[0] = 1;
             storageArray@@UintArray[1] = 2;
             storageArray@@UintArray[2] = 3;
             assert((storageArray@@UintArray[0] == 1));
             assert((storageArray@@UintArray[1] == 2));
             assert((storageArray@@UintArray[2] == 3)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.storageArrayAliasWritesThrough` (solc/SolcArrays.sol).

solc: array/storage_array_ref.sol — `uint[] storage ref = arr;` is a reference, so a
write through it is visible on the original array.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_storageArrayAliasWritesThrough :
    (sol!{ < (storageArray@@UintArray).push();
             (storageArray@@UintArray).push();
             UintArray storage ref = storageArray@@UintArray;
             ref@UintArray[1] = 33;
             assert((storageArray@@UintArray[1] == 33));
             assert((ref@UintArray.length == 2)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.storageStructArrayAliasWritesThrough` (solc/SolcArrays.sol).

solc: array/storage_array_ref.sol — the same reference semantics on an array of
structs.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_storageStructArrayAliasWritesThrough :
    (sol!{ < (structs@@PairArray).push();
             (structs@@PairArray).push();
             PairArray storage ref = structs@@PairArray;
             ref@PairArray[1].a = 33;
             assert((structs@@PairArray[1].a == 33));
             assert((ref@PairArray.length == 2)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.deleteArrayElementOfStructs` (solc/SolcArrays.sol).

solc: array/delete/delete_on_array_of_structs.sol — `delete arr[i]` resets that element
and leaves its neighbour alone.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_deleteArrayElementOfStructs :
    (sol!{ < (structs@@PairArray).push();
             (structs@@PairArray).push();
             structs@@PairArray[0].a = 1;
             structs@@PairArray[0].b = 2;
             structs@@PairArray[1].a = 3;
             structs@@PairArray[1].b = 4;
             delete structs@@PairArray[0];
             assert((structs@@PairArray[0].a == 0));
             assert((structs@@PairArray[0].b == 0));
             assert((structs@@PairArray[1].a == 3));
             assert((structs@@PairArray[1].b == 4)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.matrixElementWriteRead` (solc/SolcArrays.sol).

solc: array/array_2d_assignment.sol — an element of a `uint[][]` is addressed by two
index steps.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_matrixElementWriteRead :
    (sol!{ < matrix.push();
             matrix.push();
             matrix.push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2].push();
             matrix[2][3] = 7;
             uint r = matrix[2][3];
             assert((r == 7)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

/-- solkey `SolcArrays.lengthTracksPushAndPop` (solc/SolcArrays.sol).

solc: array/array_storage_length_access.sol — `push` and `pop` are the only things that
change `length`.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Arrays_lengthTracksPushAndPop :
    (sol!{ < (storageArray@@UintArray).push();
             storageArray@@UintArray[0] = 5;
             assert((storageArray@@UintArray.length == 1));
             (storageArray@@UintArray).push(6);
             assert((storageArray@@UintArray.length == 2));
             (storageArray@@UintArray).pop();
             assert((storageArray@@UintArray.length == 1));
             assert((storageArray@@UintArray[0] == 5)) > (true) }).Holds
      State.solcArraysStore := by
  sol_wp

end SolcArrays
end Solkey
end Solidity
