import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcControlFlow.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcControlFlow

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcControlFlow.doWhileFalseRunsBodyOnce` (solc/SolcControlFlow.sol).

solc: statements/do_while_loop_continue.sol — `do { … } while (false)` runs its body
exactly once. Unrolled: the guard `i > 0` is false on the only iteration, so the body
increments `i` and execution continues past the loop.

The increment is written `i = i + 1;` rather than `i++;` — a bare increment of a
*local* has no rule (see `SolcExpressions.bareIncrementOnLocal`). -/
theorem solkey_solc_ControlFlow_doWhileFalseRunsBodyOnce :
    (sol!{ < uint i = 0;
             uint r = 0;
             if ((i > 0)) { r = 0 } else { i = i + 1 };
             r = 42;
             assert((i == 1));
             assert((r == 42)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.forLoopUnrolledOverArray` (solc/SolcControlFlow.sol).

solc: array/array_storage_index_zeroed_test.sol — the upstream
`for (uint i = 0; i < len; i++) storageArray[i] = i + 1;`, unrolled at length 3.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_forLoopUnrolledOverArray :
    (sol!{ < values.push();
             values.push();
             values.push();
             uint i = 0;
             values[i] = i + 1;
             i = i + 1;
             values[i] = i + 1;
             i = i + 1;
             values[i] = i + 1;
             i = i + 1;
             assert((i == 3));
             assert((values[0] == 1));
             assert((values[1] == 2));
             assert((values[2] == 3)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.sequentialAssignmentDoesNotSwap` (solc/SolcControlFlow.sol).

solc: various/swap_in_storage_overwrite.sol — `(x, y) = (y, x)` does not swap. solc
assigns the tuple components with no temporary, so the pair runs as `y = x; x = y;`
and both structs end up holding x's original value. Tuple assignment does not parse
here, so the port is that desugaring. -/
theorem solkey_solc_ControlFlow_sequentialAssignmentDoesNotSwap :
    (sol!{ < sx@@Pair.a = 1;
             sx@@Pair.b = 2;
             sy@@Pair.a = 3;
             sy@@Pair.b = 4;
             sy@@Pair = sx@@Pair;
             sx@@Pair = sy@@Pair;
             assert((sx@@Pair.a == 1));
             assert((sx@@Pair.b == 2));
             assert((sy@@Pair.a == 1));
             assert((sy@@Pair.b == 2)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.swapViaTemporary` (solc/SolcControlFlow.sol).

solc: various/swap_in_storage_overwrite.sol — the corrected version, with the temporary
the upstream test shows is necessary. -/
theorem solkey_solc_ControlFlow_swapViaTemporary :
    (sol!{ < sx@@Pair.a = 1;
             sx@@Pair.b = 2;
             sy@@Pair.a = 3;
             sy@@Pair.b = 4;
             Pair memory mv = sx@@Pair;
             sx@@Pair = sy@@Pair;
             sy@@Pair = mv@Pair;
             assert((sx@@Pair.a == 3));
             assert((sx@@Pair.b == 4));
             assert((sy@@Pair.a == 1));
             assert((sy@@Pair.b == 2)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.ternarySelectsFirstMemorySource` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_storage_memory_1.sol — `data1 = cond ? x : y;`
with two memory sources, `cond` true.

concretized: solkey proves this for all parameters; ported at cond = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_ternarySelectsFirstMemorySource :
    (sol!{ < uint cond = 1;
             bool c = (cond == 1);
             Pair memory mv;
             mv@Pair.a = 11;
             Pair memory mv2;
             mv2@Pair.a = 22;
             target@@Pair = c ? mv@Pair : mv2@Pair;
             assert((target@@Pair.a == 11)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.ternaryIntoMemoryTarget` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_storage_memory_2.sol — the upstream
`x = cond ? y : data1;`: the selection goes into a *memory* target, which closes.

concretized: solkey proves this for all parameters; ported at cond = 1.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_ternaryIntoMemoryTarget :
    (sol!{ < uint cond = 1;
             bool c = (cond == 1);
             Pair memory mv;
             mv@Pair.a = 11;
             Pair memory mv2;
             mv2@Pair.a = 22;
             Pair memory mv3 = c ? mv@Pair : mv2@Pair;
             assert((mv3@Pair.a == 11)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.ifElseSelectsMemorySource` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_storage_memory_1.sol — the same selection into
a storage target, written as `if`/`else` instead of `?:`.

concretized: solkey proves this for all parameters; ported at cond = 0.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_ifElseSelectsMemorySource :
    (sol!{ < uint cond = 0;
             bool c = (cond == 1);
             Pair memory mv;
             mv@Pair.a = 11;
             Pair memory mv2;
             mv2@Pair.a = 22;
             if (c) { target@@Pair = mv@Pair } else { target@@Pair = mv2@Pair };
             assert((target@@Pair.a == 22)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.ternarySelectsValueByFlag` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_storage_memory_1.sol — the branch selection on
its own, over plain values rather than references.

concretized: solkey proves this for all parameters; ported at cond = 0.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_ternarySelectsValueByFlag :
    (sol!{ < uint cond = 0;
             bool c = (cond == 1);
             uint r = c ? 11 : 22;
             assert((r == 22)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.chainedIfsSelectLastMatch` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_storage_memory_1.sol — the upstream result is
read back through a chain of independent `if`s, the last matching one winning. -/
theorem solkey_solc_ControlFlow_chainedIfsSelectLastMatch :
    (sol!{ < target@@Pair.a = 2;
             uint t = target@@Pair.a;
             uint r = 0;
             if ((t == 1)) { r = 1 };
             if ((t == 2)) { r = 2 };
             assert((r == 2)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

/-- solkey `SolcControlFlow.nestedIfElseSelectsBranch` (solc/SolcControlFlow.sol).

solc: expressions/conditional_expression_multiple.sol — the same branch structure as a
nested `if`/`else` rather than a nested `?:`.

concretized: solkey proves this for all parameters; ported at x = 500.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_ControlFlow_nestedIfElseSelectsBranch :
    (sol!{ < uint x = 500;
             uint d = 0;
             if ((x > 100)) { if (x > 1000) { d = 1000; } else { d = 100; } } else { if (x > 50) { d = 50; } else { d = 10; } };
             assert((d == 100)) > (true) }).Holds
      State.solcControlFlowStore := by
  sol_wp

end SolcControlFlow
end Solkey
end Solidity
