import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcStructs.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcStructs

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcStructs.deleteMemberThroughStorageAlias` (solc/SolcStructs.sol).

solc: structs/struct_delete_member.sol — `T storage x = data1;` does not copy: writing
and then deleting through `x` is observable on `data1`. -/
theorem solkey_solc_Structs_deleteMemberThroughStorageAlias :
    (sol!{ < data1@@Simple.value = 2;
             Simple storage x = data1@@Simple;
             x@Simple.value = 4;
             delete x@Simple.value;
             assert((data1@@Simple.value == 0)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.deleteStructLeavesNeighbours` (solc/SolcStructs.sol).

solc: structs/struct_delete_storage.sol — `delete s` resets every member of the struct
and leaves the neighbouring state variables alone. -/
theorem solkey_solc_Structs_deleteStructLeavesNeighbours :
    (sol!{ < neighbourBefore@@uint = 23;
             neighbourAfter@@uint = 17;
             triple@@Triple.x = 42;
             triple@@Triple.y = 42;
             triple@@Triple.z = 42;
             delete triple@@Triple;
             assert((triple@@Triple.x == 0));
             assert((triple@@Triple.y == 0));
             assert((triple@@Triple.z == 0));
             assert((neighbourBefore@@uint == 23));
             assert((neighbourAfter@@uint == 17)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.deleteStructResetsArrayLength` (solc/SolcStructs.sol).

solc: structs/struct_delete_storage_with_array.sol — `delete s` on a struct holding a
dynamic array resets the array's length.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Structs_deleteStructResetsArrayLength :
    (sol!{ < (withArray@@WithArray.items).push();
             (withArray@@WithArray.items).push();
             delete withArray@@WithArray;
             uint len = withArray@@WithArray.items.length;
             assert((len == 0)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.deleteStructInMapping` (solc/SolcStructs.sol).

solc: structs/struct_delete_struct_in_mapping.sol — `delete m[k]` resets the whole
entry. -/
theorem solkey_solc_Structs_deleteStructInMapping :
    (sol!{ < campaigns@@SimpleMap[0].value = 2;
             delete campaigns@@SimpleMap[0];
             assert((campaigns@@SimpleMap[0].value == 0)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.deleteEntryKeepsOtherKeys` (solc/SolcStructs.sol).

solc: structs/struct_delete_struct_in_mapping.sol — the entry next to the deleted one
is untouched. -/
theorem solkey_solc_Structs_deleteEntryKeepsOtherKeys :
    (sol!{ < campaigns@@SimpleMap[0].value = 2;
             campaigns@@SimpleMap[1].value = 3;
             delete campaigns@@SimpleMap[0];
             assert((campaigns@@SimpleMap[0].value == 0));
             assert((campaigns@@SimpleMap[1].value == 3)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.structCopyViaMemoryLocal` (solc/SolcStructs.sol).

solc: structs/struct_copy_via_local.sol — a storage struct copied out to memory and
back into another storage struct keeps every member. -/
theorem solkey_solc_Structs_structCopyViaMemoryLocal :
    (sol!{ < source@@Pair.a = 1;
             source@@Pair.b = 2;
             Pair memory mv = source@@Pair;
             target@@Pair = mv@Pair;
             assert((target@@Pair.a == 1));
             assert((target@@Pair.b == 2)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.structCopyFromStorageIsDeep` (solc/SolcStructs.sol).

solc: structs/copy_from_storage.sol — the storage source is copied, not aliased: a
later write to the source does not reach the copy. -/
theorem solkey_solc_Structs_structCopyFromStorageIsDeep :
    (sol!{ < source@@Pair.a = 13;
             source@@Pair.b = 14;
             target@@Pair = source@@Pair;
             source@@Pair.a = 20;
             source@@Pair.b = 21;
             assert((target@@Pair.a == 13));
             assert((target@@Pair.b == 14)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.structArrayElementCopy` (solc/SolcStructs.sol).

solc: array/copying/array_copy_storage_storage_struct.sol — the element-wise form of
the upstream whole-array copy `data2 = data1;` (which has no terminal rule yet).

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Structs_structArrayElementCopy :
    (sol!{ < (pairs1@@PairArray).push();
             (pairs2@@PairArray).push();
             pairs1@@PairArray[0].a = 4;
             pairs1@@PairArray[0].b = 5;
             Pair storage src = pairs1@@PairArray[0];
             pairs2@@PairArray[0] = src@Pair;
             assert((pairs2@@PairArray[0].a == 4));
             assert((pairs2@@PairArray[0].b == 5)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

/-- solkey `SolcStructs.structArrayElementCopyMemberwise` (solc/SolcStructs.sol).

solc: array/copying/array_copy_storage_storage_struct.sol — the same copy performed
member by member through two element aliases.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Structs_structArrayElementCopyMemberwise :
    (sol!{ < (pairs1@@PairArray).push();
             (pairs2@@PairArray).push();
             pairs1@@PairArray[0].a = 4;
             pairs1@@PairArray[0].b = 5;
             Pair storage src = pairs1@@PairArray[0];
             Pair storage dst = pairs2@@PairArray[0];
             dst@Pair.a = src@Pair.a;
             dst@Pair.b = src@Pair.b;
             assert((pairs2@@PairArray[0].a == 4));
             assert((pairs2@@PairArray[0].b == 5)) > (true) }).Holds
      State.solcStructsStore := by
  sol_wp

end SolcStructs
end Solkey
end Solidity
