import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcMappings.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcMappings

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcMappings.structStorageToMappingEntry` (solc/SolcMappings.sol).

solc: structs/struct_storage_to_mapping.sol — `m[1] = s;` copies the storage struct into
the mapping entry. -/
theorem solkey_solc_Mappings_structStorageToMappingEntry :
    (sol!{ < sBox@@S.a = 12;
             sMap@@SMap[1] = sBox@@S;
             assert((sMap@@SMap[1].a == 12)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.mappingEntryToStorageStruct` (solc/SolcMappings.sol).

solc: structs/copy_from_mapping.sol — the copy out of a mapping entry into a state
struct. -/
theorem solkey_solc_Mappings_mappingEntryToStorageStruct :
    (sol!{ < sMap@@SMap[1].a = 7;
             sBox@@S = sMap@@SMap[1];
             assert((sBox@@S.a == 7)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.mappingEntryCopyIsDeep` (solc/SolcMappings.sol).

solc: structs/struct_storage_to_mapping.sol — the copy is deep: writing the source
afterwards does not reach the entry. -/
theorem solkey_solc_Mappings_mappingEntryCopyIsDeep :
    (sol!{ < sBox@@S.a = 12;
             sMap@@SMap[1] = sBox@@S;
             sBox@@S.a = 13;
             assert((sMap@@SMap[1].a == 12)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.copySubstructureIntoMapping` (solc/SolcMappings.sol).

solc: structs/copy_substructures_to_mapping.sol — a struct with a nested struct copied
into a mapping entry keeps both levels. -/
theorem solkey_solc_Mappings_copySubstructureIntoMapping :
    (sol!{ < withSub@@WithSub.a = 1;
             withSub@@WithSub.sub.x = 2;
             withSub@@WithSub.sub.y = 3;
             withSubMap@@WithSubMap[5] = withSub@@WithSub;
             assert((withSubMap@@WithSubMap[5].a == 1));
             assert((withSubMap@@WithSubMap[5].sub.x == 2));
             assert((withSubMap@@WithSubMap[5].sub.y == 3)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.copySubstructureFromMapping` (solc/SolcMappings.sol).

solc: structs/copy_substructures_from_mapping.sol — and back out again. -/
theorem solkey_solc_Mappings_copySubstructureFromMapping :
    (sol!{ < withSubMap@@WithSubMap[5].a = 1;
             withSubMap@@WithSubMap[5].sub.x = 2;
             withSub@@WithSub = withSubMap@@WithSubMap[5];
             assert((withSub@@WithSub.a == 1));
             assert((withSub@@WithSub.sub.x == 2)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.mappingKeysAreIndependent` (solc/SolcMappings.sol).

solc: structs/struct_delete_struct_in_mapping.sol — distinct keys are independent. -/
theorem solkey_solc_Mappings_mappingKeysAreIndependent :
    (sol!{ < balances[1] = 10;
             balances[2] = 20;
             delete balances[1];
             assert((balances[1] == 0));
             assert((balances[2] == 20)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.deleteStructKeepsMappingMember` (solc/SolcMappings.sol).

No upstream twin — the Solidity language rule that `delete` on a struct resets its
value members but leaves its mapping members alone (solc has no semantic test for it
because the result is not observable through its return-value harness). This is what
SolKey's lazy `delNode` marker implements. -/
theorem solkey_solc_Mappings_deleteStructKeepsMappingMember :
    (sol!{ < ledger@@Ledger.nonce = 5;
             ledger@@Ledger.balances[1] = 10;
             delete ledger@@Ledger;
             assert((ledger@@Ledger.nonce == 0));
             assert((ledger@@Ledger.balances[1] == 10)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.arrayElementsToMapping` (solc/SolcMappings.sol).

solc: array/copying/array_elements_to_mapping.sol — the upstream `m[0] = s[0];` copies a
whole array into a mapping entry.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Mappings_arrayElementsToMapping :
    (sol!{ < (rows@@UintMatrix).push();
             rows@@UintMatrix[0].push();
             rows@@UintMatrix[0].push();
             rows@@UintMatrix[0][0] = 10;
             rows@@UintMatrix[0][1] = 11;
             UintArray storage row = rows@@UintMatrix[0];
             arrayMap@@UintArrayMap[0] = row@UintArray;
             assert((arrayMap@@UintArrayMap[0][0] == 10));
             assert((arrayMap@@UintArrayMap[0][1] == 11)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

/-- solkey `SolcMappings.arrayElementsToMappingElementwise` (solc/SolcMappings.sol).

solc: array/copying/array_elements_to_mapping.sol — the same copy performed element by
element through the mapping entry's own array.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Mappings_arrayElementsToMappingElementwise :
    (sol!{ < (rows@@UintMatrix).push();
             rows@@UintMatrix[0].push();
             rows@@UintMatrix[0].push();
             rows@@UintMatrix[0][0] = 10;
             rows@@UintMatrix[0][1] = 11;
             uint v0 = rows@@UintMatrix[0][0];
             uint v1 = rows@@UintMatrix[0][1];
             arrayMap@@UintArrayMap[0].push(v0);
             arrayMap@@UintArrayMap[0].push(v1);
             assert((arrayMap@@UintArrayMap[0].length == 2));
             assert((arrayMap@@UintArrayMap[0][0] == 10));
             assert((arrayMap@@UintArrayMap[0][1] == 11)) > (true) }).Holds
      State.solcMappingsStore := by
  sol_wp

end SolcMappings
end Solkey
end Solidity
