import Solidity.Wp.Verifier

/-!
# solkey `solc/SolcExpressions.sol`, ported

Generated by `scripts/solkey-port.mjs` from the solkey source of
truth; do not edit by hand. See that script for the translation
rules and `docs/solkey-parity.md` for the functions that are not
here and why.
-/

namespace Solidity
namespace Solkey
namespace SolcExpressions

open Semantics Wp

set_option maxHeartbeats 8000000

/-- solkey `SolcExpressions.postIncrementYieldsOldValue` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — `a++` yields the old value and increments. -/
theorem solkey_solc_Expressions_postIncrementYieldsOldValue :
    (sol!{ < uint a = 6;
             uint v_p = a++;
             assert((v_p == 6));
             assert((a == 7)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.preIncrementYieldsNewValue` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — `++a` yields the new value. -/
theorem solkey_solc_Expressions_preIncrementYieldsNewValue :
    (sol!{ < uint a = 6;
             uint q = ++a;
             assert((q == 7));
             assert((a == 7)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.incDecChainOnLocal` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — the upstream accumulation
`r = a; r += a++ * 0x10; r += ++a * 0x100` on a local, with each step bound
(0x10 = 16, 0x100 = 256; the expected 6 + 6*16 + 8*256 = 2150). -/
theorem solkey_solc_Expressions_incDecChainOnLocal :
    (sol!{ < uint a = 6;
             uint r = a;
             uint v_p = a++;
             r = r + v_p * 16;
             uint q = ++a;
             r = r + q * 256;
             assert((a == 8));
             assert((r == 2150)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.incDecChainOnStateVariable` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — same chain on a state variable
(`v = 3; r += v++ * 0x1000; r += ++v * 0x10000`), so the storage increment rules are
exercised instead of the local ones (0x1000 = 4096, 0x10000 = 65536; the expected
3*4096 + 5*65536 = 339968). -/
theorem solkey_solc_Expressions_incDecChainOnStateVariable :
    (sol!{ < counter@@uint = 3;
             uint v_p = counter@@uint++;
             uint r = v_p * 4096;
             uint q = ++counter@@uint;
             r = r + q * 65536;
             assert((counter@@uint == 5));
             assert((r == 339968)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.postDecrementYieldsOldValue` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — the decrement twins, which upstream only
covers through the operator table. -/
theorem solkey_solc_Expressions_postDecrementYieldsOldValue :
    (sol!{ < uint a = 6;
             uint v_p = postdec(a);
             assert((v_p == 6));
             assert((a == 5)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.preDecrementYieldsNewValue` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — `--a` yields the new value. -/
theorem solkey_solc_Expressions_preDecrementYieldsNewValue :
    (sol!{ < uint a = 6;
             uint q = predec(a);
             assert((q == 5));
             assert((a == 5)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.compoundAssignOnLocal` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — the upstream chain verbatim, with the
compound assignment `r += a++ * 0x10` on a local instead of the bound-step rewrite
used by [incDecChainOnLocal]. -/
theorem solkey_solc_Expressions_compoundAssignOnLocal :
    (sol!{ < uint a = 6;
             uint r = a;
             r += a * 16;
             assert((r == 102)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.bareIncrementOnLocal` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — a bare `a++;` statement, the increment form
the upstream loops use. -/
theorem solkey_solc_Expressions_bareIncrementOnLocal :
    (sol!{ < uint a = 6;
             a++;
             assert((a == 7)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.bareIncrementOnStateVariable` (solc/SolcExpressions.sol).

solc: expressions/inc_dec_operators.sol — the same statement on a state variable. -/
theorem solkey_solc_Expressions_bareIncrementOnStateVariable :
    (sol!{ < counter@@uint = 6;
             counter@@uint++;
             assert((counter@@uint == 7)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryTrueLiteral` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_true_literal.sol — `true ? 5 : 10` is 5. -/
theorem solkey_solc_Expressions_ternaryTrueLiteral :
    (sol!{ < uint r = true ? 5 : 10;
             assert((r == 5)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryFalseLiteral` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_false_literal.sol — `false ? 5 : 10` is 10. -/
theorem solkey_solc_Expressions_ternaryFalseLiteral :
    (sol!{ < uint r = false ? 5 : 10;
             assert((r == 10)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryNestedOuterHigh` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_multiple.sol — the nested
`x > 100 ? x > 1000 ? 1000 : 100 : x > 50 ? 50 : 10`, upstream case `f(1001) -> 1000`.

concretized: solkey proves this for all parameters; ported at x = 1001.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_ternaryNestedOuterHigh :
    (sol!{ < uint x = 1001;
             uint d = (x > 100) ? ((x > 1000) ? 1000 : 100) : ((x > 50) ? 50 : 10);
             assert((d == 1000)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryNestedOuterLow` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(500) -> 100`.

concretized: solkey proves this for all parameters; ported at x = 500.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_ternaryNestedOuterLow :
    (sol!{ < uint x = 500;
             uint d = (x > 100) ? ((x > 1000) ? 1000 : 100) : ((x > 50) ? 50 : 10);
             assert((d == 100)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryNestedInnerHigh` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(80) -> 50`.

concretized: solkey proves this for all parameters; ported at x = 80.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_ternaryNestedInnerHigh :
    (sol!{ < uint x = 80;
             uint d = (x > 100) ? ((x > 1000) ? 1000 : 100) : ((x > 50) ? 50 : 10);
             assert((d == 50)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.ternaryNestedInnerLow` (solc/SolcExpressions.sol).

solc: expressions/conditional_expression_multiple.sol — upstream case `f(40) -> 10`.

concretized: solkey proves this for all parameters; ported at x = 40.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_ternaryNestedInnerLow :
    (sol!{ < uint x = 40;
             uint d = (x > 100) ? ((x > 1000) ? 1000 : 100) : ((x > 50) ? 50 : 10);
             assert((d == 10)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.exponentiationIsRightAssociative` (solc/SolcExpressions.sol).

solc: exponentiation/small_exp.sol — `**` is right-associative, so `2 ** 3 ** 2` is
`2 ** 9`, not `8 ** 2`. -/
theorem solkey_solc_Expressions_exponentiationIsRightAssociative :
    (sol!{ < uint r = 2 ** 3 ** 2;
             assert((r == 512)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.exponentiationZeroBaseZeroExponent` (solc/SolcExpressions.sol).

solc: exponentiation/literal_base.sol — `0 ** 0` is 1. -/
theorem solkey_solc_Expressions_exponentiationZeroBaseZeroExponent :
    (sol!{ < uint r = 0 ** 0;
             assert((r == 1)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.exponentiationZeroExponent` (solc/SolcExpressions.sol).

solc: exponentiation/literal_base.sol — anything to the power 0 is 1. -/
theorem solkey_solc_Expressions_exponentiationZeroExponent :
    (sol!{ < uint r = 7 ** 0;
             assert((r == 1)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.exponentiationSignedBaseEvenExponent` (solc/SolcExpressions.sol).

solc: exponentiation/signed_base.sol — a negative base loses its sign at an even
exponent.

concretized: solkey proves this for all parameters; ported at b = minusTwo.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_exponentiationSignedBaseEvenExponent :
    (sol!{ < int minusTwo = -2;
             int b = minusTwo;
             int even = b ** 2;
             assert((even == 4)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

/-- solkey `SolcExpressions.exponentiationSignedBaseOddExponent` (solc/SolcExpressions.sol).

solc: exponentiation/signed_base.sol — a negative base keeps its sign at an odd
exponent.

concretized: solkey proves this for all parameters; ported at b = minusTwo.

solkey tags this `@custom:key box`; the port makes the assumptions
true instead, so the diamond also proves that it does not revert. -/
theorem solkey_solc_Expressions_exponentiationSignedBaseOddExponent :
    (sol!{ < int minusTwo = -2;
             int b = minusTwo;
             int odd = b ** 3;
             int expectedOdd = -8;
             assert((odd == expectedOdd)) > (true) }).Holds
      State.solcExpressionsStore := by
  sol_wp

end SolcExpressions
end Solkey
end Solidity
