#!/usr/bin/env bash
# Check the solkey corpus (`SolidityCorpus`, generated by scripts/solkey-port.mjs).
#
#   1. re-derive every verdict from Lean (`solkey-port.mjs --probe`, into a
#      scratch copy) and diff the six columns against tests/solkey/expected.tsv;
#      the TestSuite rows are read off Solidity/TestSuite/Report.lean's pin,
#      not probed (scripts/check-testsuite.sh audits them without Lean);
#   2. diff the generated modules (Solidity/Corpus/ but the hand-written
#      Basic.lean and Imported.lean, SolidityCorpus.lean) and the scoreboard
#      (docs/corpus-parity.md) against what the generator writes;
#   3. build `SolidityCorpus`, which re-checks every pinned verdict: a `proved`
#      row is a theorem, an `evaluated`/`open` row a `#guard_msgs` pin, and a
#      `derived` TestSuite row a corollary of its `⊢` theorem, so the build
#      also builds the `SolkeyTestSuite` derivations it imports.
#
# Usage: scripts/check-corpus.sh [--update] [--solkey <keyext.solidity.examples>]
#   --update  re-pin in place (modules, expected.tsv, scoreboard), then build.
# The solkey checkout defaults to ../solkey (or SOLKEY_EXAMPLES).
# Exit 0 = no drift and the build passes, 1 = drift or a failing build.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
export PATH="$HOME/.elan/bin:$repo_root/scripts/lean-vscode/bin:$PATH"

update=0
args=()
for a in "$@"; do
  if [ "$a" = "--update" ]; then update=1; else args+=("$a"); fi
done

# The probe imports `Solidity.Corpus.Basic`.
lake build Solidity.Corpus.Basic >/dev/null

status=0
if [ "$update" = 1 ]; then
  node scripts/solkey-port.mjs --probe "${args[@]}"
else
  scratch="$(mktemp -d)"
  trap 'rm -rf "$scratch"' EXIT
  node scripts/solkey-port.mjs --probe --out "$scratch" "${args[@]}"
  if ! diff -u tests/solkey/expected.tsv "$scratch/tests/solkey/expected.tsv"; then
    echo "check-corpus: verdicts drifted from tests/solkey/expected.tsv (re-pin with --update)"
    status=1
  fi
  if ! diff -ru -x Basic.lean -x Imported.lean Solidity/Corpus "$scratch/Solidity/Corpus" ||
     ! diff -u SolidityCorpus.lean "$scratch/SolidityCorpus.lean" ||
     ! diff -u docs/corpus-parity.md "$scratch/docs/corpus-parity.md"; then
    echo "check-corpus: the corpus or its scoreboard is not what the generator writes (re-pin with --update)"
    status=1
  fi
fi

log="$(mktemp)"
if ! lake build SolidityCorpus >"$log" 2>&1; then
  grep -E "error" "$log" | head -40
  echo "check-corpus: lake build SolidityCorpus failed"
  status=1
fi
rm -f "$log"

[ "$status" = 0 ] && echo "check-corpus: ok"
exit "$status"
